### ISSUE TITLE
LocationOverlay에서 icon이 보이지 않습니다.

### ISSUE THREAD

**Issue by cyb9701** [note11g/flutter_naver_map#10]
안드로이드에서는 네이버에서 제공하는 현재 위치 마커가 보이는데
ios에서는 보이지 않습니다. 
별도로 지정하는 값이 있는지? 원래 ios에서 제공안하는지 궁금합니다

**Comment by note11g** [comment]
`initLocationTrackingMode` 속성이 어떻게 되어있으신지 여부와 가능하시다면 번거로우시겠지만 스크린샷 부탁드려도 될까요?

**Comment by cyb9701** [comment]
initLocationTrackingMode: LocationTrackingMode.NoFollow 입니다.

### Android
![Screenshot_20220411-105428](https://user-images.githubusercontent.com/59527787/162652317-cc5e7ccd-7df8-477e-b2b8-dfe779aa4d71.jpg)

### iOS
![iOS 이미지](https://user-images.githubusercontent.com/59527787/162652974-fac1e490-476c-4d6a-aae5-4f91b2046ff3.png)

**Comment by note11g** [comment]
현재위치 마커는 네이버 맵이 해당 위치추적 속성이 NoFollow가 아닐때만 작동합니다. 감사합니다.

**Comment by cyb9701** [comment]
```
 /// 위치를 추적하지 않습니다.
  None,

  /// 위치 추적이 활성화되고, 현위치 오버레이가 사용자의 위치를 따라 움직입니다.
  /// 그러나 지도는 움직이지 않습니다.
  NoFollow,
```
으로 나와있는데 None일 경우가 아닐때만 작동하는거 아닌가요?

**Comment by note11g** [comment]
아, 착각했네요. @cyb9701 님 말씀이 맞습니다.
관련사항 확인 후 다시 답변드릴 수 있도록 하겠습니다.

**Comment by cyb9701** [comment]
감사합니다!

**Comment by note11g** [comment]
죄송합니다. 원인을 분석하는데 오래 걸려서 시간이 좀 지체될 것 같습니다. 조금만 기다려주시면 감사드리겠습니다.

**Comment by cyb9701** [comment]
@note11g 
오류 수정 및 flutter 3.0 대응 업데이트는 대략 언제쯤일지 알 수 있을까요?

**Comment by note11g** [comment]
@cyb9701  6월 초로 예상됩니다. 학업+건강이슈가 있어 딜레이되는 점 매우 죄송하게 생각하고 있습니다... 조금만 기다려주시면 감사드리겠습니다ㅠㅠ

**Comment by cyb9701** [comment]
@note11g  알겠습니다. 감사합니다!

**Comment by cyb9701** [comment]
@note11g  더 오래 걸릴까요??

**Comment by note11g** [comment]
일단 일반 오버레이로 해결하시는 걸 추천드립니다.
어느 부분인지 문제 분석이 되지 않아, 7월 말~ 8월 초에 재설계된 1.0.0 버전으로 리뉴얼 예정이 있습니다..ㅠㅠ
조금만 기다려주시길 부탁드립니다.

**Comment by note11g** [comment]
1.0.0-dev1에서 해당 기능을 지원합니다. 감사합니다.
