### ISSUE TITLE
마커 이미지 배율 관련

### ISSUE THREAD

**Issue by swkim-lbstech** [note11g/flutter_naver_map#104]
안녕하세요. 
현제 1.0.2 버전 사용중입니다.
마커에 이미지를 넣기위해서 fromAssetImage 함수를 사용중인데
지도 화면에서 마커 이미지를 확인하면 1배율이 적용된 크기로 노출됩니다.

fromAssetImage 함수의 path를 확인하니 devicePixelRatio 적용된 path가 아닌
1배율의 path로 적용됩니다.

개인적으로 코드를 변경해야되는지 아니면 오류인건지 확인 부탁드리겠습니다.
감사합니다.

![KakaoTalk_Image_2023-07-06-14-41-00](https://github.com/note11g/flutter_naver_map/assets/72723485/9fc5a887-737d-4053-932d-64904458b08a)

**Comment by note11g** [comment]
https://github.com/note11g/flutter_naver_map/issues/91 해당 이슈와 동일한 증상으로 보입니다.
현재 고치고 있는 이슈 사항이나, 최근 개인 시간이 부족한 관계로 빠른 대응이 어렵습니다.
최대한 빠르게 수정할 수 있도록, 우선순위를 올려놓도록 하겠습니다. 감사합니다.

**Comment by swkim-lbstech** [comment]
감사합니다.
