### ISSUE TITLE
프로젝트 빌드 이슈

### ISSUE THREAD

**Issue by GoraebobKing** [note11g/flutter_naver_map#105]
해당 프로젝트를 다운받아서 빌드 했을경우 내부 swfit 코드 에러 이슈

Swift Compiler Error (Xcode): Consecutive statements on a line must be separated by ';'
/Users/****/Downloads/flutter_naver_map-main/ios/Classes/converter/AddableOverlay.swift:12:81

Swift Compiler Error (Xcode): Consecutive statements on a line must be separated by ';'
/Users/****/Downloads/flutter_naver_map-main/ios/Classes/converter/AddableOverlay.swift:14:29

Swift Compiler Error (Xcode): Expressions are not allowed at the top level
/Users/****/Downloads/flutter_naver_map-main/ios/Classes/converter/AddableOverlay.swift:12:82

Swift Compiler Error (Xcode): No such module 'NMapsMap'
/Users/****/Downloads/flutter_naver_map-main/ios/Classes/converter/AddableOverlay.swift:0:7

Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

해당 프로젝트 받아서 빌드 안드로이드는 정상적으로 작동하지만 ios는 작동 하지 않습니다.

어떤부분을 체크해봐야하는지 부탁좀 드립니다

**Comment by note11g** [comment]
안녕하세요. 사용 중이신 XCode 버전을 알려주실 수 있으실까요?

**Comment by GoraebobKing** [comment]
13.2 입니다.

**Comment by GoraebobKing** [comment]
> 안녕하세요. 사용 중이신 XCode 버전을 알려주실 수 있으실까요?

13.2 입니다

**Comment by note11g** [comment]
@GoraebobKing 
flutter run 말고, XCode에서 빌드해보시겠어요?
그래도 증상이 여전히 재현된다면, 다음 세가지 단계를 수행해주세요.
- `cd ios & pod update NMapsMap`를 실행해주세요.
- XCode 상에서 빌드 후에 기본적으로 나타나는 Warning들을 허용해주세요. 
- Flutter Cli가 아닌 Xcode상의 Compile Error를 이 이슈에 코멘트로 달아주세요.

**Comment by note11g** [comment]
코멘트 시점으로부터 너무 오래되어, 이슈를 Close 하겠습니다.
다시 코멘트 주신다면, 코멘트 후에 Re-open 부탁드리겠습니다:)
