### ISSUE TITLE
클러스터링 구현 로드맵 문의

### ISSUE THREAD

**Issue by battlecook** [note11g/flutter_naver_map#107]
README.md 에 적힌 Todo 목록 중 

* 클러스터링 구현 (추가 패키지로 제공될 예정입니다)

가 있는걸 확인했습니다. 마커 클러스터링 패키지로 이해했는데 해당 패키지 구현에 대한 로드맵 있는지 문의 드립니다.

**Comment by note11g** [comment]
안녕하세요.
현재 클러스터링은 계획 중입니다만, 각 플랫폼에 동일한 경험을 드리기 위해서 아직까지는 설계 단계를 진행하고 있습니다.
구체적인 출시 시기는 답변드리기 어려운 점, 양해 부탁드립니다.
