### ISSUE TITLE
LocationOverlay의 icon을 지정하는 기능 추가 요청

### ISSUE THREAD

**Issue by ismeeki17** [note11g/flutter_naver_map#11]
현재 위치 마커 커스텀(LocationOverlay)

아래의 위치 오버레이 아이콘을 커스텀할 수 있게 할수있을까요?

네이버 맵에서 기본으로 제공하는 아이콘이 아닌, 커스텀 아이콘을 넣고싶은데 방법을 모르겠습니다..ㅠㅠ

참고로 LocationOverlay icon 커스텀은 네이티브에서 지원하는 기능입니다.

/// <h2>위치 오버레이</h2>
/// <p>위치 오버레이는 사용자의 위치를 나타내는 데 특화된 오버레이이로, 지도상에 단 하나만
/// 존재합니다. 사용자가 바라보는 방향을 손쉽게 지정할 수 있고 그림자, 강조용 원도 나타낼 수 있습니다.</p>
class LocationOverlay {
  final MethodChannel _channel;

  /// 해당 객체를 참조하기 위햐서 [NaverMapController]의 맵버변수를 참조하거나,
  /// [NaverMapController]객체를 인자로 넘겨서 새롭게 생성하여 참조한다.
  LocationOverlay(NaverMapController controller)
      : _channel = controller._channel;

  /// 위치 오버레이의 좌표를 변경할 수 있습니다.
  /// 처음 생성된 위치 오버레이는 카메라의 초기 좌표에 위치해 있습니다.
  Future<void> setPosition(LatLng position) async {
    _channel.invokeMethod("LO#set#position", {
      'position': position._toJson(),
    });
  }

  /// __setBearing__ 을 이용하면 위치 오버레이의 베어링을 변경할 수 있습니다.
  /// flat이 true인 마커의 andgle속성과 유사하게 아이콘이 지도를 기준으로 회전합니다.
  /// > ***0.0은 정북쪽을 의미합니다.***
  ///
  /// 다음은 위치 오버레이의 베어링을 동쪽으로 변경하는 예제입니다.
  /// ```
  /// locaionOverlay.setBearing(90.0);
  /// ```
  Future<void> setBearing(double bearing) async {
    _channel.invokeMethod("LO#set#bearing", {'bearing': bearing});
  }
}

**Comment by note11g** [comment]
안녕하세요. 해당 패키지에 관심 가져주셔서 감사드립니다.
혹시 해당 기능을 지원하는 네이티브 SDK의 문서를 링크해주실 수 있으실까요?

**Comment by ismeeki17** [comment]
답변 감사합니다.

Android
https://navermaps.github.io/android-map-sdk/guide-ko/5-5.html
에서 [아이콘 - 이미지]를 참고해주십시오.

`locationOverlay.setIcon(OverlayImage.fromResource(R.drawable.location_overlay_icon));`

iOS
https://navermaps.github.io/ios-map-sdk/guide-ko/5-5.html
에서 [아이콘 - 이미지]를 참고해주십시오.
`locationOverlay.icon = NMFOverlayImage(name: "location_overlay_icon")`

**Comment by note11g** [comment]
확인 감사드립니다.
해당 기능 지원은 일정이 조금 미뤄질 수 있으나, 늦어도 5월 초까지 구현될 것 같습니다. 감사합니다.

**Comment by ismeeki17** [comment]
감사합니다.

**Comment by note11g** [comment]
먼저 많이 늦어진 점 사과드립니다.
해당 기능은, 1.0에서 현재 Android Platform에 한해, 개발이 완료되어 있는 기능입니다.
곧 iOS에서도 구현될 예정이니, 조금만 더 기다려주시면 감사드리겠습니다.

**Comment by note11g** [comment]
1.0.0-dev1에서 해당 기능을 지원합니다. 감사합니다.
