### ISSUE TITLE
건물 상세보기 옵션 기능을 지원하나요?

### ISSUE THREAD

**Issue by betrider** [note11g/flutter_naver_map#111]
지도에서 지하철 및 특정 정보를 터치 했을때 상세보기를 지원하고 싶은데

관련된 옵션이 있을까요?

**Comment by note11g** [comment]
onSymbolTap을 이용하여 symbol의 정보를 얻을 수 있습니다.

**Comment by note11g** [comment]
답변이 충분히 되셨으면 좋겠습니다.
추가로 질문이 있으시다면, 다시 이슈를 Re-open 해주시면 됩니다.
감사합니다.
