### ISSUE TITLE
NOverlayImage.fromWidget 시 마커 화질

### ISSUE THREAD

**Issue by gmelon** [note11g/flutter_naver_map#112]
안녕하세요. 라이브러리 정말 잘 사용하고 있습니다. 고생 많으십니다!

한가지 여쭤보려고 이슈 남깁니다.
아래와 같이 Icon 위젯으로 마커 이미지를 만들어 사용 중인데 마커로 만들면 화질이 떨어지는 것 같아서요. 원래 이런건지, 아니면 해결 방법이 있는지 문의드립니다.
```dart
defaultSearchIconImage = await NOverlayImage.fromWidget(
        widget:
            Icon(Icons.place_rounded, color: Colors.blue.shade600, size: 3.w),
        size: Size(4.w, 4.w),
        context: context);

NMarker marker = NMarker(
          id: "...",
          position: NLatLng(...),
          icon: defaultSearchIconImage);
```

![image](https://github.com/note11g/flutter_naver_map/assets/33623106/0f431e29-2c2c-44c1-b26b-87a821645158)

**Comment by swkim-lbstech** [comment]
관련 이슈는 devicePixelRatio가 적용되지 않아서 그렇습니다.
제작자분께서 바쁘신 거 같습니다. 언제쯤 해결될지는 몰라 개인적으로 수정해서 사용 중입니다.

**Comment by gmelon** [comment]
@swkim-lbstech 답변 감사합니다. 혹시 #106 이 PR이 해당 내용 수정한 커밋이 맞나요??

**Comment by swkim-lbstech** [comment]
네 맞습니다. 가져다 쓰셔도 되시고 제가 포크한거 가져다 쓰셔도 됩니다.

**Comment by note11g** [comment]
#91 이슈와 중복(Duplicate)이므로 Close합니다.
해당 이슈에 대한 코멘트가 있으시다면, #91 에 달아주시면 감사드리겠습니다.
