### ISSUE TITLE
setLocationTrackingMode와 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by tklee2020** [note11g/flutter_naver_map#113]
본래 네이버 지도 앱에서는 myLocation 버튼을 별도로 누르지 않아도 방향을 표시하는 화살표가 표시되며,
Gesture를 사용하여 화면을 확대/이동 하더라도 해당 화살표는 계속해서 유지되는데 

이 패키지를 사용하는 경우에는 setLocationTrackingMode를 follow로 설정해야만 해당 화살표가 표시되며, 
Gesture를 사용하는 경우 해당 설정이 바로 풀리게 됩니다.

계속해서 follow 상태를 유지하도록 하면 계속해서 현재 위치를 중앙으로 표시해야만 하기 때문에 불편함이 있습니다. 
현재 위치를 표시하되 follow, face하지 않는 noFollow 상태에서도 계속해서 화살표를 보여주는 설정이 가능한지 문의드립니다. 

감사합니다.

**Comment by note11g** [comment]
안녕하세요. flutter_naver_map을 이용해주셔서 감사드립니다.
flutter_naver_map은 Naver Map SDK를 기반으로 만들어진 라이브러리입니다.
하지만, 네이버 지도 앱은 Naver Map SDK와는 별개의 제품으로, Naver Map SDK에 수정을 가하여 만들어진 것으로 파악됩니다.
따라서, 기능의 구현이 네이버 지도 앱과 항상 일치할 수는 없는 점 양해바랍니다.

그리고 안타깝게도, 제스처를 이용한 LocationTrackingMode 전환을 막는 부분을 어떻게 구현하는지에 대해 SDK 문서에서는 언급하고 있지 않기 때문에, Naver Cloud의 Maps 팀에 문의 후에 해당 이슈에 대한 답변을 드릴 수 있을 것 같습니다.
