### ISSUE TITLE
초보적인 질문드립니다.

### ISSUE THREAD

**Issue by SpaceWhales** [note11g/flutter_naver_map#114]
안녕하세요.
마커 아이콘을 이미지로 변경하거나.
아이콘의 색상을 바꿀려고하니 안되는게 많아서 문의드립니다!
혹시 해당 구문관련해서 도움을 받을수있을까요?
물어볼때가 없어서 여기에 올립니다!

이슈가 아닌점 죄송합니다!

**Comment by gmelon** [comment]
https://note11.dev/flutter_naver_map/element/overlay/#%EC%98%A4%EB%B2%84%EB%A0%88%EC%9D%B4%EC%97%90-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%A7%80%EC%A0%95

마커 이미지는 이 방법으로 변경가능합니다.
문서가 상세하게 잘 나와있어서 참고하시면 도움 많이 될 것 같아요!

**Comment by SpaceWhales** [comment]
> 

감사합니다! 혹시 마커 정보창은 닫기명령어가 따로있을까요?
openInfoWindow를 써써 띄웟는데
close는 안되더라구요 ㅠ

**Comment by note11g** [comment]
> > 
> 
> 감사합니다! 혹시 마커 정보창은 닫기명령어가 따로있을까요?
> openInfoWindow를 써써 띄웟는데
> close는 안되더라구요.
> 
> 아 그리고 혹시 내가 바라보고있는 지도의 정중앙? 이라고해야되나.
> 화면상의 좌표값을 따는건 문서에 없던데 혹시 정보를 알수있을까요?

집 가서 답변드리겠습니다. 모두 가능은 합니다.

**Comment by note11g** [comment]
1. 마커에 열린 정보창 열기 및 닫기 예제
```dart
NInfoWindow? infoWindow;

Future<void> openInfoWindow(NMarker marker) async {
    infoWindow = NInfoWindow.onMarker(id: "1", text: "infoWindow");
    await marker.openInfoWindow(infoWindow!);
}

void closeInfoWindow() {
    infoWindow?.close();
}
```

2. 화면 정중앙 화면상 좌표 얻기
```dart
// Point 타입은 dart:math에 있습니다.
Future<Point<double>> getNowShownPoint() async {
    final centerPosition = await mapController.getCameraPosition().then((p) => p.target);
    return mapController.latLngToScreenLocation(centerPosition);
}
```
