### ISSUE TITLE
[All Platform] 지도에 오버레이가 추가되기 전에 공통 오버레이 옵션이 적용되지 않는 문제

### ISSUE THREAD

**Issue by tklee2020** [note11g/flutter_naver_map#115]
마커에 minZoom, maxZoom을 설정했음에도 마커가 zoomLevel에 따라 표시되고 사라지는 기능이 동작하지 않는데 혹시 제가 잘못 설정한걸까요..? 그리고 마커들에 zIndex 또한 설정했을 때 제대로 동작하지 않습니다.

**Comment by note11g** [comment]
안녕하세요. 먼저, 이슈를 제보해주셔서 감사드립니다.

`minZoom`/`maxZoom` 설정이, 지도에 오버레이가 추가되기 전에 제대로 적용되지 않는 현상을 확인했습니다.
안타깝게도, 이는 버그가 맞습니다. 최대한 빠르게 수정하도록 하겠습니다. 
그 전까지는 아래 예제코드처럼, 오버레이가 추가된 후에 해당 속성들을 적용하시면 됩니다.

```dart
await mapController.addOverlay(overlay).then((_) {
    overlay
      ..setMinZoom(8)
      ..setMaxZoom(10);
});
```

감사합니다. 좋은 하루 되시길 바라겠습니다.

**Comment by note11g** [comment]
Not processed at `AddableOverlay.createMapOverlay` (Native Side)
