### ISSUE TITLE
마커 관련 질문 드립니다. 

### ISSUE THREAD

**Issue by 2sklee** [note11g/flutter_naver_map#118]
1. 마커의 오버레이에 대한 이미지를 변경 할 수 있는지 궁금합니다. 

2. 마커의 폰트 크기가  android/ios 모두 다르게 나오고 있습니다. 
   폰트에 대한 커스텀이 가능 할까요?

개발 언어는 flutter를 사용하고 있습니다.

**Comment by note11g** [comment]
1. 가능합니다. 문서 - 오버레이 항목을 참고해주세요.
2. Android에는 TextScaleFactor가 따로 존재합니다. 해당 항목은, 휴대전화 설정-글꼴-글꼴 크기에서 조절하실 수 있습니다. 만약 TextScaleFactor(`MediaQuery.of(context).textScaleFactor`)가 1.0인데도, 글꼴 크기가 다르다면 코멘트 부탁드리겠습니다.

**Comment by 2sklee** [comment]
빠른 답변 감사합니다. 

2번 폰트 크기에 대해서는 코드상에서 수정을 할 수 있을까요?
휴대폰 설정에서 변경하는 부분은 고려하고 있지가 않습니다. 

예를 들면 
`Text(
                    '폰트 크기 조절 ',
                    style: TextStyle(fontWeight: FontWeight.w600),
                  ),`

**Comment by note11g** [comment]
TextStyle의 fontSize 옵션을 조절하시면 됩니다. 감사합니다.

**Comment by note11g** [comment]
@2sklee 답변이 늦어진 점 죄송합니다.
다음은 캡션의 글꼴 사이즈에 대한 조정 예시입니다.
fontWeight 속성은 적용할 수 없습니다. 다만, `NOverlayCaption`의 `haloColor` 속성을 이용하여 글자 외곽선을 추가하여 글자를 더 굵게 보이는 것은 가능합니다.
```dart
final marker = NMarker(id: "put your id", position: position)
      ..setCaption(const NOverlayCaption(text: "put your text", textSize: 12));
await mapController.addOverlay(marker);
```
