### ISSUE TITLE
지도 페이지 위에 새로운 페이지를 열고 화면을 잠갔다 열면 지도가 위에 나옵니다

### ISSUE THREAD

**Issue by shimbeomseok-gn** [note11g/flutter_naver_map#120]
아래와 같은 현상이 있습니다 확인 부탁 드립니다
지도가 있는 페이지가 UI 페이지 하단에 남아있으면 Background로 앱을 내렸다 Foreground오 올리면 무조건 지도가 맨위에 그려지네요

Case 1
1. 지도 페이지 생성
2. UI가 들어 있는 페이지 열기
3. 화면 잠금 버튼으로 화면 끔 또는 홈 버튼으로 앱을 Background로 내림
4. 화면 다시 켬 또는 앱을 Foreground로 올림
5. 지도만 제일 상단에 올라와 있음

Case 2
1. IndexedStack 에 UI 페이지와 지도 페이지 생성
2. UI가 들어 있는 페이지로 시작
3. 지도가 있는 페이지로 이동
4. UI가 들어있는 페이지로 이동
5. 화면 잠금 버튼으로 화면 끔 또는 홈 버튼으로 앱을 Background로 내림
6. 화면 다시 켬 또는 앱을 Foreground로 올림
7. 지도만 제일 상단에 올라와 있음

Flutter 3.10.5
Dart 3.0.5

**Comment by note11g** [comment]
안녕하세요. 플러터 네이버 맵을 사용해 주셔서 감사드립니다.
말씀 주신 증상은 #56 이슈와 비슷한 이슈인 것 같습니다.
임시 해결법이 있으니, 확인 후 적용해 보시기 바랍니다.
문제가 해결되셨으면 좋겠습니다. 좋은 하루 보내세요.
