### ISSUE TITLE
안드로이드의 경우, 지도가 있는 화면에서 이동할 때 화면이 깜빡입니다.

### ISSUE THREAD

**Issue by BurnFaithful** [note11g/flutter_naver_map#122]
현재 해당 패키지로 네이버 지도를 표시(전체 지도가 아닌 Container로 사이즈를 지정한 작은 지도)하는 화면이 하나 있고, 
해당 화면에서 이탈(back, push, ... 모두)할 때 이동한 화면에서 이전 화면이 일시적으로 깜빡입니다.
이 부분은 심각한 UX 이슈가 발생하는데 원인 파악이 어렵습니다.
디버깅 결과 안드로이드에서만 발생하는 이슈로 보입니다.
아래는 해당 이슈와 관련된 에러 로그입니다.

E/Surface (23307): freeAllBuffers: 1 buffers were freed while being dequeued!
E/Surface (23307): getSlotFromBufferLocked: unknown buffer: 0xb400007bd3495620

**Comment by YongWoo-8933** [comment]
같은 에러를 겪고 있습니다. 이전에 앱의 생명주기가 변할 때 지도가 위로 튀어나오는 현상과도 관련이 있어보입니다.

**Comment by battlecook** [comment]
같은 증상이 있습니다. 혹시 해결하는법 있을까요?

**Comment by note11g** [comment]
안녕하세요. 해당 현상은 Flutter 엔진상의 이슈로, 제가 우회적으로 해결할 수 있는 방법을 찾고 있는 중입니다.

**Comment by note11g** [comment]
#84 이슈와 중복입니다. 해당 이슈에 코멘트 부탁드립니다.
