### ISSUE TITLE
[dev-1.0.3] iOS에서 기본 마커가 너무 작게 표시되는 문제

### ISSUE THREAD

**Issue by note11g** [note11g/flutter_naver_map#130]
[dev-1.0.3] iOS에서 기본 마커가 너무 작게 표시되는 문제 (Caused #126)

<img width="360" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/67783062/227417a0-2364-4abd-a0a4-c744fbe06485">

<img width="360" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/67783062/f26de5bd-88ab-490e-b5a1-d6c3f2468292">

**Comment by note11g** [comment]
work branch: [refix/#91](https://github.com/note11g/flutter_naver_map/tree/refix/%2391)

**Comment by note11g** [comment]
https://github.com/note11g/flutter_naver_map/blob/b7c93bcf0dbabd838773014bc16b8e8d5be50170/lib/src/type/map/overlay/overlay/addable/marker.dart#L111

https://github.com/note11g/flutter_naver_map/blob/12a23c240a1fffb0e250fa7272361159c74b9312/ios/Classes/model/map/overlay/overlay/NMarker.swift#L38-L39

기본 사이즈(autoSize)로 인해 발생. 또한, icon이 있는지 여부 검사 필요

**Comment by Soogyo-In** [comment]
@note11g refix/#91 브랜치에서 수정하여 PR 올리겠습니다.

**Comment by note11g** [comment]
@Soogyo-In 일단 나름대로 수정은 했는데.. 해당(#130) 이슈에서 더 수정이 필요해보이는 사항이 있으신가요?

**Comment by Soogyo-In** [comment]
@note11g 아 아닙니다. 착각했네요.
