### ISSUE TITLE
플랫폼별로 NInfoWindow(인포윈도우)의 크기가 다르게 나오는 현상

### ISSUE THREAD

**Issue by minseok-jeong-gn** [note11g/flutter_naver_map#132]
### 문제점
iOS에서 NInfoWindow의 텍스트와 말풍선 크기가 너무 크게 나옵니다.
사이즈를 줄이는 방법이 있을까요?

아래 스크린샷 첨부합니다.

| Android 스크린샷 (정상)| iOS 스크린샷 (너무 큼)|
| ------------- | ------------- |
| <img src="https://github.com/note11g/flutter_naver_map/assets/142773097/e2935677-94da-415a-b0b0-3ed23e5511c3" width=100% />   |<img src="https://github.com/note11g/flutter_naver_map/assets/142773097/2675198e-527d-411d-9606-f43a1a364a01" width=100% />  |

```dart
// 사용한 코드
// NMarker marker
    await marker.openInfoWindow(
      NInfoWindow.onMarker(id: '${marker.hashCode}', text: infoText),
    );
```

버전정보:
- flutter_naver_map 1.0.2
- Flutter version 3.13.9 on channel stable

**Comment by note11g** [comment]
안녕하세요. 라이브러리를 사용해주셔서 감사드립니다.

해당 현상은 버그는 아닌 것으로 확인됩니다.
각 플랫폼의 infowindow 구현이 달라 생기는 문제인 것 같습니다.

다만, 해결을 위해 시도해볼 수 있는 방안이 있긴 합니다.
기본 title 뷰가 아닌, 커스텀하여 뷰를 생성하여 최대한 비슷하게 맞추는 것인데요,
사용성에 큰 지장을 주지 않는 이슈이고, 시간이 많이 들 듯하여, 여유가 있다면 작업하게 될 것 같습니다.

좋은 하루 되시길 바라며,
추가적인 질문이나 코멘트 있으시다면, 편하게 남겨주세요.
감사합니다.
