### ISSUE TITLE
xcode 15.0 이상 버전 업데이트 이후 에러 size 파라미터

### ISSUE THREAD

**Issue by unyang09** [note11g/flutter_naver_map#134]
error: The named parameter 'size' isn't defined. (undefined_named_parameter at [flutter_naver_map] lib/src/util/widget_to_image.dart:35)

//widget_to_image.dart

final renderView = RenderView(
        view: view,
        configuration: ViewConfiguration(
            size: size, devicePixelRatio: view.devicePixelRatio),
        child:
            RenderPositionedBox(alignment: Alignment.center, child: renderBox));
            
            
          
해당 코드에서 파라미터 에러가 발생합니다

**Comment by note11g** [comment]
안녕하세요. 이슈 제보에 감사드립니다.
증상 재현을 위해, `flutter doctor -v` 내용을 부탁드리겠습니다.

**Comment by unyang09** [comment]
gimdonghyeon@gimdonghyeon-ui-MacBookAir map222 % flutter doctor -v
[✓] Flutter (Channel master, 3.18.0-11.0.pre.12, on macOS 14.1.2 23B92 darwin-arm64, locale ko-KR)
    • Flutter version 3.18.0-11.0.pre.12 on channel master at /Users/gimdonghyeon/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 11a9cb7029 (2시간 전), 2023-12-12 20:09:13 -0800
    • Engine revision 9039ac78cf
    • Dart version 3.3.0 (build 3.3.0-219.0.dev)
    • DevTools version 2.30.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gimdonghyeon/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • 김동현의 iPhone (mobile) • 00008120-00166D4934DB401E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 120.0.6099.71

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by note11g** [comment]
xcode 15.1에서 해당 현상 재현에 실패하였습니다.
해당 이슈는 xcode와는 별개 이슈인 것으로 보입니다.
xcode build cache를 clean해보신 후에도 해당 이슈가 지속적으로 발생한다면, 
코멘트와 함께 다시 이 이슈를 오픈해주세요. 감사합니다.
