### ISSUE TITLE
Android 9 (SDK 28) 이하 버전에서 위젯 전체가 검은 화면으로 렌더링되는 문제

### ISSUE THREAD

**Issue by nteko** [note11g/flutter_naver_map#135]
설명에는 안드로이드 5.1 이상에서는 동작하는걸로 되어있는데, 9 이하에서는 뜨지 않습니다..

혹시 9이하 버전에서는 다른 방법이 있는지요?

**Comment by note11g** [comment]
안녕하세요.
사용하시는 flutter, android 버전 정보, engine 정보(impeller 사용여부) 부탁드리겠습니다.

**Comment by nteko** [comment]
안녕하세요?
플러터 정보 입니다.
Flutter 3.16.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0366e0a3f (9 days ago) • 2023-12-05 19:46:39 -0800
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
안드로이드 버전은 갤럭시 S8 에서 최종 안드로이드 업데이트(9 버전)까지 모두 한 후 테스트 하였습니다. Note 8에서도 마찬가지로
되지 않습니다.
임펠러 사용여부는 따로 설정하지 않는 기본 상태 입니다. (안드로이드에서도 기본이 임펠러 사용이라면 임펠러 사용상태 입니다.)
감사합니다.


2023년 12월 13일 (수) 오후 4:40, 김노트 ***@***.***>님이 작성:

**Comment by jonghyeok-lim** [comment]
flutter 3.16 이상 버전에서 발생하네요. 3.13으로 다운그레이드하면 괜찮습니다.
- 안드로이드 os9

**Comment by nteko** [comment]
안드로이드 9 이하버전에서의 플루터 3.16 버전 이상 지원은 혹시 진행이 될 예정인지요...?

**Comment by note11g** [comment]
@nteko @jonghyeok-lim 

해당 현상에 대한 오류 로그가 따로 생성되지 않나요?
생성된다면, 오류 로그를 첨부 부탁드리겠습니다.
스크린샷도 함께 첨부해주시면 더 빠르게 대응이 가능할 것 같습니다. 감사합니다.

**Comment by johmartin** [comment]
안녕하세요?  저 또한 같은 증상이 발생하여서 
혹시나 도움이 되실까해서 
캡처화면 및 로그 파일 복사해서 올립니다.


===> 오버레이의 클릭리스너가 설정되지 않았음에도, 클릭 이벤트가 발생하는 문제 #96
위의 글 올렸던 사람입니다. ^^ 


![android9_flutternavermap12](https://github.com/note11g/flutter_naver_map/assets/82506516/7cdee33f-f309-441b-9c0e-5b5ba491ad9b)


====================================================================================
====================================================================================
====================================================================================

Performing hot reload...
Syncing files to device SM N950N...
D/SurfaceView(23546): onWindowVisibilityChanged(8) false com.naver.maps.map.MapView$3{c4236be V.E...... ........ 0,0-1080,2031} of ViewRootImpl@472e760[MainActivity]
D/SurfaceView(23546): show() Surface(name=SurfaceView - Sys2030:com.navermaptest.app/com.navermaptest.app.MainActivity@c4236be@8[23546])/@0xbabf419 com.naver.maps.map.MapView$3{c4236be V.E...... ........ 0,0-1080,2031}
D/SurfaceView(23546): surfaceDestroyed callback.size 1 #2 com.naver.maps.map.MapView$3{c4236be V.E...... ........ 0,0-1080,2031}
W/libEGL  (23546): EGLNativeWindowType 0x703731a010 disconnect failed
D/SurfaceView(23546): destroy() Surface(name=SurfaceView - Sys2030:com.navermaptest.app/com.navermaptest.app.MainActivity@c4236be@8[23546])/@0xbabf419 com.naver.maps.map.MapView$3{c4236be V.E...... ........ 0,0-1080,2031}
D/Dialog  (23546): mIsSamsungBasicInteraction = false
D/Dialog  (23546): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
W/PlatformViewsController(23546): Unexpected platform view context for view ID 0; some functionality may not work correctly. When constructing a platform view in the factory, ensure that the view returned from PlatformViewFactory#create returns the provided context from getContext(). If you are unable to associate the view with that context, consider using Hybrid Composition instead.
E/BufferQueueProducer(23546): [SurfaceTexture-0-23546-1] connect: already connected (cur=1 req=1)
I/DecorView(23546): createDecorCaptionView >> DecorView@7d59753[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/InputTransport(23546): Input channel constructed: fd=137
D/ViewRootImpl@ba08145[MainActivity](23546): setView = DecorView@7d59753[MainActivity] TM=true MM=false
D/OpenGLRenderer(23546): eglDestroySurface = 0x703501c080, 0x7037319000
D/ViewRootImpl@472e760[MainActivity](23546): dispatchDetachedFromWindow
D/ViewRootImpl@472e760[MainActivity](23546): Surface release. android.view.ViewRootImpl.doDie:7964 android.view.ViewRootImpl.die:7932 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.Dialog.dismissDialog:518 android.app.Dialog.dismiss:501 android.app.Dialog.cancel:1462 
D/InputTransport(23546): Input channel destroyed: fd=139
V/InputMethodManager(23546): Not IME target window, ignoring
D/SurfaceView(23546): onWindowVisibilityChanged(0) true com.naver.maps.map.MapView$3{c4236be V.E...... ......ID 0,0-1080,2031} of ViewRootImpl@ba08145[MainActivity]
D/ViewRootImpl@ba08145[MainActivity](23546): dispatchAttachedToWindow
Reloaded 1 of 2378 libraries in 1,342ms (compile: 29 ms, reload: 573 ms, reassemble: 706 ms).
D/ViewRootImpl@ba08145[MainActivity](23546): Relayout returned: old=[0,0][1080,2031] new=[0,0][1080,2031] result=0x7 surface={valid=true 481962332160} changed=true
D/mali_winsys(23546): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(23546): eglCreateWindowSurface = 0x703501c080, 0x7037319010
D/SurfaceView(23546): show() Surface(name=SurfaceView - Sys2030:com.navermaptest.app/com.navermaptest.app.MainActivity@c4236be@9[23546])/@0xb18409a com.naver.maps.map.MapView$3{c4236be V.E...... ......ID 0,0-1080,2031}
D/SurfaceView(23546): surfaceCreated 1 #8 com.naver.maps.map.MapView$3{c4236be V.E...... ......ID 0,0-1080,2031}
D/SurfaceView(23546): surfaceChanged (1080,2031) 1 #8 com.naver.maps.map.MapView$3{c4236be V.E...... ......ID 0,0-1080,2031}
D/SurfaceView(23546): onWindowVisibilityChanged(8) false com.naver.maps.map.MapView$3{be9d0e9 V.E...... ........ 0,0-1080,1884} of ViewRootImpl@1cd89b6[MainActivity]
D/SurfaceView(23546): show() Surface(name=SurfaceView - Sys2030:com.navermaptest.app/com.navermaptest.app.MainActivity@be9d0e9@4[23546])/@0xd3d46b7 com.naver.maps.map.MapView$3{be9d0e9 V.E...... ........ 0,0-1080,1884}
D/mali_winsys(23546): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView(23546): surfaceDestroyed callback.size 1 #2 com.naver.maps.map.MapView$3{be9d0e9 V.E...... ........ 0,0-1080,1884}
W/libEGL  (23546): EGLNativeWindowType 0x6efcfb4010 disconnect failed
D/SurfaceView(23546): destroy() Surface(name=SurfaceView - Sys2030:com.navermaptest.app/com.navermaptest.app.MainActivity@be9d0e9@4[23546])/@0xd3d46b7 com.naver.maps.map.MapView$3{be9d0e9 V.E...... ........ 0,0-1080,1884}
D/Dialog  (23546): mIsSamsungBasicInteraction = false
D/Dialog  (23546): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
W/PlatformViewsController(23546): Unexpected platform view context for view ID 0; some functionality may not work correctly. When constructing a platform view in the factory, ensure that the view returned from PlatformViewFactory#create returns the provided context from getContext(). If you are unable to associate the view with that context, consider using Hybrid Composition instead.
E/BufferQueueProducer(23546): [SurfaceTexture-0-23546-10] connect: already connected (cur=1 req=1)
I/DecorView(23546): createDecorCaptionView >> DecorView@9ccecc1[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/InputTransport(23546): Input channel constructed: fd=147
D/ViewRootImpl@7c2fb43[MainActivity](23546): setView = DecorView@9ccecc1[MainActivity] TM=true MM=false
D/OpenGLRenderer(23546): eglDestroySurface = 0x7027ced680, 0x6efcf81000
D/ViewRootImpl@1cd89b6[MainActivity](23546): dispatchDetachedFromWindow
D/ViewRootImpl@1cd89b6[MainActivity](23546): Surface release. android.view.ViewRootImpl.doDie:7964 android.view.ViewRootImpl.die:7932 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.Dialog.dismissDialog:518 android.app.Dialog.dismiss:501 android.app.Dialog.cancel:1462 
D/InputTransport(23546): Input channel destroyed: fd=158
D/ViewRootImpl@ba08145[MainActivity](23546): Relayout returned: old=[0,0][1080,2031] new=[0,0][1080,2031] result=0x3 surface={valid=true 481962332160} changed=false
V/InputMethodManager(23546): Not IME target window, ignoring
D/SurfaceView(23546): onWindowVisibilityChanged(0) true com.naver.maps.map.MapView$3{be9d0e9 V.E...... ......ID 0,0-1080,1884} of ViewRootImpl@7c2fb43[MainActivity]
D/ViewRootImpl@7c2fb43[MainActivity](23546): dispatchAttachedToWindow
D/ViewRootImpl@7c2fb43[MainActivity](23546): Relayout returned: old=[0,0][1080,1884] new=[0,0][1080,1884] result=0x7 surface={valid=true 476691718144} changed=true
D/mali_winsys(23546): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(23546): eglCreateWindowSurface = 0x7027ced680, 0x6efd0a6010
D/SurfaceView(23546): show() Surface(name=SurfaceView - Sys2030:com.navermaptest.app/com.navermaptest.app.MainActivity@be9d0e9@5[23546])/@0xf6595c0 com.naver.maps.map.MapView$3{be9d0e9 V.E...... ......ID 0,0-1080,1884}
D/SurfaceView(23546): surfaceCreated 1 #8 com.naver.maps.map.MapView$3{be9d0e9 V.E...... ......ID 0,0-1080,1884}
D/SurfaceView(23546): surfaceChanged (1080,1884) 1 #8 com.naver.maps.map.MapView$3{be9d0e9 V.E...... ......ID 0,0-1080,1884}
D/ViewRootImpl@ba08145[MainActivity](23546): MSG_RESIZED: frame=Rect(0, 0 - 1080, 2031) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/mali_winsys(23546): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/ViewRootImpl@7c2fb43[MainActivity](23546): Relayout returned: old=[0,0][1080,1884] new=[0,0][1080,1884] result=0x3 surface={valid=true 476691718144} changed=false
D/ViewRootImpl@7c2fb43[MainActivity](23546): MSG_RESIZED: frame=Rect(0, 0 - 1080, 1884) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl@12f92d0[MainActivity](23546): ViewPostIme pointer 0
D/ViewRootImpl@12f92d0[MainActivity](23546): ViewPostIme pointer 1
D/ViewRootImpl@12f92d0[MainActivity](23546): ViewPostIme pointer 0
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:2.2857144
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:3.0434783
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:3.4545455
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:2.2941177
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:3.25
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:2.764706
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:2.5263157
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:2.45
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:3.0454545
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:2.9411764
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:2.75
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:3.1538463
D/ViewRootImpl(23546): [ViewRootImpl] action cancel - 1, eccen:3.1538463
D/ViewRootImpl@12f92d0[MainActivity](23546): ViewPostIme pointer 1
D/SmartClipDataCropperImpl(23546): doExtractSmartClipData : Extraction start! reqId = 152  Cropped area = Rect(540, 1110 - 541, 1111)  Package = com.navermaptest.app
D/SmartClipDataCropperImpl(23546): traverseView : Contains meta data : Rect(0, 0, 1080, 2094)	FlutterTextureView@3ee4dec	plain_text	
D/SmartClipDataCropperImpl(23546): getOpaqueBackgroundRect : opaqueRect=null  element=com.samsung.android.content.smartclip.SmartClipDataElementImpl@8bd45b5
D/SmartClipDataCropperImpl(23546): getOpaqueBackgroundRect : opaqueRect=null  element=com.samsung.android.content.smartclip.SmartClipDataElementImpl@2d2044a
D/SmartClipDataCropperImpl(23546): getOpaqueBackgroundRect : opaqueRect=null  element=com.samsung.android.content.smartclip.SmartClipDataElementImpl@bf68fbb
D/SmartClipDataCropperImpl(23546): addAppMetaTag : package name is com.navermaptest.app
D/SmartClipDataCropperImpl(23546): sendExtractionResultToSmartClipService : -- Extracted SmartClip data information --
D/SmartClipDataCropperImpl(23546): sendExtractionResultToSmartClipService : Request Id : 152
D/SmartClipDataCropperImpl(23546): sendExtractionResultToSmartClipService : Extraction mode : 1
D/SemSmartClipDataRepository(23546): ----- Start of SmartClip repository informations -----
D/SemSmartClipDataRepository(23546): ** Content type : image
D/SemSmartClipDataRepository(23546): ** Meta area rect : Rect(0, 0 - 1080, 2094)
D/SemSmartClipDataRepository(23546): ** Captured image file path : null
D/SemSmartClipDataRepository(23546): ----- End of SmartClip repository informations -----
D/SmartClipDataCropperImpl(23546): sendExtractionResultToSmartClipService : Elapsed = 6
D/SmartClipRemoteRequestDispatcher(23546): dispatchScrollableAreaInfo : windowRect = Rect(0, 0 - 1080, 2220)
D/SmartClipRemoteRequestDispatcher(23546): dispatchScrollableAreaInfo : Scrollable view count = 1
D/SmartClipRemoteRequestDispatcher(23546): dispatchScrollableAreaInfo : Unscrollable view count = 0
D/SmartClipRemoteRequestDispatcher(23546): dispatchScrollableAreaInfo : Pkg=com.navermaptest.app Activity=null
D/ViewRootImpl@12f92d0[MainActivity](23546): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(23546): prepareNavigationBarInfo() DecorView@91ecb1b[MainActivity]
D/InputMethodManager(23546): getNavigationBarColor() -855310
D/ViewRootImpl@12f92d0[MainActivity](23546): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(23546): prepareNavigationBarInfo() DecorView@91ecb1b[MainActivity]
D/InputMethodManager(23546): getNavigationBarColor() -855310
I/flutter (23546): RESUMED !!!!!!!!!!!!

**Comment by note11g** [comment]
일단 해당 현상이 왜 발생하는지는 아직까지 파악하지 못했습니다만, 워낙 급한 사안이라 SDK 26(Android 8.0) 이상에서는 정상적으로 동작하도록 조치해두었습니다.
[해당 브랜치](https://github.com/note11g/flutter_naver_map/tree/fix/%23135)에서 수정중에 있습니다.

임시적으로 다음처럼 사용하실 수 있습니다. (pubspec.yaml)
```yaml
flutter_naver_map:
    git:
      url: https://github.com/note11g/flutter_naver_map.git
      ref: fix/#135
```

임시 해결책에 대한 부작용은 다음과 같습니다.
- SDK 21\~25 (5.0\~7.1)에서는 지도 뷰를 여러개 띄울 경우, 멈추는 현상이 발생할 수 있습니다.

**Comment by note11g** [comment]
90fda47ccce9d1d1d1231b924daee8faf50b915e 
해당 커밋은, 지도가 두개 이상 z축 상으로 겹쳐 있을 경우, 문제가 발생할 수 있습니다. (네비게이터 스택에 남아있다면, 백그라운드로 전환된 후에 문제가 발생합니다.)
또한, SDK 26(8.0) 이상의 문제만 해결합니다. 
SDK 21~25는 두개 이상 z축 상으로 겹쳐있을 경우, 백그라운드 전환 여부와 관계 없이 하단 지도가 보여집니다.

**Comment by note11g** [comment]
Flutter stable(3.16.1), main(3.18.0-18.0.pre.28) 동일 증상 확인.

확인된 관련 로그
```
Unexpected platform view context for view ID 0; 
some functionality may not work correctly. 
When constructing a platform view in the factory, ensure that the view returned from PlatformViewFactory#create returns the provided context from getContext(). 
If you are unable to associate the view with that context, consider using Hybrid Composition instead.
```

**Comment by note11g** [comment]
1.1.0 버전에서 임시로 #135 이슈를 수정합니다. (PR: #148)

이 PR에는 SideEffect가 포함되어 있습니다.

## Known SideEffects
- `SDK 26(8.0)~28(9.0)` : 지도가 두개 이상 z축 상으로 겹쳐 있을 경우, 백그라운드 전환 시, 하단 지도가 보여짐.
- `SDK 23(6.0)~25(7.1)` : 지도가 두개 이상 z축 상으로 겹쳐있을 경우, 백그라운드 전환 여부와 관계 없이 하단 지도가 보여집니다.

**Comment by note11g** [comment]
> [main/master channel에서 비슷한 문제가 해결되었다는 보고](https://github.com/flutter/flutter/issues/138947)가 있어, 시도해보았으나, Flutter stable(3.16.1), main(3.18.0-18.0.pre.28) 동일 증상 확인.
> 
> 확인된 관련 로그
> 
> ```
> Unexpected platform view context for view ID 0; 
> some functionality may not work correctly. 
> When constructing a platform view in the factory, ensure that the view returned from PlatformViewFactory#create returns the provided context from getContext(). 
> If you are unable to associate the view with that context, consider using Hybrid Composition instead.
> ```

해당 이슈는 화면이 렌더링되지 않는 것과 관련이 없는 것으로 추정됩니다.
https://github.com/flutter/engine/pull/35997 해당 변경사항과 관련이 있습니다.

869466c0f8f31501caaa70889f3d27585a401cb2 이 경고를 뜨지 않도록 해결하는 커밋입니다.

**Comment by note11g** [comment]
https://github.com/flutter/packages/commit/e393d452beaf4b216e2567bc2cee0225087f4662

**Comment by note11g** [comment]
#153 PR은 해당 이슈를 해결합니다.
자세한 내용은 PR 코멘트와, #152 이슈를 참고하세요.
