### ISSUE TITLE
NMarker의 id에 접근할 수 없습니다.

### ISSUE THREAD

**Issue by Han-Sungyu** [note11g/flutter_naver_map#136]
https://note11.dev/flutter_naver_map/element/overlay/#%ED%84%B0%EC%B9%98-%EC%9D%B4%EB%B2%A4%ED%8A%B8
위 링크에 나온 것 과 같이
`marker.setOnTapListener((NMarker marker) {
  print("마커가 터치되었습니다. id: ${marker.id}");
});`
할 경우 에러가 납니다.

NMarker의 id값을 참조할 수 없습니다.

**Comment by note11g** [comment]
안녕하세요.
혹시 어떤 오류가 나는지 로그를 볼 수 있을까요?

**Comment by Han-Sungyu** [comment]
@note11g 

컴파일 오류가 아니라 로그는 따로 없습니다.
게터가 설정되지 않아 프레임워크에서 오류를 감지합니다.
The getter 'id' isn't defined for the type 'NMarker'.

혹시 `marker.info.id` 로 접근하여야 하는 것인가요?

**Comment by note11g** [comment]
아, 네. 맞습니다. 해당부분 문서가 업데이트 되지 않아 혼란을 겪으신 것 같습니다. 죄송합니다.

**Comment by note11g** [comment]
문서 업데이트 필요
