### ISSUE TITLE
오버레이에 태그를 추가할 수 없습니다.

### ISSUE THREAD

**Issue by Han-Sungyu** [note11g/flutter_naver_map#137]
https://note11.dev/flutter_naver_map/element/overlay/ 문서에는 오버레이에 태그를 지정할 수 있다고 나오지만 실제로 태그를 지정할 수 없습니다.

```
var marker = NMarker(...);
marker.setTag("marker"); // 정의되지 않은 함수
marker.tag; // 해당 속성이 존재하지 않음
```

태그를 지정할 수 있도록 해주세요.

**Comment by note11g** [comment]
안녕하세요. 이슈를 제보해주셔서 감사드립니다.
혹시 어떤 오류 로그가 나오는지, 첨부 부탁드릴 수 있을까요?

**Comment by Han-Sungyu** [comment]
런타임 오류가 아닙니다. 프레임워크에서 감지된 오류입니다.
초기 글에 제공한 예시 코드로 확인이 가능합니다.
개발자들이 보통 빨간줄이라 말하는 그것과 같습니다.

**Comment by note11g** [comment]
@Han-Sungyu  아, 네. 맞습니다. tag는 dev preview 버전까지만 존재했던 프로퍼티입니다.
혼란을 드려 죄송합니다. 착오 없으시도록, 문서를 업데이트하도록 하겠습니다.
즐거운 연말 보내시길 바라겠습니다. 새해 복 많이 받으세요!
