### ISSUE TITLE
locationButtonEnable 버튼을 제어할 수 있나요?

### ISSUE THREAD

**Issue by Koobonik** [note11g/flutter_naver_map#14]
![IMG_0DBA3CE51726-1](https://user-images.githubusercontent.com/15663052/165501058-4627e29f-8df9-41d3-bcfc-2fa7906d7dd9.jpeg)

안녕하세요 :) 새롭게 이어가심에 고생이 많으십니다.

해당 왼쪽 하단에 있는 위치 아이콘에 대해 탭 했을때를 제어 하고 싶은데 따로 제어할 수 없는 것 같아서요.
따로 방법이 있나요?

**Comment by note11g** [comment]
안녕하세요!
혹시 Naver Moblie Dynamic Map SDK에서 관련 내용 찾아주실 수 있으실까요?
시간이 요즘 촉박한지라..ㅠㅠ 감히 부탁드려도 될까요..

**Comment by note11g** [comment]
해당 버튼은 제어할 수 없습니다. 다만, 해당 버튼 활성화 옵션(locationButtonEnabled)을 해제(false)하시고 커스텀 버튼을 만들어 사용해주시면 될 것 같습니다.
만약, LocationOverlay(의 위치, 방향 등)를 제어하고 싶으시다면 1.0 버전을 이용해주시면 됩니다.

여전히 문제가 있으시다면, 다시 이슈를 오픈해주시면 됩니다! 감사합니다.
