### ISSUE TITLE
NOverlayImage.fromWidget not loaded on IOS

### ISSUE THREAD

**Issue by anandabayu** [note11g/flutter_naver_map#150]
Hi, I tried to use `NOverlayImage.fromWidget` but it not loaded on the first load, when I opened the page for a second try it loaded successfully

```dart
NMarker marker = NMarker(
  id: "marker",
  position: position,
);
final image = await NOverlayImage.fromWidget(
  widget: DefaultImage(
    path: "icons/ic_spot_location.svg",
    width: 40,
    height: 40,
  ),
  size: const Size(25, 25),
  context: context,
);
marker.setIcon(image);
```

on the first load it only shows pink box:
<img width="319" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/9120244/f93e8ca2-3f1f-4d82-b744-e57921c77239">

on the second load it shows successfully:
<img width="321" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/9120244/c0918d16-6e2a-4e03-8299-fda565b031be">

**Comment by note11g** [comment]
Hi. NOverlayImage.fromWidget is not recommended at Image Widget. It cause inefficient working than using NOverlay another constructor.

Also, in version 1.1.1, change of that issue is scheduled. Please refer to the appropriate commit(djfue2)

**Comment by anandabayu** [comment]
`NOverlayImage.fromAssetImage` is not showing

<img width="310" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/9120244/8fe2c967-e2ec-4726-8c62-673415d8a443">

Here is my code:
```dart
NMarker marker = NMarker(
  id: "marker",
  position: position,
  icon: const NOverlayImage.fromAssetImage("assets/icons/ic_spot_location.svg"),
  size: const Size(10, 10),
);
```

I've also tried using NGroundOverlay not working also:
```dart
final bounds = NLatLngBounds(
  southWest: position,
  northEast: position.offsetByMeter(
    northMeter: 100,
    eastMeter: 200,
  ),
);
var m = NGroundOverlay(
  id: "pin-point",
  bounds: bounds,
  image: const NOverlayImage.fromAssetImage("assets/icons/ic_spot_location.svg"),
  alpha: 1,
);
```

**Comment by note11g** [comment]
@anandabayu svg(vector) is not support.

**Comment by kimwest00** [comment]
안녕하세요:)
혹시 NOverlayImage.fromAssetImage의 확장자로서 .svg를 추가할 계획이 있으신지 궁금합니다!
