### ISSUE TITLE
[Not plugin issue, Flutter Engine] Android PlatformView Display Mode Issues

### ISSUE THREAD

**Issue by note11g** [note11g/flutter_naver_map#152]
## Background

flutter_naver_map 플러그인은 더 나은 성능을 위해, Android 플랫폼에서 TextureView 대신, GLSurfaceView를 사용하여 렌더링합니다.
하지만, 이로 인해 플랫폼 뷰 위젯에 많은 이슈가 발생하고 있습니다. 이를 수집하고 정리하기 위해 해당 이슈를 생성합니다.

The flutter_naver_map plugin uses GLSurfaceView instead of TextureView for rendering on the Android platform, aiming for better performance.
However, many issues have been occurring at PlatformView Widget. This issue has been created to collect and organize them.

**Comment by note11g** [comment]
_본 코멘트는 Flutter 3.16~Flutter 3.18 사이의 코드를 기준으로 서술되었습니다._

Flutter에는 Android PlatformView에서 사용할 수 있는 디스플레이 모드가 3가지 있습니다.
1. [**Hybrid Composition** (이하 HC)](https://github.com/flutter/flutter/wiki/Hybrid-Composition)
2. [**Texture Layer Hybrid Composition** (이하 TLHC)](https://github.com/flutter/flutter/wiki/Texture-Layer-Hybrid-Composition)
3. [**Virtual Display** (이하 VD)](https://github.com/flutter/flutter/wiki/Virtual-Display)

그리고, 실제로 Flutter 엔진이 플러터 위젯들을 그리는 공간인 FlutterView는 두가지 렌더링 뷰를 지원합니다.
1. [**SurfaceView** (Default, 이하 SV)](https://source.android.com/docs/core/graphics/arch-sv-glsv)
2. [**TextureView** (이하 TV)](https://source.android.com/docs/core/graphics/arch-tv)

또한, NaverMap Android SDK 역시 두가지 렌더링 뷰를 지원합니다.

1. [**GLSurfaceView** (이하 GLSV)](https://source.android.com/docs/core/graphics/arch-sv-glsv#glsurfaceview)
2. [**TextureView**](https://source.android.com/docs/core/graphics/arch-tv)

여기에서는 해당 선택지를 어떻게 조합하고 구성하냐에 따라, 어떤 Trade-Off들이 존재하는지와 flutter_naver_map에서는 버전별로 어떻게 구현되어 있는지 서술합니다.

------

## 1. 성능

- FlutterAndroidPlatformView : **`TLHC` > `HC` > `VD`**
- AndroidRenderView : **`SV (or GLSV)` > `TV`**

따라서, flutter_naver_map에서는 MapRendering에 GLSV를 기본으로 사용하되 아래 서술할 호환성에 문제가 있는 기기들에서는 TV를 사용합니다.

## 2. 호환성 (이슈)

### Map: GLSurfaceView
- 백그라운드 모드로 전환되었다가, 다시 돌아오면 Navigator Stack의 Z-Order를 무시합니다.
-

**Comment by johnmccutchan** [comment]
Because of how SurfaceViews render in Android, Flutter will always have trouble supporting them completely and you should avoid using them in a Flutter app.

FWIW: Google Maps on Android uses TextureView (not just in Flutter but in general) and it has great performance.

**Comment by note11g** [comment]
Need to check flutter 3.19's Update (TLHC, Impeller)

**Comment by note11g** [comment]
https://github.com/flutter/flutter/issues/98865 가 flutter 3.19에서 해결된 것으로 보입니다.
1.2.0부터는 TLHC모드를 기본으로 사용합니다. (동시에, min flutter version과 min dart 역시 업그레이드 됩니다)

60c16d578522963109eda67a6ee694cdcfb9b4a1 관련 커밋입니다.

다음은 해결되는 Hybrid Composition 관련 이슈들입니다.
- #68 
- #84

또한, flutter 3.19에서 TLHC와 함께 사용시, GLSurfaceView 문제 역시 해결되었습니다.
따라서, 이제 Android 11~13(API 30~33)에서 FlutterView를 TextureView로 사용하지 않습니다. 나머지는 현행 유지합니다.

80483528d6ba57cecfeff4091fe9a4c8790ed0ef 관련 커밋입니다.

다음은 해결되는 GLSurfaceView 관련 이슈들입니다.
- #56 
- #160

**Comment by note11g** [comment]
해당 이슈에 관련된 이슈는 대부분 수정되었습니다.
곧 1.2.0 버전이 업그레이드 되고 나면, 해당 이슈는 닫힙니다.
감사합니다.
