### ISSUE TITLE
marker 정보창 표시 불가 오류

### ISSUE THREAD

**Issue by oxyhydro26** [note11g/flutter_naver_map#154]
```
          onMapTapped: (NPoint point, NLatLng latLng) async {
            print(point);
            print(latLng);

            final NMarker marker1 = NMarker(
                id: '1',
                position: latLng
                );

            await _mapController.addOverlay(marker1);

            final NInfoWindow infoWindow = NInfoWindow.onMarker(id: '1', text: 'fff');

            await marker1.openInfoWindow(infoWindow);
          },
```
이때 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, lateinit property commonProperties has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property commonProperties has not been initialized 오류 발생.

flutter 3.16.~ 가 문제일까요

**Comment by oxyhydro26** [comment]
icon 유무와 상관없는 오류

**Comment by note11g** [comment]
안녕하세요. 이슈 제보에 감사드립니다.
해당 이슈는 빠르게 조치하여, `1.1.1`버전에서 곧 제공될 예정입니다.
감사합니다. 좋은 밤 되세요:)

**Comment by oxyhydro26** [comment]
휴일에도 수고하십니다. 다른 이슈들 있으면 또 제보드리겠습니다.

2024년 1월 6일 (토) 오후 10:23, 김노트 ***@***.***>님이 작성:
