### ISSUE TITLE
flutter_native_splash 패키지의 FlutterNativeSplash.preserve 사용시 오류

### ISSUE THREAD

**Issue by YongWoo-8933** [note11g/flutter_naver_map#160]
flutter_native_splash 를 사용해 splash화면을 띄우고
초기 설정이 끝나면 FlutterNativeSplash.remove()를 통해
앱을 시작하도록 했는데, 이번 1.1.1버전 버전업 이후
splash화면이 검은색만 뜹니다.

정확히는 처음에는 splash가 잘 실행되지만, 
FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding) 와
FlutterNativeSplash.remove() 사이 시간에
아무것도 뜨질 않습니다.

안드로이드 11, 12이후 버전, ios에서 같은 증상을 확인했고
네이버 지도를 넣지 않은 테스트 프로젝트에서는
해당 증상이 발생하지 않는 걸 보아 
flutter_naver_map와 flutter_native_splash간
어떤 충돌로 짐작해 이슈를 남깁니다.

한번 확인 부탁드립니다 :)

**Comment by note11g** [comment]
@YongWoo-8933 안녕하세요.
혹시 이전에 사용하시던 버전 정보를 알 수 있을까요?
그리고, 빠른 대응을 위해서 가능하시다면 note11@kakao.com으로 연락 부탁드리겠습니다. 감사합니다.

**Comment by YongWoo-8933** [comment]
적어주신 메일로 이메일 따로 드렸습니다. 
혹시 몰라 여기에도 적어보자면, 이전에 1.0.2 사용중이었습니다.

**Comment by note11g** [comment]
Android는 해당 현상 재현에 성공하였습니다. (Android 11~13)
iOS는 해당 증상 확인에 실패했습니다. 번거로우시겠지만, 재현 환경을 말씀해주실 수 있으실까요?

재현에 사용한 코드는 다음과 같습니다.
```dart
void main() async {
  final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  await Future.delayed(const Duration(seconds: 3));
  await NaverMapSdk.instance.initialize(clientId: '2vkiu8dsqb');
  FlutterNativeSplash.remove();
  runApp(const MyApp());
}
```

**Comment by YongWoo-8933** [comment]
제 설정이 잘못됐었네요. ios에서는 제대로 작동합니다. 안드로이드 11~13 이슈만 확인해 주시면 될 것 같습니다.

**Comment by note11g** [comment]
#56의 수정으로 발생하고 있는 이슈입니다.

기본 플러터 렌더뷰를 TextureView로 변경하는 수정이 있었습니다만,
트레이드오프를 다시 고려해 조만간 업데이트하도록 하겠습니다.
그때까지는, 해당 이슈가 발생할 수 있습니다.
