### ISSUE TITLE
[문의] 패키지내에서 Navermap sdk 3.16.2 > 3.17.0 으로 변경후 앱 용량 증가

### ISSUE THREAD

**Issue by woogi-kang** [note11g/flutter_naver_map#162]
안녕하세요 플러그인 유지하시느라 고생하십니다.

다름이 아니라 이번에 1.0.1 버전에서 1.1.1 버전으로 마이그레이션 진행을했더니 

apk/appbundle/ipa 용량이 약 2배정도로 늘어나는 현상을 발견했습니다. (apk 경우 약 110MB 상승)
아무래도 네이버 맵 sdk 버전이 올라가면서 그런거같은데 네이버맵 Release Note 에서는 별 내용이없어 혹시 이 사항에 대해서 알고계시는지 궁금합니다.

**Comment by note11g** [comment]
안녕하세요. 
혹시 빌드캐시나 pod repo를 초기화해도 해당 현상이 그대로 발생하는지 여쭤볼 수 있을까요?

**Comment by woogi-kang** [comment]
@note11g 

네네 안드로이드/ iOS 둘다 캐시지우고 빌드해봤는데 재현되고있습니다

**Comment by note11g** [comment]
![image](https://github.com/note11g/flutter_naver_map/assets/67783062/3a72cb84-3667-43de-bc9b-2ebe96f77035)
Android: 
1.0.2: apk **125.5mb**, download size **43.8mb**
1.1.1: apk **126.1mb**, download size **44mb**
![image](https://github.com/note11g/flutter_naver_map/assets/67783062/d677e77b-6661-471a-a60c-58e0ed8c1336)
iOS: _(실제 다운로드 용량은 앱스토어 커넥트에 올려야 정확히 파악할 수 있어 측정하지 않았습니다)_
1.0.2: .app 73.3mb, map size 46.6mb 
1.1.1: .app 74.5mb, map size 47.7mb

분석 결과에서는 유의미한 차이를 보이지 않는 것으로 보입니다.
계속해서 문제가 생기신다면, pub clean 등의 작업을 수행해보시고, 여전히 같은 증상이 발생하신다면 코멘트 남겨주시길 바라겠습니다.
감사합니다.

**Comment by note11g** [comment]
https://developer.android.com/reference/tools/gradle-api/7.1/com/android/build/api/dsl/JniLibsPackagingOptions#uselegacypackaging

해당 옵션을 android build.gradle에서 활성화해주시면, 서빙되는 apk 용량(다운로드 사이즈 x)이 줄어듭니다.
