### ISSUE TITLE
2가지 문의 드립니다.

### ISSUE THREAD

**Issue by ItdaTeam** [note11g/flutter_naver_map#164]
1. flutter web 버전 지원 계획이 있는지 궁금합니다. 
 - naver map flutter version 나오면 웹/앱 버전 으로 아주 유용하게 정리 될듯 합니다.

2. 마커 클러스터링은 계속 이야기가 있었고 개발 로드맵?에 반영은 하신다고 했던것 같은데
- 계획이 있다면 언제쯤 되는것인지 궁금 합니다.

**Comment by note11g** [comment]
1. 웹 버전 지원 계획은 현재로써는 없습니다. 
이유는 몇가지 있는데요, 첫번째는 Flutter Web의 안정성입니다. 아직 많이 불안정하며, 이 문제로 인해 전체 유지 보수가 힘들어질 것으로 판단하고 있습니다. 두번째는 플랫폼별 특성때문입니다. Web은 Android나 iOS와 비교했을 때, UX나 API Spec 등 여러부분에서 차이가 발생하며, 이는 통일된 API와 사용경험을 제공해드리기 힘든 부분이 존재합니다. 세번째는 Flutter Web의 활용성입니다. Flutter Web은 현재 기존 PC웹이 아닌, PWA를 더욱 잘 개발할 수 있도록 하는 방향으로 개발되고 있는 것으로 알고 있습니다. 이는 Web Dynamic Map SDK의 일부 기능을 제공해드리지 못하거나, Flutter Web과 다른 방향성으로 구현될 수 있음을 의미합니다. 이외에도, 아직 사용처가 많지 않은 부분도 있어, 해당 부분은 현재로써는 계획이 없습니다. 양해바랍니다.

2. 마커 클러스터링은 시간에 여유가 없어 계속해서 작업이 늦어지고 있습니다. 성능상의 이슈로 여러가지 테스트를 진행하다, 지금은 잠시 중단된 상태입니다. 추후 컨셉코드와 오픈소스 기여 가이드를 추가하는 등의 작업을 통해 커뮤니티의 참여를 유도할 수도 있을 것 같습니다. 하지만 지금으로써는 정확한 일정을 말씀드리기는 어려운 점 양해 부탁드리겠습니다. 

감사합니다. 좋은 밤 되시길 바라겠습니다.
