### ISSUE TITLE
여러 개의 NOverlayImage를 사용할 경우, 해당 이미지가 포함된 일부 오버레이가 특정 줌 레벨에서 보이지 않는 현상

### ISSUE THREAD

**Issue by spencer0124** [note11g/flutter_naver_map#165]
```
import 'package:flutter_naver_map/flutter_naver_map.dart';

class CampusMarker {
  final String id;
  final NLatLng position;
  String get imagepath => 'assets/images/$id.png';

  CampusMarker({
    required this.id,
    required this.position,
  });
}
```

```
final List<CampusMarker> hsscCampusMarker = [
    CampusMarker(id: 'line1', position: const NLatLng(37.587361, 126.994479)),
    CampusMarker(id: 'line2', position: const NLatLng(37.587441, 126.990506)),
    CampusMarker(id: 'line4', position: const NLatLng(37.588636, 126.993209)),
    CampusMarker(id: 'line7', position: const NLatLng(37.588353, 126.994262)),
    CampusMarker(id: 'line8', position: const NLatLng(37.58752, 126.99322)),
    CampusMarker(id: 'line9', position: const NLatLng(37.586819, 126.995246)),
    CampusMarker(id: 'line31', position: const NLatLng(37.589184, 126.991539)),
    CampusMarker(id: 'line32', position: const NLatLng(37.589053, 126.992435)),
    CampusMarker(id: 'line33', position: const NLatLng(37.588572, 126.992666)),
    CampusMarker(id: 'line61', position: const NLatLng(37.587882, 126.991079)),
    CampusMarker(id: 'line62', position: const NLatLng(37.588160, 126.990868)),
  ];
```

```
...controller.hsscCampusMarker.map(
            (campusMarker) => NMarker(
              id: campusMarker.id,
              position: campusMarker.position,
              size: const Size(25, 25),
              icon: NOverlayImage.fromAssetImage(campusMarker.imagepath),
            )
              ..setZIndex(10)
              ..setGlobalZIndex(10),
          ),
```

마커를 조금 더 효율적으로 표시하기 위해서 hsscCampusMarker에 필요한 정보를 다 써두고, 해당 정보를 반복적으로 불러와서 마커를 표시하려고 했습니다.

그런데 icon이 const가 아닌 경우 (코드처럼 다 다른 경우) 마커가 hsscCampusMarker의 상단에 있는 3개 ~ 4개만 보이고 나머지는 대부분 누락됩니다.

해당 코드에서 icon을 const로 변경하는 경우( 다 동일한 아이콘을 주는 경우) 의도한대로 동작합니다.
* asset의 문제는 아닙니다.
* IOS & Android 둘다 동일합니다.

**Comment by note11g** [comment]
안녕하세요. 제보에 감사드립니다.

혹시 pubspec에 asset 경로를 어떻게 설정해두셨는지 여쭤볼 수 있을까요?

**Comment by spencer0124** [comment]
```
flutter:
  assets:
    - ".env"
    - assets/
    - assets/applogo/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/SKKU/
```

이렇게 설정해두었고, 마커에 필요한 이미지 파일은
assets/images 폴더 안에 line(숫자).png 형식으로 저장해두었습니다.

<img width="766" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/62795814/7e70e779-3a95-4e8f-a9b2-cce7d667addb">

**Comment by note11g** [comment]
혹시 이미지들의 크기를 알 수 있을까요?
비트맵의 크기가 너무 크면 이런 현상이 발생할 수도 있을 것 같습니다.
맵에 100m 간격으로 모두 다른 아이콘(평균 을 사용하여 테스트해 보았을 때,

zoomLevel이 14까지는 정상적으로 표출되었으나, 줌 레벨을 더 줄였을 때에는 메모리에 적재되는 양을 조절하느라 일부 마커가 보이지 않는 현상이 발생하였습니다. 다만, 이때 오버레이 터치 이벤트는 정상적으로 수신되는 것으로 보아, 이미지만 뜨지 않는 현상으로 판단할 수 있을 것 같습니다.

(사용한 예시 아이콘-1774, 아이콘들은 0\~9999번까지 생성하여 테스트하였으며 용량은 7~9kb입니다.)
![00076eab65ac3667f6eab3a83d25e8b1e694b129b691322a37d20fc283e9772f](https://github.com/note11g/flutter_naver_map/assets/67783062/01a3c26a-e637-4d26-99ec-64c8d074a7b2)

<img width="250" src="https://github.com/note11g/flutter_naver_map/assets/67783062/0c56c2ac-5c01-4606-bed1-1e26f4b36fd9"/>
<img width="250" src="https://github.com/note11g/flutter_naver_map/assets/67783062/e4f573ab-2b38-4751-abcc-a844f33a8335"/>

정확한 답변을 위해, SDK 팀에 공식 답변을 요청하도록 하겠습니다.
일단은 파일 크기에 의해 숨겨지는 것으로 추정됩니다.

그리고 마커에 정보를 나타내야 한다면, 많은 이미지를 사용하는 것보다는 caption 혹은 subCaption 등을 활용하시는 방법을 권장드립니다. 감사합니다.

**Comment by note11g** [comment]
marker.setCaption처럼 설정하실 수 있습니다.

**Comment by spencer0124** [comment]
감사합니다
![image](https://github.com/note11g/flutter_naver_map/assets/62795814/51b14546-0c70-4a86-a3ac-7abcaefd7b21)
다만 현재 제가 구현하고자 하는 부분은 사진처럼 건물 사이 간격이 50m 내외인 경우라서
텍스트를 넣기보다는 마커별로 다른 숫자를 표현해줘야 하는 기능이 절실한데..
네이버 답변이 오기 전에 시도해볼 수 있는 방법 중

(1) 마커 바로 위에 숫자를 오버레이하거나
(2) 마커 이미지 자체를 Container와 같은 위젯으로 만드는 것

둘중에 가능한게 있을까요?

**Comment by note11g** [comment]
증상에 알맞게 제목을 변경합니다.

**Comment by note11g** [comment]
> * 1번 방법은 captionAligns와 captionOffset을 활용할 수 있습니다.

다음은 예시입니다.

```dart
final pathMarker = NMarker(
        id: "path_mark_$pathPointId",
        position: latLng,
        caption: NOverlayCaption(text: "$pathPointId", textSize: 14),
        captionOffset: -16,
        captionAligns: [NAlign.top]);

    mapController.addOverlay(pathMarker);
```

![image](https://github.com/note11g/flutter_naver_map/assets/67783062/68f82efa-664d-4e62-a193-5683dd6de91e)

**Comment by spencer0124** [comment]
![image](https://github.com/note11g/flutter_naver_map/assets/62795814/2dfa281a-9bbf-42ef-aee5-6871d34bcf8d)
말씀해주신 방법으로 원하는 형태로 구현 성공했습니다!
감사드립니다

증상 재현을 위해서는
1. 마커의 이미지를 각각 모두 다르게 설정
2. 마커의 간격들을 50-100m 이내로 밀집되게 설정
두가지가 핵심 요인인 것으로 추정합니다.

제가 사용했었던 NLatLng으로 테스트해보시면 쉬울 것 같습니다


List<CampusMarker> hsscMarkers = [
  CampusMarker(
    idNumber: "1",
    position: const NLatLng(37.587361, 126.994479),
  ),
  CampusMarker(
    idNumber: "2",
    position: const NLatLng(37.587441, 126.990506),
  ),
  CampusMarker(
    idNumber: "4",
    position: const NLatLng(37.588636, 126.993209),
  ),
  CampusMarker(
    idNumber: "7",
    position: const NLatLng(37.588353, 126.994262),
  ),
  CampusMarker(
    idNumber: "8",
    position: const NLatLng(37.58752, 126.99322),
  ),
  CampusMarker(
    idNumber: "9",
    position: const NLatLng(37.586819, 126.995246),
  ),
  CampusMarker(
    idNumber: "31",
    position: const NLatLng(37.589184, 126.991539),
  ),
  CampusMarker(
    idNumber: "32",
    position: const NLatLng(37.589053, 126.992435),
  ),
  CampusMarker(
    idNumber: "33",
    position: const NLatLng(37.588572, 126.992666),
  ),
  CampusMarker(
    idNumber: "61",
    position: const NLatLng(37.587882, 126.991079),
  ),
  CampusMarker(
    idNumber: "62",
    position: const NLatLng(37.588160, 126.990868),
  ),
];

**Comment by note11g** [comment]
둘 다 잘 보이는 것 같습니다. 지금은 11개의 서로 다른 마커를 사용하였는데요, 사용된 이미지를 업로드합니다(마지막 마커는 사용하지 않았습니다만, 일단 올립니다.)

대부분의 경우 1000개 이하의 이미지 종류면 문제가 없는 것으로 보입니다.

일단은 재현이 불가능하므로, 이슈를 닫겠습니다. 
다시 문제가 발생하신다면, 이슈를 열어주시고 재현 조건을 상세히 기재해주시길 부탁드리겠습니다.

<img height="720" src="https://github.com/note11g/flutter_naver_map/assets/67783062/e6ef8cc5-7a41-435a-a0ca-9c7b7fa6b72d">
<img height="720" src="https://github.com/note11g/flutter_naver_map/assets/67783062/dbfdf3fc-8ec6-49fa-a4b5-0f2f527b8d59">

---

<img width="48" alt="bank" src="https://github.com/note11g/flutter_naver_map/assets/67783062/b0b93da2-e6cb-4c42-8591-e3e65b62fd97">
<img width="48" alt="bar" src="https://github.com/note11g/flutter_naver_map/assets/67783062/0989db90-2795-4b83-b1d5-1e23828e1339">
<img width="48" alt="bus" src="https://github.com/note11g/flutter_naver_map/assets/67783062/e565a20d-a6b0-4523-8d11-0da490fa8d23">
<img width="48" alt="cafe" src="https://github.com/note11g/flutter_naver_map/assets/67783062/d9833262-aa43-4728-a128-4bd4e23eefeb">
<img width="48" alt="corporate" src="https://github.com/note11g/flutter_naver_map/assets/67783062/797c1985-e921-4962-9d5a-6f499acbd4c3">
<img width="48" alt="dining" src="https://github.com/note11g/flutter_naver_map/assets/67783062/cd404778-9588-4bca-8c82-a6453230ff8b">
<img width="48" alt="esport" src="https://github.com/note11g/flutter_naver_map/assets/67783062/e4df3b62-5e9b-4240-bdec-5abafbc37af7">
<img width="48" alt="fastfood" src="https://github.com/note11g/flutter_naver_map/assets/67783062/6151973a-f2e1-4c65-9e79-d27041618769">
<img width="48" alt="restaurant" src="https://github.com/note11g/flutter_naver_map/assets/67783062/0c66cd2f-5ae8-44cf-8423-e22c1234f3f3">
<img width="48" alt="sport" src="https://github.com/note11g/flutter_naver_map/assets/67783062/9dfcbf5a-e9b2-4c70-a744-54ff7b3cad8f">
<img width="48" alt="store" src="https://github.com/note11g/flutter_naver_map/assets/67783062/223dc9ec-be86-4f19-8e30-313e919fcf3e">
<img width="48" alt="subway" src="https://github.com/note11g/flutter_naver_map/assets/67783062/e9eae1fb-2534-4057-a906-064fb0bdcde4">
