### ISSUE TITLE
marker isAdded, isVisible 이 true 인경우 set 함수들의 No implementation found 에러 발생

### ISSUE THREAD

**Issue by battlecook** [note11g/flutter_naver_map#172]
marker 의 isAdded, isVisible 이 모두 true인 경우에 

setZIndex, setIconTintColor, setCaption 함수등을 호출했을때 MissingPluginException 예외가 나는경우가 간헐적으로 발생중인데 어떤경우인지 알 수 있을까요?

flutter: MissingPluginException(No implementation found for method ma"44758"caption on channel flutter_naver_map_overlay#3)

재현경로 확인중에 있습니다

**Comment by note11g** [comment]
안녕하세요, 이슈를 제보주셔서 감사드립니다.
혹시, 해당 마커가 맵에 attach된 상태인지 확인 부탁드려도 괜찮을까요?

**Comment by note11g** [comment]
현재 해당 현상 발생하는 플랫폼 정보도 부탁드리겠습니다:)

**Comment by note11g** [comment]
오랫동안 답변이 달리지 않아 이슈를 닫도록 하겠습니다.
여전히 이슈라고 판단하신다면, 이슈를 다시 열어주세요.
감사합니다.
