### ISSUE TITLE
IOS 시뮬레이터 현재 위치로 카메라 이동 안 되는 이슈 + Bearing 지원 여부 질문

### ISSUE THREAD

**Issue by Dale-Sprint** [note11g/flutter_naver_map#174]
안녕하세요 !
Flutter로 개발을 시작한지 얼마되지 않아서 잘 몰라서 하는 질문일 수도 있어서 많이 조심스럽습니다 ㅠㅠ 최대한 상세하게 질문해보겠습니다 !

저는 현재 실시간으로 사용자들의 위치를 지도에 보여주는 앱을 만들고 있습니다.
아직 여러명을 지도에 띄우는 것을 구현하지 못하고, 우선 제 자신만 지도에 띄우는 것을 목표로 어제 개발에 성공을 했습니다.
그런데 개발을 하면서 겪었던 이슈를 공유하고 질문합니다.

1. 위치(Location) 모양 아이콘을 누르면 현재 위치로 이동하는 기능을 구현했습니다.

`Future<void> _setCustomMarkerIcon(
      BuildContext context, Position position) async {
    final iconImage =
        await NOverlayImage.fromAssetImage('asset/images/logo/logo.png');

    final locationOverlay = await mapController!.getLocationOverlay();
    locationOverlay.setIcon(iconImage);
    locationOverlay.setIconSize(const Size.fromRadius(50));
    locationOverlay.setCircleRadius(50.0);
    locationOverlay.setCircleColor(Colors.yellow.withOpacity(0.3));
    locationOverlay.setPosition(NLatLng(position.latitude, position.longitude));
    locationOverlay.setIsVisible(true);
    locationOverlay.setBearing(locationOverlay.getBearing() as double);

    // 카메라 포지션 객체 생성
    NCameraPosition nCameraPosition = NCameraPosition(
      target: NLatLng(position.latitude, position.longitude),
      zoom: 17,
    );

    // 카메라 업데이트 객체 생성 및 애니메이션 설정
    NCameraUpdate.fromCameraPosition(nCameraPosition).setAnimation(
      animation: NCameraAnimation.linear,
      duration: const Duration(seconds: 2),
    );

    print("좌표 이동: $latitude, $longitude");
  }`

이때 버튼을 눌렀을 때 에뮬레이터와 안드로이드 실기기에서는 정상적으로 작동하는 것을 확인했는데, 시뮬레이터에서는 작동이 될 때도있고 안 될 때도 있는데 안 되는 경우가 훨씬 많았습니다.

이게 시뮬레이터 문제라면 이슈로 전달드리는게 죄송스럽지만... 혹시 이 제보가 도움이 될까 해서 이슈로 남깁니다 !

=================================================

두번째는 질문입니다.
Naver Map에서 locationButtonEnable: true로 옵션을 설정하면, 현재 위치로 이동도 되고 방향을 표시해주는 것을 확인했습니다.

저는 제 앱에서 개인적으로 현재위치에 카메라를 이동시키는 버튼을 만들었기 때문에 네이버에서 제공해주는 옵션을 사용하지 않으려고 합니다.

그래서 만약 가능하다면 네이버에서 제공해주는 현재 방향 표시 기능을 제가 만든 버튼에 적용해주고 싶은데 가능한지 궁금합니다 !
===================================================
마지막 질문입니다.

제가 모든 사용자의 위치를 실시간(5초당 한번씩 서버에 회원들의 위치를 조회)해서 지도상에 유저의 위치를 보여주려고 합니다.

기존에 마커로 구현을 해보려고 했는데, 5초마다 변경된 위치를 보여주려면, 보여주고 또 삭제하고 또 보여주는 과정의 반복이 될 것 같더라구요..!

그래서 위치 [오버레이](https://note11.dev/flutter_naver_map/element/overlay)를 사용하여 구현하려고 합니다.
(현재 제 자신의 위치를 실시간으로 보여지는 것은 구현한 상태입니다.)
그런데 메서드를 확인해보니 모든 유저들의 위치값들을 넣을 리스트 파라미터를 받는 메서드가 보이지 않더라구요..!

혹시 위치 오버레이는 단 한 명의 사용자만 지도상에 표현이 가능한가요...?

만약 그렇다면, 5초마다 서버에 요청했을 때 모든 유저를 지도상에 표시해주려면 어떤 오버레이를 사용해야 하는지 궁금합니다..!

추후에, 지도에 사용자의 이미지가 보일 때, 터치를 하면 상태 모달창이 뜨고, 거기에 친구추가 등의 기능을 할 수 있도록 하려고 하는데, 오버레이는 불가능 하고 마커만 가능한 것 같아요..! 그러면 어쩔 수 없이 마커를 사용해야하는건지.. ㅠㅠ

어떤 선택을 해야하는지 확신이 들지 않습니다 ㅠㅠ

======================================================

어제 오픈채팅방에서 처음으로 뵙고 너무 영광이었습니다 !
설명이 부족할 수도 있는데, 코멘트 주시면 최선을 다해서 설명드리겠습니다 !
감사합니다 ㅎㅎ

**Comment by note11g** [comment]
안녕하세요, 반갑습니다.
1번 질문은 사실 잘 이해를 하지 못해, 1번을 제외하고 답변드리도록 하겠습니다.
1번 질문에서 정확히 어떤 요구사항을 구현하려고 하시는지, 추가 코멘트에 명확하게 설명 부탁드릴게요!

---
2-a. 위치 오버레이의 방향 표시 기능은 setSubIcon을 통해 방향각 표시를 해주시고, setBearing을 지정하여 방향을 컨트롤하실 수 있습니다.
이때, https://pub.dev/packages/flutter_compass 와 같은 플러그인을 사용하시어 지자기 센서를 활용하시면 됩니다.

2-b. 위치 오버레이는 따로 생성하실 수 없으며, 지도당 하나씩만 존재합니다. 따라서, 다른 사용자를 표시할 때는 마커를 사용하시면 됩니다.

2-c. 모달창보다는, 바텀시트(https://api.flutter.dev/flutter/material/showModalBottomSheet.html) 등을 활용하시는 것을 추천드립니다.

감사합니다.

**Comment by Dale-Sprint** [comment]
안녕하세요 ! 답변 감사드립니다 ㅎㅎ
제 설명이 미흡했나봅니다 ㅠㅠ 조금 더 자세하게 설명드리겠습니다 !
1. 현재 위치로 카메라 이동하는 버튼을 구현

<img width="385" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/153828241/6798856d-792d-4fe4-b90e-875108836a93">

naver map에서 기본적으로 제공해주는 현재 위치를 보여주는 기능을 직접 버튼을 만들어 구현하였습니다 !
이 버튼을 실행해볼 때 안드로이드 에뮬레이터와 실기기에서는 기대한 것처럼 정상적으로 작동을 하지만, ios 시뮬레이터에서는 정상적으로 작동하지 않습니다.

사용중인 시뮬레이터는 ios 15 pro max입니다.

첫번째 질문에서 첨부했던 코드는, 제가 버튼을 구현할 때 사용한 코드입니다.
이렇게 구현하니까 현재 위치로 포커싱해주더라구요 !

`final locationOverlay = await mapController!.getLocationOverlay();
locationOverlay.setIcon(iconImage);
locationOverlay.setIconSize(const Size.fromRadius(50));
locationOverlay.setCircleRadius(50.0);
locationOverlay.setCircleColor(Colors.yellow.withOpacity(0.3));
locationOverlay.setPosition(NLatLng(position.latitude, position.longitude));
locationOverlay.setIsVisible(true);
locationOverlay.setBearing(locationOverlay.getBearing() as double);

// 카메라 포지션 객체 생성
NCameraPosition nCameraPosition = NCameraPosition(
  target: NLatLng(position.latitude, position.longitude),
  zoom: 17,
);

// 카메라 업데이트 객체 생성 및 애니메이션 설정
NCameraUpdate.fromCameraPosition(nCameraPosition).setAnimation(
  animation: NCameraAnimation.linear,
  duration: const Duration(seconds: 2),
);

print("좌표 이동: $latitude, $longitude");`

혹시 이게 시뮬레이터 자체의 문제라면 업데이트를 기다리는게 최선이겠지만, 혹시 이 이슈 제보를 통해 개션될 수 있을까해서 남겨봅니다 ! ㅎㅎ
조금 더 구체적으로 설명드린다고 했는데, 내용 전달이 잘 됐을지 모르겠습니다 ㅠㅠ
===================================================
2-a: setSubIcon에 방향각에 대한 이미지를 찾아서 bearing에 따라 보여주면 되군요 ..!
좋은 아이디어 감사드립니다 !

2-b:
제 자신의 실시간 위치를 보일 때는 위치 오버레이를 사용하고, 다른 유저들을 보여줄 때는 마커를 사용하는 아이디어 공유 감사합니다 !!

매번 요청할 때마다 사용자의 위치가 바뀌기 때문에, 매번 전체 마커를 생성하고, 지우는 과정을 거쳐야할 것 같은데, 보통 이렇게 처리를 하나요..?
기기가 이 정도는 버텨낼지... 솔직히 좋은 코딩 방식이 아니라고 생각이 들지만, 더 나은 구현 방식이 잘 떠오르지 않네요 ㅠㅠ

2-c: 마커를 클릭할 때 모달창 보다는 바텀시트를 사용하도록 해보겠습니다 ! 생각지도 못했던 좋은 정보 공유해주셔서 감사합니다 !

=====================================================
제가 목표로 구현하려고 하는 것은,
만약 저와 김노트님이 제가 구현한 앱을 사용하고 있을 때 광화문에서 뵙기로 했다면

제가 광화문 위치를 선택했을 때 김노트님께 함께 만나기를 요청합니다.
김노트님께서 요청에 대해 승인하신다면, 저희 둘만 보이는 경로가 나타나는데, 각자 위치에서 광화문까지 얼마나 걸리는지 naver 길찾기가 서로에게 공유가 되는 시스템을 개발하려고 합니다. 실시간으로 각자가 그 장소에 도착하는데 얼마나 걸리는지 만나기로 한 사람들끼리 알게되는 것을 앱의 목표로 하고 있습니다 !

만약 지도에 오버레이를 하나만 사용할 수 있다면, 지금 사용하고 있는 위치 오버레이를 포기하고 경로 오버레이만 사용해야 하는건지 헷갈립니다 ㅠㅠ

========================================================

멋진 개발자님과 이렇게 기술적인 대화를 나누는 것은 제게 큰 영광입니다.
답변 감사드립니다 !

**Comment by note11g** [comment]
@Dale-Sprint 
1-a. 말씀 주신 코드에서는 NCameraUpdate 객체만 생성하시고, 따로 컨트롤러를 통해 이동은 하지 않으신 것으로 보입니다.
이렇게 하면, 카메라는 움직이지 않습니다.
다음과 같이 코드를 수정해보세요.

```dart
Future<void> locationUpdate({ required NLatLng currentCoord }) async {
    final locationOverlay = await mapController?.getLocationOverlay();
    locationOverlay
      ?..setIcon(iconImage)
      ..setIconSize(const Size.fromRadius(50))
      ..setCircleRadius(50.0)
      ..setCircleColor(Colors.yellow.withOpacity(0.3))
      ..setPosition(currentCoord)
      ..setIsVisible(true);

    final cameraUpdate = NCameraUpdate.withParams(target: currentCoord);
      ..setAnimation(animation: NCameraAnimation.linear, duration: const Duration(seconds: 2)); // 2초는 너무 길 수도 있어요.
    await mapController?.updateCamera(cameraUpdate);
}
```

1-b. 방향각 이미지는 추후 API로 제공할 수 있도록 해보겠습니다. 현재로써는 직접 가져오셔야 합니다.
2-b: marker 객체를 보관하고 계시면 됩니다. marker.setPosition 메서드를 통해 위치의 조작이 가능합니다.
답변은 여기까지입니다. 도움되셨다면, 스타를 부탁드려도 될까요?
추가 질문이 있으시다면 이슈를 다시 열고, 코멘트를 남겨주세요.
좋은 저녁 되시길 바라겠습니다, 감사합니다.
