### ISSUE TITLE
[질문] Naver Map 다중 마커 지원 여부 

### ISSUE THREAD

**Issue by Dale-Sprint** [note11g/flutter_naver_map#177]
안녕하세요 !
회원가입 된 유저의 위치를 마커로 보여주는 것을 구현하려고 합니다 !

# 첫번째 질문

마커를 만들어서 지도에 보여주는 것은 성공했는데, 100명의 유저가 있다고 가정했을 때, 코드상에 100개의 마커를 만드는 것은 뭔가 잘못된 코드 방식이라고 느껴지더라구요..!

그래서 찾아보니 보통 다중 마커 기능을 지원하는것으로 보여지는데, 김노트님 문서에서는 다중 마커에 대한 내용을 확인할 수 없었습니다 ㅠㅠ

만약에 단일 마커를 사용해야한다면,
특정 지역에 확대했을 때 마커를 보여주기 위해 생성했다가,
다시 축소할 때 마커를 삭제하는 과정을 반복해야하는건지 궁금합니다 !

# 두번째 질문
현재 사용자의 이미지를 서버로부터 presignedUrl을 받고, 사진을 앱 내에 저장 후 경로를 조회해서 보여주고 있습니다.
만약에 1000명의 유저가 있다면 1000명의 유저의 이미지를 모두 다운로드 해야하는 상황이 발생하게 되는데, 회원가입 된 유저의 수가 늘어날수록 앱의 저장공간에 대한 무리가 있을 것 같습니다.

혹시 앱 내에 저장하지 않고 PreSigendUrl을 바로 사용해서 이미지를 보여줄 수 있는 방법이 있는지
혹은 보통 이럴 경우에 어떻게 대처하는지 조언을 구하고 싶습니다 ..!

**Comment by note11g** [comment]
안녕하세요, 라이브러리를 사용해주셔서 감사드립니다.
관련 문의사항에 대해 답변드리겠습니다.

1. 맞습니다. 말씀해주신 것처럼 카메라의 변경이 있고 난 후(`onCameraIdle`), 지도에 올라갈 오버레이들을 적절히 갱신해주시면 됩니다.
2. 현재, `fromByteArray`, `fromWidget`에 대해서는 해싱과 캐시 스토리지를 이용한 캐싱이 이루어지고 있습니다. 이는 매번 비트맵 인스턴스를 생성하는 것을 방지하여 메모리 사용을 효과적으로 관리하고자 사용하고 있습니다만, 개발자에게 좀 더 유연한 API를 제공하고자, 해싱과 스토리지 저장 옵션을 사용하지 않고, key(id)로 직접 관리할 수 있는 API를 추가하는 것을 검토해보도록 하겠습니다.  지금 바로 사용하실 수 있는 방법은 `NOverlayImage.fromFile` 생성자입니다. 파일 저장과 삭제 정책을 직접 구현하시어, 저장공간을 최대한으로 활용할 수 있는 형태를 만드시면 됩니다.

감사합니다.
