### ISSUE TITLE
파이어베이스 이미지를 NOverlayImage.fromWidget 마커로 띄우는 방법이 뭘까요?

### ISSUE THREAD

**Issue by baekjungkim** [note11g/flutter_naver_map#178]
Image.network, Image.memory 등을 커스텀 위젯 마커로 만들어서 띄우려고 합니다.

그런데 마커의 모양은 나타나고 이미지는 나오지 않습니다.. 

```
final request = await http.get(Uri.parse(imageUrl));
final imageMemory = request.bodyBytes;
final imagePath = await ImageUtil.saveImage(imageMemory);

await NOverlayImage.fromWidget(
    widget: CustomMarker(imagePath),
    size: const Size(100, 100),
    context: context
);
```

<img width="117" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/44705388/690ec335-aa62-4614-9bd0-7a1314e66d23">

**Comment by note11g** [comment]
안녕하세요, 다음과 같이 사용하시면 됩니다.
```dart
final overlayImage = await NOverlayImage.fromByteArray(request.bodyBytes);
```

더 궁금하신 사항이 있으시다면, 코멘트 남겨주세요.
감사합니다, 좋은 저녁 보내세요!

**Comment by baekjungkim** [comment]
> 안녕하세요, 다음과 같이 사용하시면 됩니다.
> 
> ```dart
> final overlayImage = await NOverlayImage.fromByteArray(request.bodyBytes);
> ```
> 
> 더 궁금하신 사항이 있으시다면, 코멘트 남겨주세요. 감사합니다, 좋은 저녁 보내세요!

fromByteArray 함수로 이미지를 만드는 것은 가이드를 통해 확인헀습니다.

제가 여쭙고 싶은 것은 custom marker 위젯에 사진을 넣어서 맵상에 마커로 띄우고 싶습니다.

**Comment by note11g** [comment]
같은 방법으로 하시면 됩니다.
marker.setIcon 메서드를 활용해주세요.

**Comment by baekjungkim** [comment]
> 같은 방법으로 하시면 됩니다. marker.setIcon 메서드를 활용해주세요.

진짜 죄송한데 예제 하나만 알려주시면 안될까요?

fromByteArray 와 fromWidget 을 같이 사용하는방법을 잘 모르겠습니다..

**Comment by note11g** [comment]
아, 혹시 위젯+이미지를 마커 아이콘으로 만들어 사용하시려고 하시는걸까요?
그런 경우에는 Image.memory(bytes) 위젯을 사용하시면 됩니다. 다만, 위젯 그리는 비용이 비싸기 때문에, 권장드리지는 않습니다.
단, Image를 다른 위젯과 함께 사용하실 때만 사용하세요. 감사합니다.

**Comment by jeongsehun** [comment]
@baekjungkim 안녕하세요. 
저도 위와 같은 작업을 진행하려고 하는데요 디자인 된 마커 내부에 사용자 프로필 이미지를 외부 url로 불러와 출력하고 싶습니다. 
**fromWidget()** 을 통해 marker 위젯을 만들고 url을 넘겨주는 형태로 개발하다가 이미지가 로드되지 않아 마커 위젯 내부에서 이미지 위젯을 사용하면 안된다는걸 알았습니다.
혹시 해당 부분 어떻게 해결하셨을까요??

**Comment by note11g** [comment]
> @baekjungkim 안녕하세요. 
> 저도 위와 같은 작업을 진행하려고 하는데요 디자인 된 마커 내부에 사용자 프로필 이미지를 외부 url로 불러와 출력하고 싶습니다. 
> **fromWidget()** 을 통해 marker 위젯을 만들고 url을 넘겨주는 형태로 개발하다가 이미지가 로드되지 않아 마커 위젯 내부에서 이미지 위젯을 사용하면 안된다는걸 알았습니다.
> 혹시 해당 부분 어떻게 해결하셨을까요??

이미지 프로바이더를 통해서 해당 이미지에 대한 preload 후 하시면 됩니다!

**Comment by jeongsehun** [comment]
@note11g 알려주신 방법 참고해볼게요! 감사합니다 :)
