### ISSUE TITLE
Flutter 3.0 빌드 오류

### ISSUE THREAD

**Issue by tree1891** [note11g/flutter_naver_map#18]
Flutter 3.0으로 빌드시 오류가 발생합니다.

**Comment by wnsgh78b** [comment]
https://github.com/wnsgh78b/flutter_naver_map

일단 제가 임시로 동작 가능하게 만들긴 했습니다.

문제는 useSurface: true 시 안드로이드에서 지도 말고 다른 UI가 안보이게되는 문제가 있습니다.
3.0 으로 빌드 해서 문제생기는 건지 아니면 다른 버전에서도 문제가 생기는지는 파악중 입니다.

**Comment by ItdaTeam** [comment]
패키지 업데이트 해주시면 감사하겠습니다. ㅠ.ㅠ;  빌드 할때 크러쉬 되네요.

**Comment by note11g** [comment]
해당 임시 동작 PR 승인 하였습니다.
적극적인 지원은 1.0 버전에서 이루어질 예정입니다.
추가 이슈가 있다면 다시 열어주세요. 감사합니다.
