### ISSUE TITLE
Map is not functioning only showing default map

### ISSUE THREAD

**Issue by Safiullah2000** [note11g/flutter_naver_map#180]
I have implement naver map with flutter naver map plugin 1.1.2. The problem is i have changed map type and also add initial camera position to busan but map still starts on seoul city which is default why it's not working   
![naver](https://github.com/note11g/flutter_naver_map/assets/45438596/7ba14d5d-0e6a-4433-a90b-a6545f482895)

**Comment by note11g** [comment]
@Safiullah2000 Can you add a reproduction step?

**Comment by Safiullah2000** [comment]
Step 1:  Register the Application in the Naver map console

Step 2: Adding dependency by following line:
            flutter pub add flutter_naver_map

Step 3:  Add the following lines in AndroidManifest.xml
        <meta-data
            android:name="com.naver.maps.map.CLIENT_ID"
            android:value="YOUR-CLIENT-ID"/>
        <meta-data
            android:name="com.naver.maps.map.CLIENT_SECRET"
            android:value="YOUR-CLIENT-SECRET-ID"/>
 
 Step 4: Add this line in main.dart
         WidgetsFlutterBinding.ensureInitialized();
          await NaverMapSdk.instance.initialize(
                     clientId: ''YOUR-CLIENT-ID",
                     onAuthFailed: (error) {
                            print('Auth failed: $error');
                      });
 
 Step 5: This is my Naver Map screen code 

![nav](https://github.com/note11g/flutter_naver_map/assets/45438596/62bd612e-e9ae-4c0a-932b-880d5a60477a)

My flutter version is 3.13.9 

Tell me if i made a mistake i will be very thankful to you

**Comment by note11g** [comment]
@Safiullah2000 Please check this sample. clone and run please.
https://github.com/note11g/flutter_naver_map_pure_example/tree/sample/%23180

<img width="372" src="https://github.com/note11g/flutter_naver_map/assets/67783062/cbe0e0f7-cf71-4dec-8330-81725ac06aa9"/>

**Comment by Safiullah2000** [comment]
The clone you send it's working and my app is also working but it works when i am calling naver map in start of app but when i am opening map screen through splash screen -> Login Screen -> Home Page -> Tracks -> Naver Map Screen it's not working can you tell me what will be the solution for. this

**Comment by Safiullah2000** [comment]
Issue is resolved thanks @note11g

**Comment by note11g** [comment]
@Safiullah2000 I'm so glad it's been resolved! Please use it well, and have a nice day :) Thank you!
