### ISSUE TITLE
Error: No named parameter with the name 'size'.

### ISSUE THREAD

**Issue by grandff** [note11g/flutter_naver_map#182]
```bash
# debug console
.../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_naver_map-1.1.2/lib/src/util/widget_to_image.dart:43:13: Error: No named parameter with the name 'size'.
            size: size, devicePixelRatio: view.devicePixelRatio),
            ^^^^
../flutter/flutter/packages/flutter/lib/src/rendering/view.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const ViewConfiguration({
        ^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
```

```bash
# flutter doctor
[√] Flutter (Channel master, 3.20.0-6.0.pre.50, on Microsoft Windows [Version 10.0.22631.3007], locale ko-KR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
[√] Android Studio (version 2023.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

mac에서 개발하다가 윈도우 쓸일이 있어서 사용했는데, 이런 오류가 발생하네요.
제가 개발한 앱이 현재 내부 로직 문제로 지도화면 -> 페이지 이동 -> 페이지 pop -> 앱 crash
이슈가 있어서 master 채널을 사용 중입니다.

혹시 원인을 알 수 있을까요?

**Comment by note11g** [comment]
해당 부분 인지하고 있는 상황이며, flutter 3.18부터 View에 대한 인자들이 바뀌어 발생하는 현상입니다.
master 채널을 사용하시는게 불가피하신가요?

**Comment by grandff** [comment]
@note11g 아 그렇군요. 맥에서는 이전 버전의 마스터 채널을 사용해서 오류가 안생겼나봅니다. 어차피 주로 작업하는 건 맥에서하고, 이미 인지하고 계신 거라면 기다리면 될거 같네요. 감사합니다~!

**Comment by note11g** [comment]
https://github.com/note11g/flutter_naver_map/tree/migrate_3.20
해당 브랜치에서 이 작업에 대한 변경사항을 확인할 수 있습니다.
플러터 버전 업그레이드와 마이그레이션 버전으로의 라이브러리 업그레이드를 동시에 진행하도록 하겠습니다.

**Comment by note11g** [comment]
오늘 새벽(한국 시간 기준 2am)에 있었던 Google IO에서 flutter 3.22.0이 발표되었습니다.
해당 버전으로 인한 braking changes 중 하나가 해당 이슈와 연관이 있어, 이슈를 다시 열었습니다. 감사합니다.
다음 버전에서 바로 수정됩니다.

**Comment by note11g** [comment]
잠시 짬이 나서, #237 PR 업로드하였습니다. (잠시 후에 `1.2.2-flutter3.22` 버전으로 pub.dev에 업로드됩니다)
다른 업데이트 없이, flutter 3.22에 대한 대응만이 수정사항이니, 참고하세요.
