### ISSUE TITLE
Git을 통한 Clone 불가

### ISSUE THREAD

**Issue by WTPENGUIN** [note11g/flutter_naver_map#187]
안녕하십니까. 좋은 패키지 잘 사용하고 있습니다.

다름 아니라, 현재 git을 통한 소스코드 clone이 오류와 함께 되지 않는 현상이 발생하고 있습니다.

![클론 오류](https://github.com/note11g/flutter_naver_map/assets/28136137/428a6b10-f090-44cd-a05a-1c509776b840)

***error: invalid path '.pubignore '*** 라는 메세지와 함께 clone이 되지 않고 있는데, 확인 부탁드리겠습니다.

**Comment by note11g** [comment]
안녕하세요. 이슈를 제보해주셔서 감사드립니다.
해당 현상은 `.pubignore ` 파일명에 공백(SPACE, U+0020)이 포함되어 있어, 윈도우 플랫폼에서만 나타나는 현상인 것으로 보입니다.
바로 해당 현상 수정하였습니다. 감사합니다.
