### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by Sanjarbek-Olimov** [note11g/flutter_naver_map#188]
<img width="892" alt="image_2024-02-24_01-21-11" src="https://github.com/note11g/flutter_naver_map/assets/83695032/5e70c4f1-31d4-4eeb-911d-51480f1b7a81">
After updating flutter version to 3.19. 
While building an app, there is an error as in the image!

**Comment by note11g** [comment]
hi. Could you please try a clean build and then rebuild in Android Studio(or gradle)?

**Comment by Sanjarbek-Olimov** [comment]
> hi. Could you please try a clean build and then rebuild in Android Studio(or gradle)? https://stackoverflow.com/questions/16636848/equivalent-of-clean-build-in-android-studio

Hi. I tried several times. But it could not help!

**Comment by note11g** [comment]
Could you please share your project's android styles.xml file? 
You can find it at `[project]/android/app/src/main/res/values/styles.xml`.

**Comment by Sanjarbek-Olimov** [comment]
> Could you please share your project's android styles.xml file? You can find it at `[project]/android/app/src/main/res/values/styles.xml`.

![Uploading image_2024-02-24_15-40-52.png…]()

**Comment by note11g** [comment]
Sorry, It's not re-produced on my environment.
please more infomation about your development environment. thank you.

**Comment by Sanjarbek-Olimov** [comment]
I created new Flutter project and migrated previous project all codes to this new project. Now it works fine!

**Comment by note11g** [comment]
I'm glad to hear it's been resolved. Can we close this issue then?

**Comment by note11g** [comment]
I'll close this issue. 
If the problem re-produced or if you have any additional questions, 
please re-open the issue. Thank you.
