### ISSUE TITLE
lateinit property naverMap has not been initialized.

### ISSUE THREAD

**Issue by dylan-kwon** [note11g/flutter_naver_map#19]
네이버 지도 사용 중 간혹 아래 같은 크래시가 발생하며 지도가 검은색으로 보입니다.

### NaverMapController.java
```
Caused by k.w
lateinit property naverMap has not been initialized
```
> map.naver.plugin.net.note11.naver_map_plugin.NaverMapController.dispose (NaverMapController.java:40)
io.flutter.plugin.platform.VirtualDisplayController.dispose (VirtualDisplayController.java:16)
io.flutter.plugin.platform.PlatformViewsController.flushAllViews (PlatformViewsController.java:22)
io.flutter.plugin.platform.PlatformViewsController.onDetachedFromJNI (PlatformViewsController.java)
io.flutter.embedding.engine.FlutterEngine.destroy (FlutterEngine.java:36)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:90)
io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java:18)

### message_codecs.dart
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
```
> PlatformException(error, lateinit property naverMap has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property naverMap has not been initialized at m.a.a.a.a.a.m.c(NaverMapController.kt:7) at i.a.d.e.n.c(VirtualDisplayController.java:4) at i.a.d.e.m$a.g(PlatformViewsController.java:6) at i.a.c.b.l.j$a.c(PlatformViewsChannel.java:5) at i.a.c.b.l.j$a.onMethodCall(PlatformViewsChannel.java:5) at i.a.d.a.i$a.a(MethodChannel.java:2) at i.a.c.b.f.c.i(DartMessenger.java:2) at i.a.c.b.f.c.j(DartMessenger.java:2) at i.a.c.b.f.c.k(Unknown Source:0) at i.a.c.b.f.a.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:226) at android.os.Looper.loop(Looper.java:313) at android.app.ActivityThread.main(ActivityThread.java:8663) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) ). Error thrown null.

**Comment by note11g** [comment]
너무 늦게 답변드려 죄송합니다.
dispose가 비정상적으로 된 것 같습니다. 더 정보를 제공해주실 수 있으실까요?

**Comment by note11g** [comment]
해당 이슈는 오랫동안 답변이 없어, 이슈를 닫도록 하겠습니다.
같은 이슈가 발생할 경우, 코멘트와 함께 다시 열어주시면 감사드리겠습니다.
