### ISSUE TITLE
ios 빌드 이슈

### ISSUE THREAD

**Issue by jung-ah-choi** [note11g/flutter_naver_map#191]
안녕하세요 김노트님 :)
만들어주신 플러그인을 토이 프로젝트에 사용하려던 중에 ios 빌드 오류가 나서 이슈를 만들게 되었습니다.

- 오류 내용 :  No such module 'NMapsMap'
아래는 XCode에서 빌드했을 때 발생하는 오류창입니다.
![스크린샷 2024-02-27 오후 2 47 31](https://github.com/note11g/flutter_naver_map/assets/65520261/e797a5ad-b733-4c01-a2b6-2dbf65db680e)

- 프로젝트에 사용된 버전
Xcode : 15.2
CocoaPods 1.15.1
Flutter : 3.19.1
Dart: 3.3.0

바쁘시겠지만 이슈 해결에 도움을 주신다면 정말 감사하겠습니다 🙏

**Comment by note11g** [comment]
안녕하세요.
https://note11.dev/flutter_naver_map/start/initial_setting#ios
혹시 해당 문서의 과정을 수행하셨을까요?

**Comment by jung-ah-choi** [comment]
@note11g 넵, 진행하였는데도 동일한 오류가 발생합니다 😭

**Comment by note11g** [comment]
flutter 쪽에서 실행하신게 맞으실까요?
XCode로 실행하려 하면 첫 실행시에는 받아지지 않을 수도 있습니다.

**Comment by jung-ah-choi** [comment]
@note11g 작성해주신 명령어 터미널에서 실행하고 vscode에서 빌드했는데도 동일한 오류가 발생하네요 ㅠㅠ..
(전에 말씀드린 에러도 vscode에서 빌드 후 오류가 발생해서 Xcode에서 빌드를 했던 경우였습니다)
<img width="842" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/65520261/ef09d796-3626-4455-98fa-35c18394b0e4">

**Comment by note11g** [comment]
#105 #75 이슈가 비슷한 내용이었던 것 같습니다.
해당 이슈에 코멘트 참고하여 확인 부탁드립니다.
해결하셨다면 해결 방법을 리포트해주시면 감사드리겠습니다.
해결하지 못하셨다면, 다시 코멘트를 남겨주세요.

**Comment by jung-ah-choi** [comment]
넵 해당 이슈들 다 확인하고 적용했는데도 동일한 오류가 발생해서 혹시나 해결방안이 있을까 해서 이슈를 열게 되었습니다 🥲
플러그인 이슈는 아닌 것 같긴 한데 혹시 에러 해결에 도움을 얻을 수 있을까 해서 요청 드리긴 했습니다 🥹

**Comment by note11g** [comment]
https://yerang.kim/swift/[xcode]-cocoapods---no-such-module-error/
https://wiwi-pe.tistory.com/228

두가지 참고하여 시도해보시겠어요?

**Comment by jung-ah-choi** [comment]
@note11g 직접 찾아주셨는데 참고해서 해도 안되네요 ㅠㅠ.. 사실 구글링으로 나오는 결과 거의 다 참고해서 시도해봤는데도 안되서 직접 여쭤보게 됐네요.. 😅

**Comment by note11g** [comment]
이건 아닐 것 같긴 합니다만, 혹시 최소 실행 가능 버전을 11로 올려보시겠어요?

**Comment by jung-ah-choi** [comment]
@note11g 현재 12 버전으로 되어 있습니다 ㅠㅠ 늦은 시간까지 함께 고민해주셔서 감사합니다.

**Comment by note11g** [comment]
아, 도움이 되어드렸다면 더 좋았을텐데 아쉽네요.
빠른 시일 내 해결하실겁니다.
해결하시면 혹시 관련 내용 공유해주실 수 있을까요?

**Comment by note11g** [comment]
감사합니다. 좋은 밤 되세요:)

**Comment by note11g** [comment]
플러그인 이슈가 아닌 것으로 추정되며, 
2주간의 업데이트 사항이 없으므로 해당 이슈를 닫도록 하겠습니다.
업데이트가 있으시다면 이슈를 다시 열거나 코멘트를 남겨주세요. 감사합니다.
