### ISSUE TITLE
지도에 없는 오버레이를 삭제 시도하면, NPE가 발생함

### ISSUE THREAD

**Issue by comversecorp** [note11g/flutter_naver_map#192]
최근 배포한  1.2.1로 업그레이드로 하고 앱을 사용해 보면 지도에 마커/경로 등을 표시할때 
아래와 같은 오류로그가 발생하고 있습니다.  (  화면은 정상동작 중 )
원인 및 조치방법 부탁 드립니다. 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (31093): #0      _NOverlayControllerImpl.deleteWithInfo (package:flutter_naver_map/src/controller/overlay/overlay_controller_impl.dart:48)
E/flutter (31093): #1      _NaverMapControllerImpl.deleteOverlay (package:flutter_naver_map/src/controller/map/controller.dart:159)
E/flutter (31093): <asynchronous suspension>

**Comment by note11g** [comment]
안녕하세요, 먼저 이슈를 제보해주셔서 감사드립니다.
재현 및 원인 분석을 위해 관련하여 재현을 확인할 수 있는 코드를 부탁드립니다.

**Comment by comversecorp** [comment]
@note11g  사용한 코드입니다.

_mapController?.clearOverlays(type: NOverlayType.pathOverlay);
_mapController?.deleteOverlay( NOverlayInfo(type: NOverlayType.marker, id: 'pinStart'));
_mapController?.deleteOverlay( NOverlayInfo(type: NOverlayType.marker, id: 'pinEnd'));
_clearMarkerWayPoints();

**Comment by note11g** [comment]
추가한 코드도 알려주실 수 있으실까요?
아래 `_clearMarkerWayPoints()`의 내용도 부탁드리겠습니다.

**Comment by comversecorp** [comment]
Future<void> _clearMarkerWayPoints() async {
    logger.warning('clear marker waypoint');
    for (String id in markerWayPoints) {
      logger.warning('delete id = $id');
      _mapController
          ?.deleteOverlay(NOverlayInfo(type: NOverlayType.marker, id: id));
    }
    markerWayPoints.clear();
  }

**Comment by note11g** [comment]
해당 현상은 지도에 현재 추가되지 않은 오버레이에 대한 정보를 넣게되면 발생하는 것으로 보입니다.
다음 버전에서는 Null Check Operator 대신, assertion을 사용하여 디버깅에 도움이 되도록 수정하겠습니다. (지금은 대안으로 try-catch문을 사용하시거나, 수정사항이 반영된 dev-1.2.3 브랜치를 사용하시면 됩니다. 
감사합니다.
