### ISSUE TITLE
1.2.1 버전에서 초기화가 정상적으로 종료 되지 않음

### ISSUE THREAD

**Issue by juyunyoung** [note11g/flutter_naver_map#194]
../../.pub-cache/hosted/pub.dev/flutter_naver_map-1.1.1/lib/src/util/widget_to_image.dart:35:13: Error: No named parameter with the name 'size'.
            size: size, devicePixelRatio: view.devicePixelRatio),
            ^^^^
../../flutter/packages/flutter/lib/src/rendering/view.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const ViewConfiguration({
        ^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

1.2.1 버전 초기화 할때 에러 납니다. 

세팅 환경은 아래와 같습니다. 
flutter_naver_map :1.2.1 
flutter  sdk: '>=3.1.5 <4.0.0'
minSdkVersion 23
targetSdkVersion 30

**Comment by note11g** [comment]
해당 이슈는 사용 중인 flutter channel이 master/main 일 때 발생하는 문제입니다.
flutter 3.20-pre.n 부터 flutter 내부 API가 변경되어 해당 문제가 발생합니다.

해결 방법은 두가지가 있습니다.
1. flutter channel을 stable로 변경
2. flutter_naver_map 버전을 깃허브 migrate_3.20 브랜치 버전으로 변경. 이 경우, 1.2.0의 코드베이스를 사용하므로, 1.2.1의 개선사항들을 사용할 수 없음.

감사합니다.

**Comment by note11g** [comment]
https://github.com/note11g/flutter_naver_map/issues/182
해당 이슈와 중복이므로, 이슈를 닫습니다.
해당 이슈에 코멘트를 남겨주세요. 만약, 다른 문제라고 판단하신다면 다시 이 문제를 열어주세요. 감사합니다.
