### ISSUE TITLE
지도화면에서 qr코드 스캔하는 화면을 갔다가 오면 지도가 하얗게 되고 작동안합니다.

### ISSUE THREAD

**Issue by crjung** [note11g/flutter_naver_map#196]
지도화면에서 qr코드 스캔하는 화면을 갔다가 오면 지도가 하얗게 되고 작동안합니다.
네이버 지도 1.2.1 최신버전 사용했습니다.

mobile_scanner, qr_code_scanner 등 사용해 보았는데요.
카메라가 동작한 뒤에 지도화면으로 돌아오는 경우에 발생하는 것으로 보입니다.
아래 로그 첨부합니다.
dependencies도 마지막에 첨부했습니다.

1. qr코드 scanner 화면이동
I/ViewRootImpl@ed9e22a[MainActivity]( 9228): ViewPostIme pointer 0
I/ViewRootImpl@ed9e22a[MainActivity]( 9228): onDisplayChanged oldDisplayState=2 newDisplayState=2
I/ViewRootImpl@ed9e22a[MainActivity]( 9228): ViewPostIme pointer 1
I/flutter ( 9228): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9228): │ 16:26:46.089 (+0:03:14.351303)
I/flutter ( 9228): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9228): │ 🐛 onClick: qrcode
I/flutter ( 9228): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[GETX] WARNING, consider using: "Get.to(() => Page())" instead of "Get.to(Page())".
Using a widget function instead of a widget fully guarantees that the widget and its controllers will be removed from memory when they are no longer used.
      
[GETX] GOING TO ROUTE /PageQrRiding
D/CameraOrientationUtil( 9228): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil( 9228): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/TransportRuntime.SQLiteEventStore( 9228): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
D/DynamicRangeResolver( 9228): Resolved dynamic range for use case androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa to no compatible HDR dynamic ranges.
D/DynamicRangeResolver( 9228): DynamicRange@94f1146{encoding=UNSPECIFIED, bitDepth=0}
D/DynamicRangeResolver( 9228): ->
D/DynamicRangeResolver( 9228): DynamicRange@d1ab921{encoding=SDR, bitDepth=8}
D/CameraOrientationUtil( 9228): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/DeferrableSurface( 9228): Surface created[total_surfaces=1, used_surfaces=0](androidx.camera.core.processing.SurfaceEdge$SettableSurface@f180a3b}
D/DeferrableSurface( 9228): Surface created[total_surfaces=2, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@b730f17}
D/TransportRuntime.JobInfoScheduler( 9228): Scheduling upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) with jobId=274605192 in 876715ms(Backend next call timestamp 1709797283083). Attempt 1
D/DeferrableSurface( 9228): New surface in use[total_surfaces=2, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@b730f17}
D/DeferrableSurface( 9228): use count+1, useCount=1 androidx.camera.core.SurfaceRequest$2@b730f17
D/CameraOrientationUtil( 9228): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil( 9228): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil( 9228): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/DeferrableSurface( 9228): Surface created[total_surfaces=3, used_surfaces=1](androidx.camera.core.impl.ImmediateSurface@ecaa770}
D/CameraOrientationUtil( 9228): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil( 9228): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Use case androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039 ACTIVE
D/UseCaseAttachState( 9228): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Use case androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076 ACTIVE
D/UseCaseAttachState( 9228): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Use cases [androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039, androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076] now ATTACHED
D/UseCaseAttachState( 9228): All use case: [androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039, androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076] for camera: 0
D/UseCaseAttachState( 9228): Active and attached use case: [androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039, androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076] for camera: 0
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Resetting Capture Session
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Releasing session in state INITIALIZED
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Attempting to force open the camera.
D/CameraStateRegistry( 9228): tryOpenCamera(Camera@b26c55b[id=0]) [Available Cameras: 1, Already Open: false (Previous state: CLOSED)] --> SUCCESS
D/CameraStateRegistry( 9228): Recalculating open cameras:
D/CameraStateRegistry( 9228): Camera                                       State                 
D/CameraStateRegistry( 9228): -------------------------------------------------------------------
D/CameraStateRegistry( 9228): Camera@5c10810[id=1]                         UNKNOWN               
D/CameraStateRegistry( 9228): Camera@c5fbb4b[id=2]                         UNKNOWN               
D/CameraStateRegistry( 9228): Camera@b26c55b[id=0]                         OPENING               
D/CameraStateRegistry( 9228): Camera@5cc5c72[id=3]                         UNKNOWN               
D/CameraStateRegistry( 9228): -------------------------------------------------------------------
D/CameraStateRegistry( 9228): Open count: 1 (Max allowed: 1)
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Opening camera.
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/CameraStateMachine( 9228): New public camera state CameraState{type=OPENING, error=null} from OPENING and null
D/CameraStateMachine( 9228): Publishing new public camera state CameraState{type=OPENING, error=null}
D/UseCaseAttachState( 9228): All use case: [androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039, androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076] for camera: 0
I/CameraManagerGlobal( 9228): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPENING for client com.mobigo.bike.app API Level 2 User Id 0
I/CameraManagerGlobal( 9228): postSingleUpdate device: camera id 0 status STATUS_NOT_AVAILABLE
I/CameraManagerGlobal( 9228): postSingleUpdate device: camera id 0 status STATUS_NOT_AVAILABLE
I/CameraManagerGlobal( 9228): postSingleUpdate device: camera id 0 status STATUS_NOT_AVAILABLE
I/CameraManagerGlobal( 9228): postSingleUpdate device: camera id 0 status STATUS_NOT_AVAILABLE
I/CameraManagerGlobal( 9228): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.mobigo.bike.app API Level 2 User Id 0
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Use case androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039 ACTIVE
D/UseCaseAttachState( 9228): Active and attached use case: [androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039, androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076] for camera: 0
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Use case androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076 ACTIVE
D/UseCaseAttachState( 9228): Active and attached use case: [androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039, androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076] for camera: 0
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Issue capture request
D/UseCaseAttachState( 9228): Active and attached use case: [androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039, androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076] for camera: 0
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Transitioning camera internal state: OPENING --> OPENED
D/CameraStateRegistry( 9228): Recalculating open cameras:
D/CameraStateRegistry( 9228): Camera                                       State                 
D/CameraStateRegistry( 9228): -------------------------------------------------------------------
D/CameraStateRegistry( 9228): Camera@5c10810[id=1]                         UNKNOWN               
D/CameraStateRegistry( 9228): Camera@c5fbb4b[id=2]                         UNKNOWN               
D/CameraStateRegistry( 9228): Camera@b26c55b[id=0]                         OPEN                  
D/CameraStateRegistry( 9228): Camera@5cc5c72[id=3]                         UNKNOWN               
D/CameraStateRegistry( 9228): -------------------------------------------------------------------
D/CameraStateRegistry( 9228): Open count: 1 (Max allowed: 1)
D/CameraStateMachine( 9228): New public camera state CameraState{type=OPEN, error=null} from OPEN and null
D/CameraStateMachine( 9228): Publishing new public camera state CameraState{type=OPEN, error=null}
D/UseCaseAttachState( 9228): All use case: [androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039, androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076] for camera: 0
D/UseCaseAttachState( 9228): Active and attached use case: [androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039, androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076] for camera: 0
D/SyncCaptureSessionBase( 9228): [androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl@faf421b] getSurface...done
D/CaptureSession( 9228): Opening capture session.
D/DeferrableSurface( 9228): use count+1, useCount=2 androidx.camera.core.SurfaceRequest$2@b730f17
D/DeferrableSurface( 9228): New surface in use[total_surfaces=3, used_surfaces=2](androidx.camera.core.impl.ImmediateSurface@ecaa770}
D/DeferrableSurface( 9228): use count+1, useCount=1 androidx.camera.core.impl.ImmediateSurface@ecaa770
D/CaptureSession( 9228): Attempting to send capture request onConfigured
D/CaptureSession( 9228): Issuing request for session.
D/Camera2CaptureRequestBuilder( 9228): createCaptureRequest
D/CaptureSession( 9228): Issuing capture request.
D/Camera2CaptureRequestBuilder( 9228): createCaptureRequest
D/CaptureSession( 9228): CameraCaptureSession.onConfigured() mState=OPENED
D/CaptureSession( 9228): CameraCaptureSession.onReady() OPENED
I/CameraManagerGlobal( 9228): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.mobigo.bike.app API Level 2 User Id 0
I/ViewRootImpl@ed9e22a[MainActivity]( 9228): onDisplayChanged oldDisplayState=2 newDisplayState=2
D/TransportRuntime.SQLiteEventStore( 9228): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 9228): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
W/Vision  ( 9228): Would have logged:
W/Vision  ( 9228): # m.aod@e8e80bf5
I/mobigo.bike.app( 9228): EglImage dataspace changed, need recreate
D/TransportRuntime.SQLiteEventStore( 9228): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 9228): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore( 9228): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 9228): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
I/mobigo.bike.app( 9228): EglImage dataspace changed, need recreate
I/mobigo.bike.app( 9228): EglImage dataspace changed, need recreate
I/mobigo.bike.app( 9228): EglImage dataspace changed, need recreate
I/mobigo.bike.app( 9228): EglImage dataspace changed, need recreate
I/mobigo.bike.app( 9228): EglImage dataspace changed, need recreate
I/mobigo.bike.app( 9228): EglImage dataspace changed, need recreate
I/mobigo.bike.app( 9228): EglImage dataspace changed, need recreate
I/mobigo.bike.app( 9228): EglImage dataspace changed, need recreate
D/InsetsSourceConsumer( 9228): applyRequestedVisibilityToControl: visible=true, type=1

2. 다시 지도화면으로 돌아온 뒤
W/System  ( 9228): A resource failed to call Surface.release. 
I/BpBinder( 9228): onLastStrongRef automatically unlinking death recipients: 
I/ViewRootImpl@ed9e22a[MainActivity]( 9228): ViewPostIme pointer 0
D/WindowOnBackDispatcher( 9228): onBackInvoked, owner=ViewRootImpl@ed9e22a[MainActivity], callback=io.flutter.embedding.android.FlutterActivity$1@a40ed25
I/flutter ( 9228): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9228): │ 16:27:00.417 (+0:03:28.679999)
I/flutter ( 9228): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9228): │ 🐛 goMain
I/flutter ( 9228): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9228): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9228): │ 16:27:00.426 (+0:03:28.688480)
I/flutter ( 9228): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9228): │ 🐛 QR bikeNumber:null
I/flutter ( 9228): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[GETX] CLOSE TO ROUTE /PageQrRiding
D/DeferrableSurface( 9228): surface closed,  useCount=2 closed=true androidx.camera.core.SurfaceRequest$2@b730f17
D/DeferrableSurface( 9228): surface closed,  useCount=0 closed=true androidx.camera.core.processing.SurfaceEdge$SettableSurface@f180a3b
D/DeferrableSurface( 9228): Surface terminated[total_surfaces=2, used_surfaces=2](androidx.camera.core.processing.SurfaceEdge$SettableSurface@f180a3b}
D/DeferrableSurface( 9228): use count-1,  useCount=1 closed=true androidx.camera.core.SurfaceRequest$2@b730f17
D/DeferrableSurface( 9228): surface closed,  useCount=1 closed=true androidx.camera.core.impl.ImmediateSurface@ecaa770
W/WindowOnBackDispatcher( 9228): sendCancelIfRunning: isInProgress=falsecallback=io.flutter.embedding.android.FlutterActivity$1@a40ed25
E/BufferQueueProducer( 9228): [SurfaceTexture-0-9228-3](id:240c00000009,api:4,p:1862,c:9228) dequeueBuffer: BufferQueue has been abandoned
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Use cases [androidx.camera.core.Preview-af61d4a9-7d0c-4714-88ec-0f73290042fa265739039, androidx.camera.core.ImageAnalysis-435db634-840a-4099-a7d1-2f73acf6db0d238612076] now DETACHED for camera
E/BufferQueueProducer( 9228): [SurfaceTexture-0-9228-3](id:240c00000009,api:4,p:1862,c:9228) queueBuffer: BufferQueue has been abandoned
D/UseCaseAttachState( 9228): All use case: [] for camera: 0
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Resetting Capture Session
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Releasing session in state OPENED
D/UseCaseAttachState( 9228): Active and attached use case: [] for camera: 0
D/UseCaseAttachState( 9228): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Closing camera.
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/CameraStateRegistry( 9228): Recalculating open cameras:
D/CameraStateRegistry( 9228): Camera                                       State                 
D/CameraStateRegistry( 9228): -------------------------------------------------------------------
D/CameraStateRegistry( 9228): Camera@5c10810[id=1]                         UNKNOWN               
D/CameraStateRegistry( 9228): Camera@c5fbb4b[id=2]                         UNKNOWN               
D/CameraStateRegistry( 9228): Camera@b26c55b[id=0]                         CLOSING               
D/CameraStateRegistry( 9228): Camera@5cc5c72[id=3]                         UNKNOWN               
D/CameraStateRegistry( 9228): -------------------------------------------------------------------
D/CameraStateRegistry( 9228): Open count: 1 (Max allowed: 1)
D/CameraStateMachine( 9228): New public camera state CameraState{type=CLOSING, error=null} from CLOSING and null
D/CameraStateMachine( 9228): Publishing new public camera state CameraState{type=CLOSING, error=null}
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Resetting Capture Session
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Releasing session in state CLOSING
D/CaptureSession( 9228): onSessionFinished()
E/BufferQueueProducer( 9228): [SurfaceTexture-0-9228-3](id:240c00000009,api:4,p:1862,c:9228) cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 9228): [SurfaceTexture-0-9228-3](id:240c00000009,api:4,p:1862,c:9228) cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 9228): [SurfaceTexture-0-9228-3](id:240c00000009,api:4,p:1862,c:9228) cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 9228): [SurfaceTexture-0-9228-3](id:240c00000009,api:4,p:1862,c:9228) cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 9228): [SurfaceTexture-0-9228-3](id:240c00000009,api:4,p:1862,c:9228) cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 9228): [SurfaceTexture-0-9228-3](id:240c00000009,api:4,p:1862,c:9228) cancelBuffer: BufferQueue has been abandoned
I/CameraManagerGlobal( 9228): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.mobigo.bike.app API Level 2 User Id 0
I/ViewRootImpl@ed9e22a[MainActivity]( 9228): onDisplayChanged oldDisplayState=2 newDisplayState=2
I/CameraManagerGlobal( 9228): postSingleUpdate device: camera id 0 status STATUS_PRESENT
I/CameraManagerGlobal( 9228): postSingleUpdate device: camera id 0 status STATUS_PRESENT
I/CameraManagerGlobal( 9228): postSingleUpdate device: camera id 0 status STATUS_PRESENT
I/CameraManagerGlobal( 9228): postSingleUpdate device: camera id 0 status STATUS_PRESENT
I/CameraManagerGlobal( 9228): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.mobigo.bike.app API Level 2 User Id 0
D/UseCaseAttachState( 9228): Active and attached use case: [] for camera: 0
W/mobigo.bike.app( 9228): Long monitor contention with owner CameraX-core_camera_1 (9636) at void android.hardware.camera2.impl.CameraDeviceImpl.close()(CameraDeviceImpl.java:1492) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl.onDeviceError(int, android.hardware.camera2.impl.CaptureResultExtras) for 245ms
D/DeferrableSurface( 9228): use count-1,  useCount=0 closed=true androidx.camera.core.SurfaceRequest$2@b730f17
D/DeferrableSurface( 9228): Surface no longer in use[total_surfaces=2, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@b730f17}
D/DeferrableSurface( 9228): Surface terminated[total_surfaces=1, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@b730f17}
D/DeferrableSurface( 9228): use count-1,  useCount=0 closed=true androidx.camera.core.impl.ImmediateSurface@ecaa770
D/DeferrableSurface( 9228): Surface no longer in use[total_surfaces=1, used_surfaces=0](androidx.camera.core.impl.ImmediateSurface@ecaa770}
D/DeferrableSurface( 9228): Surface terminated[total_surfaces=0, used_surfaces=0](androidx.camera.core.impl.ImmediateSurface@ecaa770}
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} CameraDevice.onClosed()
D/Camera2CameraImpl( 9228): {Camera@b26c55b[id=0]} Transitioning camera internal state: CLOSING --> INITIALIZED
D/CameraStateRegistry( 9228): Recalculating open cameras:
D/CameraStateRegistry( 9228): Camera                                       State                 
D/CameraStateRegistry( 9228): -------------------------------------------------------------------
D/CameraStateRegistry( 9228): Camera@5c10810[id=1]                         UNKNOWN               
D/CameraStateRegistry( 9228): Camera@c5fbb4b[id=2]                         UNKNOWN               
D/CameraStateRegistry( 9228): Camera@b26c55b[id=0]                         CLOSED                
D/CameraStateRegistry( 9228): Camera@5cc5c72[id=3]                         UNKNOWN               
D/CameraStateRegistry( 9228): -------------------------------------------------------------------
D/CameraStateRegistry( 9228): Open count: 0 (Max allowed: 1)
D/CameraStateMachine( 9228): New public camera state CameraState{type=CLOSED, error=null} from CLOSED and null
D/CameraStateMachine( 9228): Publishing new public camera state CameraState{type=CLOSED, error=null}

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.1
  get_storage: ^2.0.3

  kakao_flutter_sdk: ^1.7.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.2
  flutter_naver_login: ^1.8.0
  sign_in_with_apple: ^5.0.0

  flutter_inappwebview: ^6.0.0-beta.22

  flutter_naver_map: ^1.2.1
  mobile_scanner: ^4.0.1
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  location: ^5.0.3
  permission_handler: ^11.0.1
  jwt_decoder: ^2.0.1
  camera: ^0.10.5+5
  fluttertoast: ^8.0.8
  http: ^1.1.0
  mask_input_formatter: ^0.0.3
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  latlong2: ^0.9.0
  share: ^2.0.4
  url_launcher: ^6.0.18

  logger: ^2.0.2+1

  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.0

**Comment by note11g** [comment]
안녕하세요, 이슈를 제보해주셔서 감사합니다.
원인 조사를 위해, 재현 가능한 최소한의 코드 샘플 부탁드립니다.
또한 실행중인 플랫폼 정보도 부탁드리겠습니다. (안드로이드 버전)
감사합니다.

**Comment by crjung** [comment]
안녕하세요.
아 제가 map을 숨기는 코드가 있었는데 깜빡했네요^^;;
해당 이슈는 삭제하겠습니다.
감사합니다.


-----Original Message-----
