### ISSUE TITLE
1.2.1 버전 파일용량

### ISSUE THREAD

**Issue by minseok-jeong-gn** [note11g/flutter_naver_map#199]
apk 파일 및 ipa 파일 사이즈가 너무 크게 증가하는대
기존 1.0.x 버전에서는 네이버 지도관련 .so 파일이 6MB 정도였는대,
이번 빌드부터는 22MB로 나오는대 혹시 왜그런지 알수 있을까요?

**Comment by note11g** [comment]
안녕하세요, 이 이슈는 해당 이슈와 중복되는 것으로 보입니다.
확인 후, 다른 이슈라고 여겨지신다면 다시 이 이슈를 열어주세요.
감사합니다.

Releated Issue: #162
