### ISSUE TITLE
flutter SDK 2.10.x 에서 아이폰 시뮬레이터에서 앱 크러쉬 증상

### ISSUE THREAD

**Issue by ItdaTeam** [note11g/flutter_naver_map#20]
안드 애뮬레이터, 실단말기에서는 잘되는데 

아이폰 실단말기에서는 잘되고 있으나 시뮬레이터에서는 네이버 지도 로드중에 앱 크러쉬가 납니다. 

시뮬레이터 IOS  버젼은 15.2 인데  확인 가능 할까요?

**Comment by note11g** [comment]
시뮬레이터 지원을 이전에는 지원하지 않았으나, 현재는 해결 중인 과제입니다.
실수로, 해당 지원을 열어놓아서 발생한 일으로 생각해주시면 될 것 같습니다.
다음 버전에서 지원하도록 최선을 다하겠습니다. 감사합니다. 좋은 하루 되세요..!

**Comment by note11g** [comment]
1.0에서 시뮬레이터 지원이 추가되었습니다.
곧 iOS 버전 개발이 끝나는대로 preview 버전 링크를 달아드리도록 하겠습니다.
감사합니다.

**Comment by note11g** [comment]
[1.0.0-dev](https://github.com/note11g/flutter_naver_map/tree/dev_preview) 에서 해당 기능을 지원합니다. 감사합니다.
