### ISSUE TITLE
[iOS] Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by minseok-jeong-gn** [note11g/flutter_naver_map#200]
현재 `flutter_naver_map 1.2.1` 버전을 쓰고 있으면 `flutter 3.19.2` 버전을 사용중에 있습니다.

테스트한 디바이스는 `iPhoneS XS` 입니다.(ios 16.3)

네이버 지도가 있는 화면으로 이동 중에 아래와 같은 에러가 발생하였습니다.

```sh
flutter_naver_map/NOverlayImage.swift:25: Fatal error: Unexpectedly found nil while unwrapping an Optional value
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x0000000192aa90f8 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x192aa90f8 <+0>: ret    

libswiftCore.dylib`:
    0x192aa90fc <+0>: b      0x192aa90f8               ; _swift_runtime_on_report
libswiftCore.dylib`:
    0x192aa9100 <+0>: adrp   x8, 365860
    0x192aa9104 <+4>: ldrb   w0, [x8, #0xabc]
Target 0: (Runner) stopped.
Lost connection to device.
```

앱스토어 커넥트 충돌 피드백 첨부합니다.
<img width="909" alt="스크린샷 2024-03-12 오전 11 47 14" src="https://github.com/note11g/flutter_naver_map/assets/142773097/2d056f9e-0261-4d29-b974-af0adda88873">

**Comment by note11g** [comment]
안녕하세요. 먼저, 이슈를 제보해주셔서 감사드립니다.
해당 오류는 올바르지 않은 에셋 경로를 넣었을 때 발생하는 것으로 추정됩니다.
assertion(debug error)으로 변경해야하지만 미처 변경하지 못하여 해당 충돌이 일어나고 있다고 보여집니다.

에셋 경로를 pubspec.yaml에 등록했는지, 에셋 경로를 정확히 입력하였는지 다시 한번 확인 부탁드립니다.
감사합니다.

**Comment by note11g** [comment]
현재 이슈가 발생하는 코드(재현 가능 샘플)를 부탁드리겠습니다.
재현 확인 후, 원인 분석을 진행하도록 하겠습니다.

**Comment by note11g** [comment]
해당 코드로 테스트한 경우, 문제없이 동작하는 것을 확인하였습니다.
참고해주세요.
```dart
  void onMapReady(NaverMapController controller) {
    final markerTest = NMarker(
        id: "t",
        position: NaverMapViewOptions.seoulCityHall.target,
        icon: NLocationOverlay.faceModeSubIcon);
    controller.addOverlay(markerTest);
  }
```

**Comment by minseok-jeong-gn** [comment]
OnMapReady 호출이후 ios의경우 현재 정확히알수없지만 테스트결과 50ms 이전에 컨트롤러에 접근해 마커를 그릴시 위와같은 에러가 발생합니다.
네이티브쪽 타이밍 이슈이지않을까 추정됩니다.

안드로이드의경우 도 계속 크래시가 발생해 
맵생성후 onCompleted호출될경우 그때부터 작업을진행하도록 변경한이후 크래시현상이 해결된것으로 보입니다.
허나 ios는 계속해서 크래시가 랜덤하게 발생하여
OnMapReady 이후  300ms 이후 컨트롤러를 사용하도록 변경이후 크래시가 나지않습니다.
300ms 는 임의로 설정한값이며 유저가 알아차리기 힘든 시간이라 설정하였습니다.

**Comment by note11g** [comment]
@minseok-jeong-gn 

해당 코드의 실행 전에 실행된 것은 아닌지 확인 부탁드립니다.

```dart
WidgetsFlutterBinding.ensureInitialized();
```


또한, 말씀하신 현상과 조건만으로는 재현이 어렵습니다.
**재현 가능한 최소한의 코드를 부탁드리겠습니다.**
