### ISSUE TITLE
백그라운드에서 포그라운드로 돌아올때 지도가 하얗게 보이는 이슈

### ISSUE THREAD

**Issue by thkim0118** [note11g/flutter_naver_map#208]
버전 1.2.1
기기 : 노트20, 갤럭시 S22, S23

백그라운드에서 포그라운드로 돌아올때 지도가 하얗게 보이는 이슈가 발생합니다.

일반적인 경우에는 발생하지 않고 네이버 지도 앱을 진입했다가 다시 돌아올 경우 발생합니다.

**Comment by thkim0118** [comment]
1.1.2 버전에서는 발생하지않고 1.2.0 이후 버전에서만 발생하고있습니다

**Comment by note11g** [comment]
https://github.com/note11g/flutter_naver_map/issues/201

해당 이슈와 중복입니다. 해당 이슈에 코멘트 남겨주시면 감사드리겠습니다!
