### ISSUE TITLE
[ANDROID] MissingPluginException(No implementation found for method clearOverlays on channel flutter_naver_map_view#3) 발생

### ISSUE THREAD

**Issue by jeongbinboo** [note11g/flutter_naver_map#209]
개발 중에는 발생하지 않았는데 앱을 배포하고 실제 사용하면서 Firebase의 Crashlytics가 다음 에러가 발생했다고 알려줍니다. flutter_naver_map 관련 오류인 것으로 보여 issue 남깁니다.

platform: android
version: 1.0.2
error:
![스크린샷 2024-03-20 오전 11 18 19](https://github.com/note11g/flutter_naver_map/assets/74458913/e4144c6e-fa70-4165-ae67-da3ea5d05a3f)

감사합니다

**Comment by note11g** [comment]
안녕하세요, 이슈를 제보해주셔서 감사드립니다.
오류의 재현과 원인 파악을 위해, clearOverlay 메서드를 사용 중인 코드를 부탁드리겠습니다.

**Comment by jeongbinboo** [comment]
` if (readyAllocation is AsyncData && runningAllocation is AsyncData) {
      switch (markerOptionState.code) {
        case 'ALL':
          widget.mapController.clearOverlays();
          markerList = getMarkerList(
              [...readyAllocation.value!, ...runningAllocation.value!],
              context);
          widget.mapController.addOverlayAll({...markerList});
          break;
        case 'READY':
          widget.mapController.clearOverlays();
          markerList = getMarkerList(readyAllocation.value!, context);
          widget.mapController.addOverlayAll({...markerList});
          break;
        case 'RUNNING':
          widget.mapController.clearOverlays();
          markerList = getMarkerList(runningAllocation.value!, context);
          widget.mapController.addOverlayAll({...markerList});
          break;
        default:
      }
    } else {
      widget.mapController.clearOverlays();
    }`
    
    switch문의 모두(ALL), 대기(READY), 진행 중(RUNNING) 각 케이스에 해당하는 마커를 보여주기 전에 clearOverlays 함수를 사용합니다!

**Comment by note11g** [comment]
혹시, 좀 더 길게 stackTrace를 제공해주실 수 있으실까요?

**Comment by note11g** [comment]
2주간 추가적인 코멘트가 없어, 이슈를 닫도록 하겠습니다.
만약 1.2.2 이상의 버전에서, 사용중에 다시 해당 이슈가 발생하신다면 재현 가능 코드와 함께 이 이슈를 다시 열어주세요.
감사합니다, 좋은 하루 되세요!
