### ISSUE TITLE
[IOS]앱 진입 시 바로 infoWindow Open 방법

### ISSUE THREAD

**Issue by ccomangi2** [note11g/flutter_naver_map#21]
안녕하세요. 혹시 ios에서 앱 진입 시 바로 infowWindow를 Open 하는 방법이 있을까요?

**Comment by note11g** [comment]
안녕하세요.
어떤 화면에 접근하던지, 
```dart
NaverMap(onMapCreated: (NaverMapController controller) {
    // 해당 함수가 호출되면, 지도가 로딩 된 것입니다.
})
``` 
처럼, 지도가 로딩이 완료되는 시점을 받을 수 있습니다.
자세한 내용은 아래 문서를 확인하시면 도움되실 것 같습니다. 감사합니다.

https://pub.dev/documentation/flutter_naver_map/latest/flutter_naver_map/NaverMap/onMapCreated.html
