### ISSUE TITLE
navermap 웹 버전 출시는 힘들까요? 너무 필요한데.. 

### ISSUE THREAD

**Issue by ItdaTeam** [note11g/flutter_naver_map#214]
개발자 단톡방도 그렇고 네이버맵이 웹버전이 안되서 이리 저리 고민이 많습니다.

구글지도만 현재 웹 버전을 지원하고 있는데 

네이버맵도 플러터 웹 지원을 해주시면 너무 큰 도움 될듯 합니다. 

간곡하게 다시 부탁드리오니 검토 부탁드립니다.

**Comment by note11g** [comment]
안녕하세요. 
웹 버전의 경우 계속해서 말씀드렸지만, 아직까지는 지원 계획이 없습니다.

여기에는 몇가지 이유가 있는데요,
당장 Android, iOS만 지원하는 모바일 패키지만으로도 오픈소스를 유지하는데 공수가 꽤 들기도 하며,
Flutter Web의 경우 아직까지는 이슈가 끊이지 않고 있어, 유지보수가 더 지속적으로 필요해질 것 같아 어렵다는 것이 제 개인적인 생각입니다. (게다가, NaverMap JS SDK 역시 모바일과는 다른 코드베이스를 가지고 있기에 유지보수 뿐만 아니라, 제작에 있어서도 더더욱 그렇습니다)
이 패키지를 유지하는 동력은 적어도 아직까지는 어떠한 지원도 없이 커뮤니티와 제 책임감에 의해서이기 때문에, 
제가 감당할 수 없는 상황에서 책임지지 못할만한 지원을 보장드리는 것은 어렵다고 판단됩니다.

나중에 여력이 생기거나, Co-Maintainer 분이 생기게 될 때까지는 웹버전에 대한 지원은 말씀드리기 어려운 점 양해 바랍니다.
감사합니다, 좋은 하루 되세요.
