### ISSUE TITLE
[Android] 안드로이드 백그라운드 - 포그라운드 시 맵이 흰색으로 변함

### ISSUE THREAD

**Issue by kindkmj** [note11g/flutter_naver_map#215]
백그라운드 사용시 일정시간 (시간을 체크하지 않았지만 2~30분 이상 으로 예상됩니다) 포그라운드 변경시 맵이 흰색으로 표기가 됩니다.
이때 맵을 다시 띄어주는 방법이 있을까요?
맵이 그려지지 않음을 체크하여 다시 띄어주는 방법이 있을까요?

만약 기능이 없다 하심 로직상에서 포그라운드 변경시마다 맵을 새로 그려주고 기존 마커,오버레이 등을 다시 그려주는 방법을 고려하고 있습니다.

**Comment by note11g** [comment]
해당 이슈는 이 이슈와 관련 있어보입니다: https://github.com/note11g/flutter_naver_map/issues/201
같은 이슈로 판단되어, 이슈를 닫겠습니다. 해당 이슈 채널에서 코멘트 부탁드립니다.
만약, 같은 이슈가 아니라면 다시 이 이슈를 열어주세요. 감사합니다.
