### ISSUE TITLE
[All Platform] fromWidget can On Tap?

### ISSUE THREAD

**Issue by kindkmj** [note11g/flutter_naver_map#216]
fromWidget  으로 오버레이를 그려줄 경우 인터렉션이 불가능하다고 하셧습니다.
유사 혹은 다른 방법을 사용해서 해당 오버레이(마커,폴리곤 등) 에 이벤트를 등록 시키거나 아이디를 반환받는등의 행위를 할 수 있는 방법이 존재할까요?

**Comment by note11g** [comment]
인터렉션이 불가능하다는 의미는, fromWidget으로 사용한 NOverlayImage에 한정된 것입니다. (이미지로 변환 된 것이기 때문에)
따라서, 다른 오버레이와 동일하게 터치 인터렉션 등의 사용은 그대로 가능합니다. 감사합니다.
