### ISSUE TITLE
Marker fromWidget 으로 등록할경우 위젯이 미 표기되는 이슈

### ISSUE THREAD

**Issue by kindkmj** [note11g/flutter_naver_map#218]
```dart
Size size = const Size(37, 48);
await NOverlayImage.fromWidget(
        widget: SizedBox(
                width: size.width+1,
                height: size.height+1,
                child: Stack(
                  children: [
                    Image.asset(
                      'assets/icons/marker/marker_active.png',
                      width: size.width,
                      height: size.height,
                    ),
                    Positioned(
                      top: 11,
                      left: 12.5,
                      child: TextWidget(
                        alignment: Alignment.centerLeft,
                        title: taskListResponse.taskSequence.toString(),
                        textStyleEnum: TextStyleEnum.body16B,
                        color: white,
                      ),
                    ),
                  ],
                ),
              ),
        size: size,
        context: context!,
      );
```
로 표기를 해주려고 했습니다.
![스크린샷 2024-04-05 오후 5 32 53](https://github.com/note11g/flutter_naver_map/assets/41276448/6f04f6ec-1481-4cda-860e-82cfc50da781)

흰 텍스트로 2 라고 표기된게 이미지가 로딩되지? 않은 부분이고 
파란색으로 이미지까지 표기된게 제가 의도한 바 입니다.

따로 에러는 표기되지 않았으며

추측하기로는 await 할때의 데이터가 완료되지 않았지만 widget이 반환됨으로 보여집니다.

**Comment by note11g** [comment]
이미지는 이미지로 만들어서 사용하시는게 맞습니다.
이미지 로드 시간이 걸리기 때문이기도 하며, fromWidget의 경우, 어차피 이미지로 변환되어 사용되기에 굳이 비효율적인 변환을 진행할 필요는 없습니다. 텍스트가 필요하신 경우에는 caption 혹은 subCaption과 캡션의 포지션을 잘 조절하시어 사용하시는 것이 더 좋습니다. 
꼭 필요하시다면, 플러터에서 위젯에 사용되는 이미지를 pre-load 하는 방법을 찾아보시기 바랍니다. 감사합니다.

**Comment by kindkmj** [comment]
감사합니다. 혹시 caption의 포지션을 변경하는게 aligns 랑 offset 말고는 없을까요?
@note11g

**Comment by kindkmj** [comment]
@note11g  pre load 에 아이디어를 얻어 해결했습니다. 감사합니다.
캐쉬에 등록되는 시점문제로 파악되어
캐쉬에 미리 등록이후 사용하는 방법으로 진행했습니다. 감사합니다.
