### ISSUE TITLE
안녕하세요! #195, #212 관련해서 추가 확인 부탁드립니다. 

### ISSUE THREAD

**Issue by ByeongheeKim** [note11g/flutter_naver_map#226]
패키지 잘쓰고 있어서 항상 감사하다고 전하고 싶습니다!

현재 테스트 중인 단말기 정보는 안드로이드14 입니다.

#195 
#212 

관련 이슈글은 읽었는데, 이해가 되지 않는 부분이 있어서 확인 부탁드립니다.

E/FrameEvents(23658): updateAcquireFence: Did not find frame.
E/ImageTextureRegistryEntry(23658): Dropping PlatformView Frame
이 로그가 확인되는데, 

요약하자면, 플러터 자체 이슈이기 때문에,  NaverMapController를 이용하여 updateCamera등의 api를 활용했을 때,
해당 로그가 나타나고 있고, 플러터에 등록하신 내용이 해결되기 전까지는 위 로그가 나타나는게 맞는 걸까요?? 

아니면 1.2.2 버전에서는 위 내용이 해결되었으며, 제가 코드 수정을 잘못해서 나타나는 걸까요?? 

skia 관련 이슈인지, 플랫폼 렌더링 이슈인지, 마이그레이션 관련인지 조금 헷갈려서 이슈 제출 드립니다.

**Comment by note11g** [comment]
해당 이슈는 1.2.2에서 해결되었으며, 제공해주신 에러로그는 Android 플랫폼에서 플랫폼뷰 이용시 나타날 수 있는 현상입니다.
사용상 지장은 없으니 안심하셔도 좋습니다. 감사합니다.
