### ISSUE TITLE
NaverMap() 호출시 오류 발생

### ISSUE THREAD

**Issue by dsdskm** [note11g/flutter_naver_map#228]
/C:/Users/tothe/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_naver_map-1.1.2/lib/src/util/widget_to_image.dart:43:13: Error: No named parameter with the name 'size'.
            size: size, devicePixelRatio: view.devicePixelRatio),
            ^^^^
../../../flutter/flutter/packages/flutter/lib/src/rendering/view.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const ViewConfiguration({
        ^^^^^^^^^^^^^^^^^

**Comment by note11g** [comment]
사용중이신 플러터 버전을 명시해주세요.

**Comment by dsdskm** [comment]
Tools • Dart 3.5.0 (build 3.5.0-100.0.dev) • DevTools 2.35.0-dev.8
입니다~

**Comment by note11g** [comment]
main이나 dev channel 으로 사용하고 계실까요?
@dsdskm

**Comment by note11g** [comment]
#182 와 중복이며, 이는 버그가 아닙니다.
flutter stable 채널을 사용하는 것이 아니라면, 해당 이슈를 트래킹해주세요.
