### ISSUE TITLE
안드로이드 빌드시 flutter_naver_map:compileDebugKotlin 에러

### ISSUE THREAD

**Issue by fbghgus123** [note11g/flutter_naver_map#23]
안드로이드 빌드시 flutter_naver_map:compileDebugKotlin 에러가 발생합니다.
해결 방법 알 수 있을까요?

**Comment by kangmyonggyu** [comment]
저도 동일한 에러가 발생하네요~

**Comment by note11g** [comment]
flutter doctor 결과와 현재 AndroidManifest.xml, 자세한 오류 내용 남겨주시면 오류 파악에 도움될 것 같습니다.
감사합니다.

**Comment by whtjtjddn** [comment]
[에러 내용]
flutter_naver_map-0.10.5/android/src/main/kotlin/map/naver/plugin/net/note11/naver_map_plugin/NaverMapController.kt: (54, 23): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected
'NaverMapFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
----
Manifest
<img width="1328" alt="스크린샷 2022-08-03 오후 6 02 16" src="https://user-images.githubusercontent.com/54929329/182569058-edb8b1c5-0f9a-4859-a00b-5305cd55cfea.png">

**Comment by kangmyonggyu** [comment]
pub yaml 내에 flutter_naver_map 0.10.5 를 해서 받은 library 에 코틀린 버전차이로 인한 null safety 적용 등이 안되어서
발생한 문제로 보입니다.

**Comment by battlecook** [comment]
저도 같은 에러가 발생합니다.

**Comment by Yellowtoast** [comment]
> pub yaml 내에 flutter_naver_map 0.10.5 를 해서 받은 library 에 코틀린 버전차이로 인한 null safety 적용 등이 안되어서 발생한 문제로 보입니다. 원인 파악을 한후 flutter_naver_map: git: https://github.com/wnsgh78b/flutter_naver_map.git 을 pub yaml 파일에 넣은 후 빌드 에러가 사라졌습니다.

무한 감사 드립니다

**Comment by mybloodykeyboard** [comment]
노란토스트님께서 잘 설명해주셨지만 좀 더 자세하게 설명된 링크 남겨드립니다.
https://stackoverflow.com/questions/54022704/how-to-add-a-package-from-github-in-flutter

**Comment by note11g** [comment]
1.0 Stable 업데이트 이후, 해결해보도록 노력하겠습니다.
감사합니다.

**Comment by note11g** [comment]
[0.10.7](https://pub.dev/packages/flutter_naver_map/versions/0.10.7) 에서 수정되었습니다.
감사합니다.
