### ISSUE TITLE
ViewConfiguration 파라미터 오류

### ISSUE THREAD

**Issue by user71309876** [note11g/flutter_naver_map#231]
lib/src/util/widget_to_image.dart의 42번째줄에서 ViewConfiguration 클래스를 호출하는 과정에서 파라미터가 잘못되었습니다.
최신 플러터 코드를 보니 ViewConfiguration 클래스의 생성자 파라미터가 변경되었습니다.
이점 유의해서 업데이트 해주셔야 될 것 같습니다.

**Comment by user71309876** [comment]
해결되었습니다
혹시 저와 같은 문제를 가지신 분이 계시면
[https://github.com/users/note11g/projects/2/views/2?pane=issue&itemId=53121840](url)
를 참고하세요

**Comment by note11g** [comment]
#182 와 중복이며, 이는 버그가 아닙니다.
flutter stable 채널을 사용하는 것이 아니라면, 해당 이슈를 트래킹해주세요.
