### ISSUE TITLE
iOS에서 마커 addOverlay 지연증상 및 visible region

### ISSUE THREAD

**Issue by dreamofmidge** [note11g/flutter_naver_map#232]
안녕하세요~!
지도 패키지 만들어주셔서 항상 감사하게 생각하고 있습니다 :)

제가 마커 객체를 미리 만들어놓고, 아래 코드를 이용해 필요할때마다 마커를 지도에 addOverlay 해주고 있습니다.
마커 갯수는 많을때 1만 5천개 정도 됩니다.
안드로이드에서는 마커가 표시되는데 1,2초 밖에 안걸리는데.
아이폰에서는 마커가 표시되는데 14,15초가 걸리네요ㅠㅠ
혹시 어떤 이유인지 알 수 있을까요?

`mapController.clearOverlays(type: NOverlayType.marker);
 for (NMarker marker in markers) {
        mapController.addOverlay(marker);
}
`

이러한 문제로 보이는 영역(visible region)에 해당하는 마커만 addOverlay 해주려고 하는데.
혹시 구글맵처럼 
`bounds = getVisibleRegion();
bounds.contains(marker.position);
`
위와 같은 코드로 현재 보이는 영역에 마커가 존재하는지 판단하는 기능이 있을까요?

**Comment by note11g** [comment]
안녕하세요. 바빠서 간략히만 답변 남겨드리자면, for문을 사용하시면 성능 하락이 있습니다.
addOverlayAll(Set<AddableOverlay> overlays) 메서드를 대신해서 사용하세요. 
자세한 내용은 문서와 API reference를 확인해보세요. 감사합니다.

**Comment by note11g** [comment]
두번째는 동일하게 존재합니다.

링크 남겨드리니 참고하세요.

https://pub.dev/documentation/flutter_naver_map/latest/flutter_naver_map/NaverMapController/getContentBounds.html

https://pub.dev/documentation/flutter_naver_map/latest/flutter_naver_map/NLatLngBounds/containsPoint.html

**Comment by dreamofmidge** [comment]
오 지금 당장 해보겠습니다!
패키지 너무 잘쓰고 있습니다!
항상 감사합니다!

**Comment by dreamofmidge** [comment]
매우 잘됩니다! 감사합니다!
