### ISSUE TITLE
Flutter v3.22.0 버전에서 ViewConfiguration 생성자 interface 가 변경됨

### ISSUE THREAD

**Issue by seunghonice** [note11g/flutter_naver_map#233]
발생 Naver Map SDK 버전: flutter_naver_map-1.2.2
Flutter 버전: v3.22.0

https://github.com/note11g/flutter_naver_map/blob/6559784935d80312e20e47c70aeb57def33b1909/lib/src/util/widget_to_image.dart#L43

``` dart
ViewConfiguration(size: size, devicePixelRatio: view.devicePixelRatio)
```
해당 생성자가 변경되어 Build 되지 않습니다.

**Comment by rambozzang** [comment]
ViewConfiguration(size: size, devicePixelRatio: view.devicePixelRatio) 을 아래와 같이 변경하니 잘되네요. 
참고하세요.

ViewConfiguration(
            physicalConstraints: BoxConstraints.tight(size),
            logicalConstraints: BoxConstraints.tight(size),
            devicePixelRatio: view.devicePixelRatio),

**Comment by seunghonice** [comment]
@rambozzang 
변경하면 되는건 알지만, 다음 버전에 fix 될 수 있도록 보고드렸습니다 ~
감사합니다 :)
