### ISSUE TITLE
Flutter 3.22.0 호환 안됨

### ISSUE THREAD

**Issue by yoojin282** [note11g/flutter_naver_map#234]
이번 flutter 3.22.0 버전이 호환이 안되네요.

확인 부탁드립니다.

**Comment by SeunghoHong-kurly** [comment]
https://github.com/note11g/flutter_naver_map/issues/233

**Comment by seunghonice** [comment]
https://github.com/note11g/flutter_naver_map/issues/233

**Comment by note11g** [comment]
선행작업: #182
