### ISSUE TITLE
1.3.0 버전 출시 일자 문의

### ISSUE THREAD

**Issue by WTPENGUIN** [note11g/flutter_naver_map#235]
2주 전 Preview 버전이 먼저 출시 되는 것으로 안내가 되었지만, 아직 출시 되지 않은 것으로 보입니다.

혹시 정식 1.3.0 버전 출시 일자나 Preview 버전 출시 일정이 어떻게 되나요?

**Comment by note11g** [comment]
안녕하세요, 1.3.0에 대한 테스트 및 배포가 늦어져 죄송스러울 따름입니다.
현재 본업때문에 잠시 여유가 없어서, 이번 주말이 지나야 다시 손댈 수 있을 것 같습니다.
이후에 여유 나는대로 소식을 여기 이슈에 업데이트 하도록 하겠습니다. 감사합니다.

**Comment by note11g** [comment]
일단, 1.2.2에 대한 플러터 3.22 대응 버전은 업데이트 완료하였습니다.
하지만, 1.3.0에 들어갈 추가 사항은 아직 작업이 완료되지 않았습니다.

현재 진행중인 사항은 클러스터링 iOS 대응 설계 변경 작업입니다. (2주가량 중단됨)
이 작업이 끝나야, Flutter에 노출되는 API를 확정지을 수 있기에, 작업 후에 공개하도록 할 예정입니다.

6월 초에 다시한번 경과를 알려드리도록 하겠습니다. 감사합니다.

**Comment by note11g** [comment]
다음주 말 부터는 작업을 재개할 수 있을 것 같습니다.
감사합니다.

**Comment by note11g** [comment]
#260 에서 작업 내용을 트래킹하실 수 있습니다.
해당 이슈는 내용이 중복되는 것을 방지하기 위해 우선 미해결로 닫도록 하겠습니다.
감사합니다.
