### ISSUE TITLE
TrackingMode face의 AOS, IOS 베어링 이슈

### ISSUE THREAD

**Issue by Gandarlpu** [note11g/flutter_naver_map#240]
안녕하세요. trackingMode의 face옵션에 대해 

제공해주신 라이브러리의 example에서 빌드하여 테스트 중 다음과 같은 현상을 발견했습니다.

AOS
https://github.com/note11g/flutter_naver_map/assets/49300186/9a3a809b-26bc-4fb1-b62a-ec533f52cee3

IOS
https://github.com/note11g/flutter_naver_map/assets/49300186/386415cb-4619-49fa-9f02-8fd23904b290

안드로이드 기기 정보
- 모델명 : A13
- Android version : 14

아이폰 기기 정보
- 모델명 : iPhone 7
- ios Version : 15.6.1

**Comment by note11g** [comment]
#42 이슈와 중복인 것으로 보입니다.
[코멘트](https://github.com/note11g/flutter_naver_map/issues/42#issuecomment-1477325529)를 참고해주세요.
만약, 다른 이슈인 것 같다면 다시 이슈를 열고 더 자세한 코멘트를 남겨주세요. 감사합니다.
