### ISSUE TITLE
ios pod NMapsMap 라이브러리 의존성 주입 이슈 보고

### ISSUE THREAD

**Issue by The-Join** [note11g/flutter_naver_map#241]
안녕하세요

현재 1.2.2 버전에서 pod install시 NMapsMap 3.17.0에 대한 라이브러리를 찾을 수 없는 에러가 발생합니다.
에러본문은 다음과 같습니다.

[!] Error installing NMapsMap
[!] /usr/bin/unzip /var/folders/p5/by3sqxqn3cn_756gjkkyywsm0000gn/T/d20240624-91583-p2edhn/file.zip -d /var/folders/p5/by3sqxqn3cn_756gjkkyywsm0000gn/T/d20240624-91583-p2edhn

Archive:  /var/folders/p5/by3sqxqn3cn_756gjkkyywsm0000gn/T/d20240624-91583-p2edhn/file.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/p5/by3sqxqn3cn_756gjkkyywsm0000gn/T/d20240624-91583-p2edhn/file.zip or
        /var/folders/p5/by3sqxqn3cn_756gjkkyywsm0000gn/T/d20240624-91583-p2edhn/file.zip.zip, and cannot find /var/folders/p5/by3sqxqn3cn_756gjkkyywsm0000gn/T/d20240624-91583-p2edhn/file.zip.ZIP, period.

현재 flutter_naver_map.podspec에 명시된 NMapMap 라이브러리 버전을 3.17.0 -> 3.18.0으로 직접 수정하여 
pod install시 해결됨을 확인했으며 빌드 후 기본적인 기능에 대하여 정상작동 되는 것을 확인하였습니다. 

기존 3.17.0을 그대로 사용하실 경우 NMapsMap-Legacy를 이용하셔야 할 것 같습니다.

버전에 대한 내용의 링크는 아래를 참조 부탁드립니다.

https://navermaps.github.io/ios-map-sdk/guide-ko/1.html

**Comment by JangJuMyeong** [comment]
윗분이 말씀하신 방법을 모르시는 분들께 도음을 드리고자 

cd .symlinks/plugins/flutter_naver_map/ios
nano flutter_naver_map.podspec

하셔서 하단에 NMapsMap 버전 3.17.0버전인걸 3.18.0버전으로 수정하면 됩니다.

**Comment by note11g** [comment]
해당 마이그레이션은 #207 에서 트래킹하실 수 있습니다.
