### ISSUE TITLE
Naver map SDK의 maven 저장소가 변경됨

### ISSUE THREAD

**Issue by hyunkyoung-jung** [note11g/flutter_naver_map#242]
https://www.ncloud-forums.com/topic/284/

위 토픽에 따르면, 
5월 31일부터는 기존의 jfrog 저장소를 사용할 수 없다고 합니다!!

저장소 링크 변경 및 3.18.0 버전으로의 업데이트가 필요해 보입니다

**Comment by The-Join** [comment]
임시 해결책은 flutter_naver_map 라이브러리의 gradle에 명시된 url을

- 기존: https://naver.jfrog.io/artifactory/maven/
- 변경: https://repository.map.naver.com/archive/maven

변경하는 것입니다.
이전 글에서 ios에 대해서만 말씀 드렸지만 aos도 동일하네요
해당 부분에 대하여 업데이트 부탁드리며

안되시는 사용자 분들은 임시로 위의 변경사항을 적용하여 사용해야할 것 같습니다.

**Comment by note11g** [comment]
해당 마이그레이션은 #207 에서 트래킹하실 수 있습니다.
