### ISSUE TITLE
seoulCityHall이 존재하지 않음

### ISSUE THREAD

**Issue by teacherSsamko** [note11g/flutter_naver_map#247]
https://github.com/note11g/flutter_naver_map/blob/3ee423b91922ca43c5ee7d9b98ea2a726c425313/lib/src/type/map/map_options.dart#L179

seoulCityHall 변수가 존재하지 않습니다.

**Comment by note11g** [comment]
https://github.com/note11g/flutter_naver_map/blob/3ee423b91922ca43c5ee7d9b98ea2a726c425313/lib%2Fsrc%2Ftype%2Fmap%2Fmap_options.dart#L336-L336

해당 라인에 존재합니다! 확인 부탁드릴게요!

**Comment by teacherSsamko** [comment]
엇, 그러네요 
왜 못 찾았죠.. 😂 닫겠습니다. 번거롭게 해드려 죄송해요 🥲

**Comment by note11g** [comment]
> 엇, 그러네요 왜 못 찾았죠.. 😂 닫겠습니다. 번거롭게 해드려 죄송해요 🥲

괜찮습니다:) 좋은 하루 되시길 바라겠습니다!
