### ISSUE TITLE
마커 크기가 OS에 따라 차이가 있습니다

### ISSUE THREAD

**Issue by TMSeo23** [note11g/flutter_naver_map#249]
라이브러리를 잘 사용하고 있습니다 
마커 사용시 iOS와 AOS에서 마커사이즈에 차이가 있습니다. 
NOverlayImage.fromAssetImage을 사용하여 동일한 이미지를 사용하고 있습니다. 

크기 조정을 위해 NOverlayImage.fromWidget 사용시 
[ImageSaveUtil] 이미 저장된 이미지입니다. 저장된 path를 반환합니다. 
로그가 발생하며, 앱이 느려집니다. 

<img width="446" alt="Screenshot 2024-07-12 at 11 46 17" src="https://github.com/user-attachments/assets/6165644a-6d50-43fc-8a25-cff03ddd0304">

asset 이미지는 flutter_gen_runner 를 이용하여 사용하고 있습니다. 

감사합니다!

**Comment by note11g** [comment]
안녕하세요, 해당 현상을 확인하기 위해 좀 더 구체적인 재현 환경과 스크린샷을 부탁드리겠습니다.

**Comment by TMSeo23** [comment]
재현 환경 :
[example](https://github.com/note11g/flutter_naver_map/tree/main/example)
example 파일로 테스트 했을 때에도 동일한 증상이 있습니다. 

테스트 기기:
안드로이드 14 
iOS 16.7 (다른 버전도 동일한 증상 발견) 

![AOS](https://github.com/user-attachments/assets/4c562ebb-9415-4dae-8146-6414d0cdd7b6)
![iOS](https://github.com/user-attachments/assets/96c5ae3c-a94f-4553-8884-276f919b18c9)

서비스 UI가 있어 동일한 비율로 스샷 수정했습니다. 

사용한 marker file: 
![location](https://github.com/user-attachments/assets/bfc1f9fe-643b-479e-bfd5-a69c1ae4caae)

감사합니다!
