### ISSUE TITLE
지도 확대/축소 제스처 및 여러가지 질문

### ISSUE THREAD

**Issue by ehdwldk7400** [note11g/flutter_naver_map#250]
혹시 API나 찾아봐도 안보여서요!
1.zoom 확대 제스쳐에 PC/Mobile Web처럼 딱딱 정확하게 끊기도록 설정하는 방법은 없을까요??
2. 로케이션 버튼은 위치조정을 못하는걸까요??
3. 안드로이드에서 
       NOverlayImage.fromWidget(
                  widget: _getMarker(id, params.map),
                  size: Size(40.h, 40.h),
                  context: context,
                ).then((icon) => e..setIcon(icon));
으로 marker 사용 중에 _getMarker에서 widget을 만들어주는데 폰트 크기가 안드로이드 스시템 폰트 크기에 영향을 받는데 안받도록 설정이 가능할까요??

**Comment by ehdwldk7400** [comment]
3번은 자답입니다!

return MediaQuery(
data: const MediaQueryData(textScaler: TextScaler.noScaling),
child: Container(),
);
로 해결했습니다!

**Comment by note11g** [comment]
1번은 정확하게 끊기게 하신다는게 아마, 제스처를 놓았을 때 일정단위로 (ex: 16->17) 끊어지게 만들고 싶다는 말씀이신 것 같은데, onCameraChange에서 gesture Camera Changing을 취소해주시고 그 다음 원하는 레벨로 이동하도록 하면 되지 않을까 싶긴 합니다.

2번은 곧 플러터 위젯으로 변경하며 가능하도록 지원 예정입니다. (#173)

3번은 잘 해주신 것 같습니다.

감사합니다. 더 궁금하신 점이 있으시다면 이슈를 다시 열고 코멘트를 남겨주세요!
