### ISSUE TITLE
[iOS] XcodeCloud 빌드 시 Could not resolve host 에러 발생

### ISSUE THREAD

**Issue by seunghonice** [note11g/flutter_naver_map#254]
<img width="994" alt="image" src="https://github.com/user-attachments/assets/5a011d17-7339-4bce-b5da-33b0e1047cf1">

XcodeCloud 를 통해 테스트앱을 배포하고 있습니다.
금요일? 부터 XcodeCloud 를 통해 빌드하게 되면 위 스크린샷과 같은 에러가 발생합니다.
로컬환경에서는 빌드가 잘 됩니다.

혹시 해당 이슈 트러블슈팅 하신 사례 있으면 공유 부탁드리며, @note11g 확인 부탁드립니다. :)

플러그인 버전은 v.1.2.3+1 입니다.

**Comment by note11g** [comment]
안녕하세요, 해당 이슈는 라이브러리 버전을 최신버전(1.2.3)으로 바꾸시면 해결되는 이슈인 것으로 보입니다.
업그레이드 후에도 동일한 이슈가 지속된다면, 이슈를 다시 열고 코멘트를 남겨주세요. 감사합니다.
