### ISSUE TITLE
NOverlayImage.fromWidget 동작 안되는 이슈

### ISSUE THREAD

**Issue by drg2533** [note11g/flutter_naver_map#255]
안녕하세요. 먼저 네이버맵 sdk제작에 큰 감사드립니다.

NOverlayImage.fromWidget 을 사용해서 위젯을 마커로 사용할때 이상현상이 있습니다.
svg파일 두개를 stack으로 겹쳐서 위젯을 만들고 해당 위젯을 마커로 사용하고 있는데 run 모드에서는 정상적으로 마커가 보입니다
그런데 release모드로 실행하면 두 svg파일중 특정 svg파일은 마커에서 보이지 않는 현상이 나타나고 있습니다.

기본 마커의 배경으로 svgString으로 사용하고 api콜을 통해 마커에 사용할 svg파일을 가져오고 있습니다.
그런데 정작 나타나지 않는건 하드코딩으로 입력한 svg가 안나타나고 있습니다
(svg파일, png파일, svgString 전부 동일하게 해당 마커만 release모드에서 안나타나고 있습니다.)
해당 파일외 여러가지 이미지도 시도해보았는데 나타나는 이미지도 있고 안나타나는 이미지도 있습니다

아래는 제가 사용한 코드입니다.

final partnerInfo = await PartnerService.getLogoPartner('pnesystems');
        // final partnerInfo = await PartnerService.getLogoPartner(partner.partnerId);
        final svgString = await http.read(Uri.parse(partnerInfo.logo));
        final activeString = '''<svg width="39" height="46" viewBox="0 0 39 46" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M32.5696 6.2794C30.798 4.50778 28.6947 3.10245 26.38 2.14366C24.0653 1.18487 21.5843 0.691396 19.0789 0.691406C14.0189 0.691426 9.16608 2.70153 5.5881 6.27951C2.01012 9.85749 2.00711e-05 14.7103 1.5306e-10 19.7703C-1.00353e-05 22.2757 0.493465 24.7567 1.45225 27.0714C2.41104 29.3862 3.81637 31.4894 5.58799 33.261L16.3805 44.0535C17.0961 44.7691 18.0667 45.1711 19.0787 45.1711C20.0907 45.1711 21.0612 44.7691 21.7768 44.0535L32.5695 33.2609C34.3411 31.4893 35.7465 29.386 36.7053 27.0713C37.6641 24.7565 38.1576 22.2756 38.1576 19.7701C38.1576 17.2647 37.6641 14.7837 36.7053 12.469C35.7465 10.1542 34.3412 8.05102 32.5696 6.2794Z" fill="#2962FF"/>
<circle cx="19" cy="19.6914" r="16" fill="white"/>
</svg>
''';
        final inactiveString = '''<svg width="40" height="45" viewBox="0 0 40 45" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M33.4893 5.69249C31.7176 3.92086 29.6144 2.51554 27.2997 1.55675C24.9849 0.59796 22.504 0.104482 19.9985 0.104492C14.9385 0.104512 10.0858 2.11461 6.50778 5.69259C2.9298 9.27058 0.919698 14.1233 0.919678 19.1834C0.919668 21.6888 1.41314 24.1698 2.37193 26.4845C3.33072 28.7992 4.73605 30.9025 6.50767 32.6741L17.3002 43.4666C18.0158 44.1822 18.9864 44.5842 19.9984 44.5842C21.0104 44.5842 21.9809 44.1822 22.6965 43.4666L33.4892 32.674C35.2608 30.9023 36.6661 28.7991 37.6249 26.4844C38.5838 24.1696 39.0772 21.6887 39.0773 19.1832C39.0773 16.6777 38.5838 14.1968 37.625 11.8821C36.6662 9.56734 35.2609 7.46411 33.4893 5.69249Z" fill="#9EA5AD"/>
    <circle cx="19.9197" cy="19.1045" r="16" fill="white"/>
</svg>''';

        double size = 50;

        final marker = Stack(
          children: [
            Positioned.fill(
              // child: SvgPicture.string(activeString),
                child: Container(width: 30, height: 30, color: Colors.yellow,)
            ),
            Positioned(
                top: 0,
                left: 20 * size / 100,
                right: 20 * size / 100,
                bottom: 15 * size / 100,
                child: Align(
                    alignment: Alignment.topCenter,
                    child: SvgPicture.string(
                      svgString,
                      width: double.infinity,
                    ))),
          ],
        );

        final offMarker = Stack(
          children: [
            Positioned.fill(
              // child: Image.asset(Assets.carsAudi),
              child: SvgPicture.string(inactiveString),
              // child: Container(width: 30, height: 30, color: Colors.yellow,)
            ),
            Positioned(
                top: 0,
                left: 20 * size / 100,
                right: 20 * size / 100,
                bottom: 15 * size / 100,
                child: Align(
                    alignment: Alignment.topCenter,
                    child: SvgPicture.string(
                      svgString,
                      width: double.infinity,
                    ))),
          ],
        );

        markersLogo.add({
          'partnerId': partner.partnerId,
          'marker': await NOverlayImage.fromWidget(widget: marker, size: Size(size, size), context: Get.context!),
          'offMarker': await NOverlayImage.fromWidget(widget: offMarker, size: Size(size, size), context: Get.context!)
        });

**Comment by note11g** [comment]
안녕하세요, 해당 이슈는 중복으로 판단됩니다.
다음은 권장되는 답변들의 링크입니다. 참고하시기 바랍니다.
https://github.com/note11g/flutter_naver_map/issues/218#issuecomment-2041435215
https://github.com/note11g/flutter_naver_map/issues/221#issuecomment-2055857474
다른 이슈라고 생각되신다면, 다시 이 이슈를 열어주세요. 감사합니다.
