### ISSUE TITLE
[Fatal Error] map-sdk-3.17.0.pom:2:10: doctype이 이미 표시되었습니다.

### ISSUE THREAD

**Issue by YOGIGOMA** [note11g/flutter_naver_map#257]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.1, on macOS 14.6.1 23G93 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.1)
[✓] Connected device (4 available)
[✓] Network resources

현재 flutter_naver_map: 1.1.2를 사용하고 있었습니다. 앱 기능 업데이트를 위해서 빌드 및 실행을 하면 아래와 같은 오류가 출력됩니다. 

[Fatal Error] map-sdk-3.17.0.pom:2:10: doctype이 이미 표시되었습니다.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.naver.maps:map-sdk:3.17.0.
     Required by:
         project :app > project :flutter_naver_map
      > Could not resolve com.naver.maps:map-sdk:3.17.0.
         > Could not parse POM https://naver.jfrog.io/artifactory/maven/com/naver/maps/map-sdk/3.17.0/map-sdk-3.17.0.pom
            > doctype이 이미 표시되었습니다.

해결방안을 제시해 주면 감사하겠습니다.

**Comment by note11g** [comment]
최신버전(1.2.3+1)을 사용해보시기 바랍니다. 감사합니다.

**Comment by duc1205** [comment]
hi @note11g 1.2.3+1 not support flutter 3.16.9.
