### ISSUE TITLE
Prepare v1.3.0

### ISSUE THREAD

**Issue by note11g** [note11g/flutter_naver_map#260]
## 현재 상태
- Beta Released: https://pub.dev/packages/flutter_naver_map/versions/1.3.0-beta.3

## 진행중인 작업
**Now working Issues**
- [x] #207 
  - [x] #224 : Done(done at 09.17)
- Additional TODO
  - [x] Android 3.19.1 SDK (e4de2e6)
  - [x] iOS 3.19.1 SDK (e4de2e6)

Beta Release 이후
- [ ] 테스트 코드 작성
    
### 일정
- Beta Release ~~2024.08.29~~ -> 2024.09.18
- Release ~~2024.08.31~~ -> 2024.09월 중

### ETC
- 작업 재개 날짜: 2024.08.15
[see working branch](https://github.com/note11g/flutter_naver_map/tree/dev/1.3.0)

**Comment by ParkJunSoung** [comment]
작업 마무리 날짜가 변경된게있나요?

**Comment by note11g** [comment]
Additional TODO
- Android 3.19.1 SDK
- iOS 3.19.1 SDK

**Comment by note11g** [comment]
베타버전 릴리즈 되었습니다: https://pub.dev/packages/flutter_naver_map/versions/1.3.0-beta.2
