### ISSUE TITLE
[iOS] flutter run 시 빌드 에러 

### ISSUE THREAD

**Issue by mungyuchoi** [note11g/flutter_naver_map#262]
================================================================
Error (Xcode): ../../.pub-cache/hosted/pub.dev/flutter_naver_map-1.2.2/lib/src/util/widget_to_image.dart:43:13: Error: No named parameter with the name 'size'.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
================================================================

https://github.com/note11g/flutter_naver_map/issues/241
위의 이슈로 3.18.0 으로 변경 후에 다시 빌드 하였더니 위와 같이 에러가 발생하는데요 .
어떻게 수정해야 하나요?

**Comment by note11g** [comment]
안녕하세요. 패키지의 버전을 최신버전 1.2.3으로 올리시거나, 1.2.2+flutter3.18 버전으로 호환되도록 진행하시면 됩니다. 감사합니다:)

**Comment by mungyuchoi** [comment]
감사합니다~!
flutter upgrade도 해줘야하는군요. 
덕분에 해결하였습니다~!
