### ISSUE TITLE
곡선 path를 그리는 기능이 지원되나요?

### ISSUE THREAD

**Issue by theflan-leech** [note11g/flutter_naver_map#263]
안녕하세요.
맵에 곡선 오버레이를 그리고 싶은데 해당 기능이 제공되는지 궁급합니다.
개발 하고자하는 기능은 아래와 같습니다.

![IMG_5060](https://github.com/user-attachments/assets/076c93b6-af86-4a3e-be36-8528d1257a5d)

**Comment by note11g** [comment]
안녕하세요.
아쉽게도 해당 기능이 따로 제공되지는 않으며, 대신 pathOverlay를 사용하시어 곡선상의 좌표들을 촘촘하게 이어 사용하실 수는 있습니다.
감사합니다.
