### ISSUE TITLE
    onCameraChange: (position, reason) {},

### ISSUE THREAD

**Issue by GlennJung** [note11g/flutter_naver_map#264]
기존에 0.10.xx를 쓰고 있다가 1.2.3으로 업데이트했는데요..
기존에는 onCameraChange에 position이 있었는데 없어졌는데,
어떤식으로 샘플을 사용해야 동일하게 동작하게 할수 있을까요?

**Comment by note11g** [comment]
[NaverMapController.nowCameraPosition](https://pub.dev/documentation/flutter_naver_map/latest/flutter_naver_map/NaverMapController/nowCameraPosition.html)을 확인해보시기 바랍니다. 감사합니다.
