### ISSUE TITLE
클러스터링 기능 구현 일정에 관해 드릴 질문이 있습니다.

### ISSUE THREAD

**Issue by tkddbf7348** [note11g/flutter_naver_map#265]
안녕하세요 개발자님. 편리한 기능을 잘 구현해주셔서 감사히 쓰고 있습니다. 바쁘신 와중에 좋은 라이브러리 만들어주셔서 감사합니다.

클러스터링 기능 추가가 포함된 버전을 적용하고 싶은데, 

이슈들을 보니 구현 완료를 8월 말로 예상하셨지만 아직 구현 중이신 듯 해서,

예정 릴리즈 날짜를 어느 정도로 생각하고 계신지 궁금합니다.

**Comment by note11g** [comment]
안녕하세요, 많이 늦어진 점 사과드립니다.
Android View쪽 이슈가 해결이 계속 안되어 미루어졌는데, 방금 Android 쪽은 커밋내역 푸시 완료했습니다.
자세한 일정은 #260 을 확인해주세요!
