### ISSUE TITLE
NInfoWindow 커스텀 디자인

### ISSUE THREAD

**Issue by elenaseo05** [note11g/flutter_naver_map#272]
안녕하세요. 

사용자 정의 정보 창 혹은 정보 창 디자인 스타일 옵션 조정 가능할까요? 

라이브러리 잘 사용하고 있습니다. 감사합니다.

**Comment by note11g** [comment]
아쉽게도 해당 기능은 제공하고 있지 않습니다.
대신, `NaverMapController`의 지도 위경도 <-> 화면 위치를 서로 변경할 수 있는 api를 사용하여 flutter의 overlay로 해당 기능을 구현할 수 있습니다.
[해당 문서](https://pub.dev/documentation/flutter_naver_map/latest/flutter_naver_map/NaverMapController/latLngToScreenLocation.html)를 확인해보세요. 감사합니다.
