### ISSUE TITLE
gradle 8.7 로 android 빌드 시 오류

### ISSUE THREAD

**Issue by Sungrinhan** [note11g/flutter_naver_map#279]
에러내용 : 
flutter_naver_map-1.3.0+1/android/src/main/kotlin/dev/note11/flutter_naver_map/flutter_naver_map/view/NaverMapView.kt:134:29 Unresolved reference: style

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_naver_map:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

flutter doctor 실행 시:
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.0.1 24A348 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.6)
[✓] VS Code (version 1.94.2)   
   

각 버전
naver map version : 1.3.0+1
gradle : 8.7
ndkVersion "26.1.10909125"
ext.kotlin_version = '1.9.0'

**Comment by ksehoseho** [comment]
안녕하세요.
저도 네이버 맵을 이번에 업데이트 하니 동일한 문제가 발생하고 있습니다.
NaverMapView.kt:134
로컬 피씨에 저장된 위 파일을 열고 134 라인의 스타일 테마 적용하는 부분을 주석처리 하면 빌드가 되기는 합니다.

**Comment by Sungrinhan** [comment]
> 안녕하세요. 저도 네이버 맵을 이번에 업데이트 하니 동일한 문제가 발생하고 있습니다. NaverMapView.kt:134 로컬 피씨에 저장된 위 파일을 열고 134 라인의 스타일 테마 적용하는 부분을 주석처리 하면 빌드가 되기는 합니다.

네, 해당부분은 확인했습니다. 근본적인 해결은 안되어서 이슈 남겼습니다 ㅎㅎ 
이거 덕분에 gradle, agp 환경설정에대해 많이 보게 되었네요.
