### ISSUE TITLE
final void Function()? onCameraIdle; 에 대한 질문이지만 오류상태일수도 있을거 같아서 남겨드립니다.

### ISSUE THREAD

**Issue by ByeongheeKim** [note11g/flutter_naver_map#282]
final void Function()? onCameraIdle; 을 이용해서 카메라 이동이 멈췄을 때, 주소를 갱신하는 이벤트를 사용중인데, 해당 이벤트가 옵저빙상태에 걸린 것 처럼 계속 결과를 반환하고 있어서 올리게 됐습니다.

 /// 카메라가 완전히 멈추었을 때, 실행 되는 함수입니다.
  /// 매 카메라 이동마다 [onCameraChange] 다음에 한번만 실행됩니다.
  final void Function()? onCameraIdle;

이 설명에 의하면 카메라가 멈춰있는데도 onCameraChange 가 해당 옵저빙 상태여서 덩달아서 onCameraIdle이 반환되고 있는 것일까요?? 아니면 onCameraIdle 자체가 옵저빙 상태여서 계속 이벤트가 반복되는 것일까요?? 

오류가 아니라면
onCameraIdle
onCameraChange 의 의도된 동작을 알려주시면 감사하겠습니다!

**Comment by note11g** [comment]
안녕하세요, 해당 현상은 의도된 현상은 아닌 것으로 보입니다.

현재 어떤 이유에서 움직이고 있는지 onCameraChange 메서드가 업데이트 되는 중인지 여부와 reason을 확인하시고, 그래도 원인을 찾지 못하셨다면 최소 재현 코드를 남겨주세요. 증상 재현에 도움이 될 것 같습니다.

**Comment by ByeongheeKim** [comment]
감사합니다! 의도된 현상 아니라는 답변 받고 확인 결과 카메라 움직임에 따라 아이콘 색상을 변화시키려고 지역변수로 setstate 걸어둔 부분때문에 나타난 현상이었습니다. 전역변수로 옮긴 이후로 해당 현상은 사라졌습니다.

**Comment by note11g** [comment]
아이콘 색상 변경에는 따로 setState가 필요하지 않습니다! 혹시 다른 용도로 사용중이신 게 아니라면 제외하여 성능 최적화를 진행하실 수도 있을 것 같습니다. 해결하셔서 다행입니다. 좋은 저녁되세요:)
