### ISSUE TITLE
네이버 맵 infoWindow 커스텀 방법..

### ISSUE THREAD

**Issue by suchul** [note11g/flutter_naver_map#3]
안녕하세요 네이버 맵을 검토 중입니다만 
마커에 텍스트 및 박스를 커스텀 하고자 하는데 
infoWindow 을 커스텀 할수 있는지요? 
문의 드립니다

**Comment by note11g** [comment]
https://navermaps.github.io/android-map-sdk/guide-ko/5-3.html
정보창(InfoWindow)는 Native SDK에서도 String 값 변경만 가능하여 텍스트 커스텀 이외의 기능은 지원하고 있지 않습니다.

flutter_naver_map 패키지에서는 Marker를 통한 InfoWindow 열기만 지원하고 있습니다만, 요청해주신다면 기능 추가는 가능합니다.
저희 패키지에 관심 가져주셔서 감사합니다.

**Comment by suchul** [comment]
혹시 마커에 화면에 실제 위치를 알수 있을런지요? infowindow를 못한다면 마커에 display 좌표를 알아야 하는데 그게 Anchor같은데 그값을 리턴 못받는거 같아서요 가능 한지요?

**Comment by note11g** [comment]
@suchul 
네이버 맵 안드로이드 SDK에서 해당 기능을 지원하는지 여부를 찾지 못하겠습니다 ㅠㅠ
혹시 링크 부탁드려도 될까요?

**Comment by note11g** [comment]
@suchul 일단 이슈가 아니어보이므로 Close 하겠습니다.
언제든 다시 Open 해주셔도 됩니다. 감사합니다.

**Comment by note11g** [comment]
https://github.com/note11g/flutter_naver_map/blob/e1ca22e20b7d805971dad69e69e2c9844ef543c5/example/lib/pages/examples/overlay_example.dart#L28-L36

비슷한 기능의 구현은 1.0 버전 예제에서 확인하실 수 있습니다.
