### ISSUE TITLE
지도 사용 시 권한 요청 팝업을 띄우지 않는 방법.

### ISSUE THREAD

**Issue by dylan-kwon** [note11g/flutter_naver_map#4]
현재 지도 위젯을 사용하기만 해도 위치 관련 권한을 요청하는 팝업이 나오고 있는 것 같습니다.
필요할 때만 권한을 요청할 수 있도록 하는 방법이 있나요?

**Comment by note11g** [comment]
`initLocationTrackingMode` 속성이 `LocationTrackingMode.None`이 아닐경우, 위치를 추적하도록 되어 있습니다.
기본 값이 추적을 허용하는 `LocationTrackingMode.NoFollow` 이므로, 한번 옵션을 확인해보시길 부탁드려도 될까요?


[initLocationTrackingMode API Docs 바로가기](https://pub.dev/documentation/flutter_naver_map/latest/flutter_naver_map/NaverMap/initLocationTrackingMode.html)

**Comment by dylan-kwon** [comment]
원하는 대로 동작합니다.
감사합니다.
