### ISSUE TITLE
Marker Size 이상

### ISSUE THREAD

**Issue by sangeunA** [note11g/flutter_naver_map#44]
Marker Icon에 OverlayImage fromByteArray(Uint8List byteArray) 를 통해서 띄우려고하면
Android 에서는 원하는대로 정상적으로 나타나고,
IOS 에서는 MediaQuery.of(context).devicePixelRatio  (Device의 Ratio) 가 곱해진 상태로  띄워져서 엄청 크게나오고 있는것 같습니다.

**Comment by sangeunA** [comment]
flutter_naver_map: ^0.10.7    입니다!

**Comment by note11g** [comment]
0.10.7 버전은 해당 동작이 정상입니다. android에서는 px단위로, iOS에서는 logical pixel(pt) 단위로 사이즈가 정해지기 때문입니다.
1.0 버전에서는 모두 동일하게 logical pixel을 사용하므로, 번거로우시겠지만 1.0 버전을 사용하시는 것을 권장드립니다.

추가적인 문의사항이 있으신 경우에는,  다시 이슈를 오픈해주시면 됩니다. 감사합니다.
