### ISSUE TITLE
NaverMapViewOptions에서 logoClickEnable 옵션 적용이 안되는 현상

### ISSUE THREAD

**Issue by KangJuO** [note11g/flutter_naver_map#45]
사용 버전: 1.0.0-dev.5

버그 내용: 
 - NaverMapViewOptions에서 logoClickEnable: false 옵션으로 사용시
 옵션 적용이 되지 않고 로고 클릭시 팝업이 표시되는 현상

버그 재현: NaverMapViewOptions에서 logoClickEnable 옵션 true, false 비교

**Comment by note11g** [comment]
@KangJuO 사용중이신 플랫폼 정보도 부탁드립니다.

**Comment by KangJuO** [comment]
@note11g IOS 16.0 입니다.

**Comment by note11g** [comment]
[1.0.0-dev.6](https://pub.dev/packages/flutter_naver_map/versions/1.0.0-dev.6)에서 수정하였습니다.
감사합니다.
