### ISSUE TITLE
지도 위젯을 제거해도, 메모리가 해제되지 않는 문제

### ISSUE THREAD

**Issue by jjyoung277** [note11g/flutter_naver_map#47]
안녕하세요. flutter로 토이프로젝트를 개발하면서 항상 개발해주신 네이버 지도를 잘 사용하고 있습니다.
개발하다가 이슈를 발견했는데요, IOS기기에서 페이지를 네이버 지도가 포함된 페이지를 pop할 경우 메모리에서 해제되지 않고 계속해서 누적으로 NaverMap이 쌓이는것 같습니다. 
일전에 비슷한 이슈가 [원본 repo에서 있었던 것 같은데요](https://github.com/LBSTECH/naver_map_plugin/issues/45), 혹시 해소가 가능한 이슈일까요?

**Comment by junyoung-ju** [comment]
^1.0.0-dev.5 와 ^1.0.0-dev.6 모두 같은 증상이 보이는것 같습니다!

**Comment by note11g** [comment]
@jjyoung277  확인 후에, 다시 코멘트 드리도록 하겠습니다.

참고) 1.0.0 버전은 기존 코드와 공유하는 코드가 없습니다.
(0.10.x 대 버전은 메모리 누수 문제를 해결하였었습니다)

**Comment by jjyoung277** [comment]
빠르게 체크해주셔서 감사합니다!

**Comment by note11g** [comment]
@jjyoung277 

[1.0.0-dev.7](https://pub.dev/packages/flutter_naver_map/versions/1.0.0-dev.7)에서 수정되었습니다.
감사합니다.

**Comment by note11g** [comment]
Android에서도 Memory Leak이 발생함을 확인하였습니다.

**Comment by note11g** [comment]
[1.0.0-dev.8](https://pub.dev/packages/flutter_naver_map/versions/1.0.0-dev.8)에서 수정되었습니다.
감사합니다.
