### ISSUE TITLE
ios > CameraUpdate.toCameraPosition( CameraPosition(~~) ) 작동 이슈

### ISSUE THREAD

**Issue by dreamofmidge** [note11g/flutter_naver_map#5]
안녕하세요 :)
패키지 잘 쓰고 있습니다.

그런데 controller.moveCamera(CameraUpdate.**toCameraPosition**(newCamera))

위와 같이
moveCamera 함수에 Cameraupdate.**toCameraPosition** 을 넣으면
안드로이드에서는 잘 동작하는데, ios 에서는 동작하지 않네요 ㅠㅠ
에러 메시지도 없어서 원인을 알기가 어렵네요

( 참고로 moveCamera 함수에 Cameraupdate.**scrollTo** 를 넣으면 안드/iOS 둘다 잘 작동합니다. )

점검 한번 해보시고 답변주시면
감사하겠습니다 :)

------------------------------------------------------------------------------------

해당패키지 버전은 0.10.3 최신버전
flutter 2.8.1
flutter doctor -v 실행시 이슈는 없습니다. (No issues found!)

**Comment by note11g** [comment]
확인 후 다시 멘션 달아서 코멘트 드리도록 하겠습니다..!

**Comment by note11g** [comment]
오늘 밤에 수정 예정입니다. 감사합니다.

**Comment by note11g** [comment]
0.10.5 버전에서 수정되었습니다. 감사합니다.
@dreamofmidge

**Comment by dreamofmidge** [comment]
> 0.10.5 버전에서 수정되었습니다. 감사합니다. @dreamofmidge

감사합니다!! @note11g
