### ISSUE TITLE
Android에서 앱에 Lifecycle 변경이 발생했을 때, 지도가 네비게이터 스택을 무시하고 최상단에 노출되는 문제

### ISSUE THREAD

**Issue by Kwon-dev** [note11g/flutter_naver_map#56]
예를 들면 홈 화면에 네이버 지도 위젯을 넣었다고 가정할 때, 그 페이지 위로 쌓이는 페이지(push를 통해 이동한 페이지)들 에서 화면 잠금을 했다가 잠금을 해제하면 네이버 지도가 페이지 제일 위로 올라와서 노출 되는 오류가 있습니다. 특정 기종이 문제가 아니라 다양한 폰에서 테스트해 본 결과 모두 같은 결과가 나왔고, 아이폰에서는 재현되지 않았습니다.

현재 사용중인 버전은  flutter_naver_map: ^1.0.0-dev.8이고 flutter 버전은 3.7.7 입니다.
안드로이드 compileSdkVersion은 33을 사용하고 있습니다.

**Comment by note11g** [comment]
flutter/flutter#103630 해당 이슈와 연관 있어보입니다.
자세한 파악 후, 다시 코멘트 드리겠습니다.

**Comment by note11g** [comment]
@Kwon-TaeHyoung 혹시, 오류로그가 존재할까요?

**Comment by Kwon-TaeHyoung** [comment]
관련있어 보이는 로그는
E/SurfaceSyncer(23788): Failed to find sync for id=0
E/SurfaceSyncer(23788): Failed to find sync for id=1
E/SurfaceSyncer(23788): Failed to find sync for id=2
E/SurfaceSyncer(23788): Failed to find sync for id=3
E/SurfaceSyncer(23788): Failed to find sync for id=4
E/SurfaceSyncer(23788): Failed to find sync for id=5
E/SurfaceSyncer(23788): Failed to find sync for id=6
E/SurfaceSyncer(23788): Failed to find sync for id=7
말고는 없네요

**Comment by note11g** [comment]
재현에 성공하였습니다.
flutter/flutter#89588 에서 언급된 해결법을 사용하면, 임시적으로 고칠 수 있습니다. 
하지만, 플러그인 자체로 해결할 수 있는 방법은 아직 없습니다. 찾는대로 코멘트 드리겠습니다.
**임시 해결법** : MainActivity.kt
```kotlin
import android.os.Bundle
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterTextureView

class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        intent.putExtra("background_mode", "transparent")
        super.onCreate(savedInstanceState)
    }

    override fun onFlutterTextureViewCreated(flutterTextureView: FlutterTextureView) {
        flutterTextureView.isOpaque = true
        super.onFlutterTextureViewCreated(flutterTextureView)
    }
}
```

**Comment by Kwon-TaeHyoung** [comment]
감사합니다 일단 해당 방법으로 문제는 해결됐습니다.

**Comment by note11g** [comment]
더 간단하게 해결하는 방법은 다음과 같습니다.

```kotlin
import android.os.Bundle
import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        intent.putExtra("background_mode", "transparent")
        super.onCreate(savedInstanceState)
    }
}
```

**Comment by Kwon-TaeHyoung** [comment]
1.0.0-dev.9 업데이트 후 위의 임시 해결법을 적용하지 않아도 해당 버그는 발생하지 않음을 확인했습니다. 다만 잠금 & 잠금해제나 홈 화면에 갔다가 복귀할 경우 #53 에서 해결한 것으로 보이는 검은 화면이 생기는 이슈가 있습니다.

**Comment by note11g** [comment]
@Kwon-TaeHyoung 임시 해결법을 적용하시면 문제가 없는지 여부를 여쭤봐도 될까요?

**Comment by Kwon-TaeHyoung** [comment]
해당 방법 적용 여부와 상관없이 같은 증상이 생깁니다. 차이점이라면 해당 방법을 적용하기 전엔 검은 화면으로 바뀌지만 적용하면 최 상위에 있던 위젯의 모양대로 프리징이 걸린다는 차이가 있습니다.

**Comment by note11g** [comment]
@Kwon-TaeHyoung 예제 앱에서 화면 추가후, 동일한 증상이 확인되시는지 한번 확인 부탁드립니다.

**Comment by Kwon-TaeHyoung** [comment]
예제앱에서도 같은 이슈가 발생합니다. debug 모드랑 release 모드 양쪽에서 발생합니다. 참고로 플러터 버전은 3.7.8 이며 실제 기기에서 테스트 중입니다.

**Comment by note11g** [comment]
@Kwon-TaeHyoung 해당 이슈와 언급해주신 이슈는 관련이 없습니다.
해당 이슈로, 새로운 이슈 열도록 하겠습니다. 감사합니다.

**Comment by KimSungJin0** [comment]
> 재현에 성공하였습니다. [flutter/flutter#89558](https://github.com/flutter/flutter/issues/89558) 에서 언급된 해결법을 사용하면, 임시적으로 고칠 수 있습니다. 하지만, 플러그인 자체로 해결할 수 있는 방법은 아직 없습니다. 찾는대로 코멘트 드리겠습니다.
> 
> **임시 해결법** (MainActivity.kt 파일을 수정해야 합니다)
> 
> ```kotlin
> import android.os.Bundle
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.android.FlutterTextureView
> 
> class MainActivity : FlutterActivity() {
>     override fun onCreate(savedInstanceState: Bundle?) {
>         intent.putExtra("background_mode", "transparent")
>         super.onCreate(savedInstanceState)
>     }
> 
>     override fun onFlutterTextureViewCreated(flutterTextureView: FlutterTextureView) {
>         flutterTextureView.isOpaque = true
>         super.onFlutterTextureViewCreated(flutterTextureView)
>     }
> }
> ```

해당 옵션을 적용한 후 splash 배경화면이 검은색으로 바뀌었습니다.
혹시 해결할 수 있는 방안이 있나요?

**Comment by note11g** [comment]
@KimSungJin0 혹시 두번째 함수를 적지 않았을때도 해당 현상이 발생하시나요?

**Comment by KimSungJin0** [comment]
`override fun onFlutterTextureViewCreated(flutterTextureView: FlutterTextureView) {
        flutterTextureView.isOpaque = true
        super.onFlutterTextureViewCreated(flutterTextureView)
    }`
를 주석 처리하고 진행한 결과 아직도 검은색임을 확인했습니다.
제 생각엔 `intent.putExtra("background_mode", "transparent")` 이 원인인 것 같습니다.
해당 코드를 주석하니 splash와 깜빡임 현상이 나오지 않는 것을 확인했습니다.

**Comment by akshatjain-beam** [comment]
hello, the solution is giving `black screen` at the app start, but when removing the `intent.putExtra` stacking of pages can be observed. Any possible solutions, so to not the have the `black screen` and not having the stacking of pages.

**Comment by akshatjain-beam** [comment]
@note11g @KimSungJin0 , do you faced the similar issue?

> https://github.com/note11g/flutter_naver_map/issues/56#issuecomment-1543740325

**Comment by rishabhgoyal-beam** [comment]
1. The solution to Issue #56 is giving black screen at the app start, but when removing the intent.putExtra stacking of pages can be observed.
2. It has become a tradeoff now. The solution to the blackout issue is removing a piece of code, which in-turn is a solution to Issue #56.

Could you please help us @note11g @KimSungJin0?

**Comment by akshatjain-beam** [comment]
for anyone, facing black screen issue, can refer to - https://github.com/jonbhanson/flutter_native_splash/issues/54#issuecomment-589237135

**Comment by betrider** [comment]
안드로이드 스크린 이동 시 스크린의 지도가 오버레이되는 문제가 있습니다.

이와 관련해서 현재 패키지에서 지도를 표시할 때 GLSurfaceView를 사용하기 때문에 발생하는 문제로 보입니다. 
추가로 TextField 포커스 이슈도 GLSurfaceView와 관련있습니다.(https://pub.dev/packages/flutter_naver_map/versions/0.10.7 - 참고사항)

GLSurfaceView와 TextureView의 용도가 다르기 때문에 옵션이 필요 합니다.
flutter_naver_map 0.10.7버전까지 존재했던 옵션(useSurface)이 사라져서 사용 할 수가 없습니다.
사용자의 용도에 따라 사용 할 수 있게 NaverMapOption - useTextureView 추가 부탁드립니다.

**Comment by note11g** [comment]
@betrider 확인하였습니다. 빠른 시일 내 검토할 수 있도록 하겠습니다. 감사합니다.

**Comment by note11g** [comment]
검토 사항
1. GLSurfaceView 사용 / TextureView 사용 Trade Off 관련 검토
2. GLSurfaceView 사용시, Native Splash 실행 이후 임시 해결 코드를 실행하는 방안 검토

**Comment by note11g** [comment]
@Kwon-dev @KimSungJin0 @betrider @akshatjain-beam @rishabhgoyal-beam 

해당 현상이 해결된 것으로 보입니다. (임시 해결법 없이)
해당 현상 재현 테스트를 진행해주실 수 있는지 여쭤볼 수 있을까요? 
([재현 Example Repository](https://github.com/note11g/flutter_naver_map_pure_example/tree/issue/%2356))를 통해서 실행해보실 수 있습니다.

**Comment by note11g** [comment]
83c7adb 커밋은 근본적인 문제(Flutter Engine Issue)를 해결하지는 않습니다.
하지만, flutter_native_splash 패키지의 동작을 방해하지 않으면서, 해당 문제를 해결하는 커밋입니다.
또한, 더 이상의 유저 측에서 별도로 코드 작성이 필요하지 않습니다.

**Comment by note11g** [comment]
다음처럼 사용하시면 됩니다. ([참고: flutter_native_splash#3-set-up-app-initialization-optional](https://pub.dev/packages/flutter_native_splash#3-set-up-app-initialization-optional))
```dart
void main() async {
  final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  await NaverMapSdk.instance.initialize(clientId: 'your client id');
  FlutterNativeSplash.remove();
  runApp(const MyApp());
}
```

다음은 테스트 영상입니다. (Pixel 4 API 33 Emulator, Flutter Release Mode)

https://github.com/note11g/flutter_naver_map/assets/67783062/886954ea-baa8-48b6-b5dc-06eaa0e98f78

**Comment by note11g** [comment]
`1.1.1` 버전에서 수정됩니다. 감사합니다.
