### ISSUE TITLE
라이브러리 용량 이슈

### ISSUE THREAD

**Issue by shr8596** [note11g/flutter_naver_map#57]
개발 앱 용량을 줄이기 위해 분석한 결과 네이버 지도 라이브러리가 가장 많은 용량을 차지했습니다(약 80%)

![개발앱_용량](https://user-images.githubusercontent.com/97893538/225842278-86d36659-823a-4e4d-90e1-f4c1666d77e0.png)

arm64-v8a

x86

x86_64

armeabi-v7a

에 모두 포함이 되어있고 가장 많은 용량을 차지하고 있습니다

필요한 부분만 따로 가져올 수 있는 지, 된다면 어떤 방법으로 해야 하는 지 질문 드립니다

+ 1.0.0 출시는 대략적으로 언제 나오는 지 답변 가능하시면 부탁 드립니다

**Comment by note11g** [comment]
@shr8596 안녕하세요. flutter_naver_map 패키지를 이용해주셔서 감사드립니다.

아마, appbundle로 빌드하실 경우, 실제로 설치되는 앱 용량은 더 낮아질 것입니다. 이는 [appbundle 문서](https://developer.android.com/guide/app-bundle?hl=ko)를 참고해주세요.

1.0.0 정식 릴리즈 출시는 안정화 이후에 출시됩니다. 현재 크리티컬 이슈로 판단되는 #53 이 있기에, 출시가 늦어지고 있습니다.
답변이 되셨으면 좋겠습니다. 감사합니다.

**Comment by note11g** [comment]
해당 이슈는 문제가 아닌 것으로 판단됩니다.
혹시, 문제라고 판단하신다면 코멘트와 함께 다시 이슈를 열어주시기 바랍니다.
감사합니다.
