### ISSUE TITLE
1.x 부터는 market tap event가 사용 불가능할까요?

### ISSUE THREAD

**Issue by jjyoung277** [note11g/flutter_naver_map#58]
안녕하세요. 개발해주신 라이브러리를 유용하게 사용하고 있습니다. 항상 감사합니다.

다름이 아니라,
0.x 버전에서는 marker 클릭시 이벤트를 등록해서 사용했었는데요, 1.x 버전부터 info window에서만 클릭 이벤트 등록이 가능한걸로 보입니다. 라이브러리의 여러 주석들을 살펴보았으나 현재 지원되지 않는 것으로 예상됩니다 ㅠㅠ (default marker 만 사용하고 있긴 합니다)
혹시 네이티브 네이버맵 버전 업데이트에 따른 제약사항일까요? 가능하다면 marker 클릭시 info window가 열리고, info window 클릭시 추가 작업을 할 수 있다면 사용성에 좋을 것 같습니다.
현재 ^1.0.0-dev.7 버전을 사용하고 있습니다.

**Comment by note11g** [comment]
안녕하세요.

다음은 마커를 생성하고, 해당 마커를 탭하면 인포 윈도우가 열리며,
해당 인포윈도우를 탭하였을 때, 인포윈도우를 닫는 예제입니다.

```dart
final marker = NMarker(id: "1", position: const NLatLng(37.5666102, 126.9783881));

marker.setOnTapListener((NMarker m) {
  final infoWindow = NInfoWindow.onMarker(
    id: m.info.id, // 인포 윈도우의 id가 마커의 id와 같을 필요는 없습니다.
    text: "인포 윈도우",
  )..setOnTapListener((iw) => iw.close());

  m.openInfoWindow(infoWindow);
});

mapController.addOverlay(marker);
```

제안해 주신 기능은 다음과 같이 사용하실 수 있으며, `setOnTapListener`는 모든 NOverlay 종류에 사용 가능합니다. 감사합니다.

**Comment by jjyoung277** [comment]
제 이해가 부족했군요.. 예제까지 첨부해주셔서 감사합니다!

**Comment by note11g** [comment]
@jjyoung277 아닙니다! 제가 문서를 아직 못 만든 탓이죠.. 빠른 시일 내 문서 완성토록 하겠습니다!
