### ISSUE TITLE
NaverMap Controller 위경도 값

### ISSUE THREAD

**Issue by sangeunA** [note11g/flutter_naver_map#59]
NaverMap Controller 를 통해서 Bounds 값을 받아올때 위/경도값이 이상하게 반환되는 현상이 나타납니다.

longitude = -180 ~ 180
latitude = -90 ~ 90
범위 내의 값이 나오도록 되어있는것이 맞나요?

[ 사용코드 ]
final NLatLngBounds bounds = await _controller.getContentBounds().then((value) {
  Logger.d('southWest.latitude : ${value.southWest.latitude}');
  Logger.d('southWest.longitude : ${value.southWest.longitude}');
  Logger.d('northEast.latitude : ${value.northEast.latitude}');
  Logger.d('northEast.longitude : ${value.northEast.longitude}');
  return value;
});
final NCameraPosition position = await _controller.getCameraPosition().then((value) {
  Logger.d('zoomLevel : ${value.zoom}');
  return value;
});

[ Log ]
southWest.latitude : 31.67777782353899
southWest.longitude : -213.7573257954126
northEast.latitude : 85.05112877980659
northEast.longitude : -138.71761555841488
zoomLevel : 2.003737663384527

**Comment by note11g** [comment]
@sangeunA 안녕하세요. 먼저, 이슈를 제보해주셔서 감사드립니다.
재현을 위해, 앱을 구동하신 플랫폼 정보를 요청드려도 될까요?

**Comment by note11g** [comment]
해당 현상은 네이버맵 SDK (NAVER Map Android SDK, NAVER Map iOS SDK) 자체에서 지도를 제공하지 않는 지역에서 발생하는 것으로 확인하였습니다.

발생하는 경우를 설명드리겠습니다.
경도 180도(-180도) 구간이 지도 화면에 포함되는 경우, 발생합니다.

이는 지도 영역 제한을 이용하시면 방지하실 수 있습니다.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/67783062/227703345-3e917a80-17d4-445e-a235-e43e13d60101.png">

flutter_naver_map의 버그는 아님을 알려드립니다. 감사합니다.

**Comment by note11g** [comment]
Naver Cloud Platform 측에 문의를 넣고, 답변이 오는대로 추가 코멘트를 달도록 하겠습니다. 감사합니다.

**Comment by note11g** [comment]
답변이 도착해 알려드립니다.

> 안녕하세요.
네이버 클라우드 플랫폼입니다.
네이버 지도 SDK는 글로벌 영역에서의 동작을 보장하지 않습니다.
부득이하게 사용해야할 경우 각 좌표를 wrap해서 사용을 부탁드립니다.
감사합니다.
