### ISSUE TITLE
All the holes are not getting displayed when using PolygonOverlay

### ISSUE THREAD

**Issue by akshatjain-beam** [note11g/flutter_naver_map#64]
### Scenario 
I have created a **PolgonOverlay**, in which for coordinates I am giving the **world coordinates** and for **holes** I am giving **small polygons in counterclockwise direction.**

**What I found is all the holes are not getting displayed for iPhone. Only some of them are getting displayed.**

### expected - 
<img width="919" alt="image" src="https://user-images.githubusercontent.com/113326157/228448669-f4459285-f651-472a-985e-f543a13e54d7.png">

### got - 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/113326157/228449067-55adfc35-4eb3-4059-aaad-65ce06648628.png">

### Also, if I comment the big one on the left, the 2 smaller ones will appear - 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/113326157/228449361-47699fc8-2d8b-4fd0-b962-7f3630ec293b.png">

**Comment by note11g** [comment]
Hi. 
Please let me know the environment you are working on and this library version.

**Comment by akshatjain-beam** [comment]
hello,
naver_maps - 0.10.6, 
> Please let me know the environment you are working on
can you elaborate please

**Comment by note11g** [comment]
@akshatjain-beam 
Can you test it in 1.0.0-dev.9 version?

and here's the [1.0.0-dev.9 docs](https://note11.dev/flutter_naver_map/)

**Comment by akshatjain-beam** [comment]
@note11g , please check the holes coordinates again, had modified them....

**Comment by note11g** [comment]
@akshatjain-beam can you check same on Android?

**Comment by akshatjain-beam** [comment]
@note11g , yes.its working fine and all of them are visible
<img width="428" alt="image" src="https://user-images.githubusercontent.com/113326157/228474530-b040e0fa-0deb-49fc-8edd-79337975046c.png">

**Comment by akshatjain-beam** [comment]
hey @note11g , following up regarding any updates?
for holes, you can try with these 2, only one of them is showing in IOS
```
holes = [
      [LatLng(37.54357147216797, 126.852294921875), LatLng(37.54539489746094, 126.81037139892578), LatLng(37.54866027832031, 126.7945785522461), LatLng(37.500465393066406, 126.73552703857422), LatLng(37.4418830871582, 126.78702545166016), LatLng(37.423072814941406, 126.79080200195312), LatLng(37.423072814941406, 126.8831558227539), LatLng(37.456329345703125, 126.94564819335938), LatLng(37.47922134399414, 126.82239532470703), LatLng(37.52334213256836, 126.90718841552734), LatLng(37.53811264038086, 126.87666320800781), LatLng(37.545631408691406, 126.87666320800781), LatLng(37.545631408691406, 126.852294921875), LatLng(37.54357147216797, 126.852294921875)],
      [LatLng(37.507957458496094, 126.93036651611328), LatLng(37.487674713134766, 126.94530487060547), LatLng(37.50560760498047, 126.96732330322266), LatLng(37.50663757324219, 126.95114135742188), LatLng(37.511226654052734, 126.95465850830078), LatLng(37.51388168334961, 126.94710540771484), LatLng(37.51108932495117, 126.93964385986328), LatLng(37.507755279541016, 126.93714904785156), LatLng(37.50743103027344, 126.93865203857422), LatLng(37.507957458496094, 126.93036651611328)],
    ];
```

**Comment by note11g** [comment]
@akshatjain-beam I'm sorry. I'm a little busy these days, so I think it'll be processed a little late.

**Comment by akshatjain-beam** [comment]
Hey @note11g , closing the issue, as the updated the code to latest version `1.0.1`, and there the bug is not there
Thanks!

**Comment by note11g** [comment]
@akshatjain-beam thank you..!!! I'm so glad it's resolved!! 😍 And I'm sorry that I couldn't support the 0.10 version continuously...
