### ISSUE TITLE
[Android, Engine Issue] Android Platform에서 위젯의 투명도(Opacity)가 조절이 되지 않는 문제

### ISSUE THREAD

**Issue by emotionalboySY** [note11g/flutter_naver_map#68]
항상 고생하십니다.

main page에서 naver map widget이 있는 페이지로 get.toNamed가 호출되어 페이지를 이동하도록 구성되어 있습니다.

여기서 뒤로 가기 버튼을 누르면 Get.back()가 호출되며 돌아가도록 되어 있는데,

Naver Map widget만 늦게 사라지는 문제가 있습니다. 이 경우 어느 부분을 수정해야 하는지 여쭤볼 수 있을까요?

flutter version: 3.7.8
dart version: 2.19.5
plugin version: 1.0.0 dev.9
Android version: 13(API Level 33)

**Comment by emotionalboySY** [comment]
https://user-images.githubusercontent.com/6222849/228714016-fab83cdd-7765-4180-82d3-88d078e5fca5.mp4

해당 이슈 관련 화면 녹화 영상을 첨부드립니다.

**Comment by note11g** [comment]
안녕하세요. 먼저, 이슈를 제보주셔서 감사드립니다.

해당 부분은 인지하고 있는 부분이었으나, flutter Hybrid Composition 자체의 이슈로 알고 있습니다.

아직 분석중에 있는 부분이니, 조금만 기다려주시면 감사드리겠습니다. 감사합니다.

**Comment by emotionalboySY** [comment]
감사합니다 :) 추후 업데이트되면 알려주시면 감사드리겠습니다

**Comment by note11g** [comment]
관련 이슈 : flutter/flutter#118498

**Comment by note11g** [comment]
관련 이슈 : https://github.com/flutter/flutter/issues/93757
