### ISSUE TITLE
마커 클러스터링 구현 유무!

### ISSUE THREAD

**Issue by chinggu88** [note11g/flutter_naver_map#7]
api 문서를 찾아보니 마커 클러스터링이 구현이 안되어 있는거 같은데

혹시 추후 개발 계획이 있나요 ?

**Comment by note11g** [comment]
혹시 네이버 맵 SDK (Mobile Dymaic Map)에서 해당 기능을 지원하는지 알 수 있을까요? 링크와 함께 덧붙여주시면 감사드리겠습니다.

**Comment by chinggu88** [comment]
아 죄송합니다.  웹버전만 구현되어 있네요 ㅠ

**Comment by note11g** [comment]
네. 이슈 Close 하겠습니다. 감사합니다.
