### ISSUE TITLE
When I click marker can not open Alert Dialog

### ISSUE THREAD

**Issue by islom9797** [note11g/flutter_naver_map#74]
[_OverlayControllerImpl] _handleMethodCall: NOverlayInfo(type: NOverlayType.marker, id: test)
[_OverlayControllerImpl] error!   UnimplementedError
I am sorry  I will write in English.
Firstly I appreciate your libruary .Please How I can show Dialog when click marker.It gives some error
Regard Flutter Developer

**Comment by note11g** [comment]
hi. pls more detail info.

**Comment by islom9797** [comment]
Hello I want to Open Dialog when I click to marker
I will attach video



marker.setOnTapListener((m) {
  symbolTapped(context);
});



symbolTapped(context) {
  showDialog(
      context: context,
      builder: (_) {
        return AlertDialog(
          title: Text("adkfndkf"),
        );
      });
}

**Comment by note11g** [comment]
Is the symptom still being produced?
Reproduction failed with the code you provided.

**Comment by islom9797** [comment]
yeah still this problem.I cant not open dialog When I use Naver Map I will attach full source

**Comment by islom9797** [comment]
This Naver Map page



import 'package:flutter/material.dart';
import 'package:flutter_naver_map/flutter_naver_map.dart';
import 'package:get/get.dart';
import 'package:womo_app/presentation/pages/map/map_controller.dart';
class MapPage extends StatefulWidget {
  const MapPage({Key? key}) : super(key: key);

  @override
  State<MapPage> createState() => _MapPageState();
}

class _MapPageState extends State<MapPage> {
  @override
  Widget build(BuildContext context) {
    return  Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text("지도 보기"),
      ),
      body:  GetBuilder<MapPageController>(

          init:MapPageController(),
          builder: (controller) {

            return NaverMap(

              options: const NaverMapViewOptions(
                indoorEnable: true,
                locationButtonEnable:true,
                scaleBarEnable: true,
                zoomGesturesEnable: true,
                initialCameraPosition: NCameraPosition(
                  target: NLatLng(37.497942 , 127.027621),
                  zoom: 13,),
              ), // 지도 옵션을 설정할 수 있습니다.
              forceGesture: true, // 지도에 전달되는 제스처 이벤트의 우선순위를 가장 높게 설정할지 여부를 지정합니다.
              onMapReady: (navercontroller)async {
                controller.naverMapController=navercontroller;
                controller.setMap(context);
              },
              onMapTapped: (point, latLng) {
                Get.to(MapPage());
              },

              onSymbolTapped: (symbol) {
                controller.symbolTapped(context);
                print('onSymbolTapped');
              },
              onCameraChange: (position, reason) {print('onCameraChange');},
              onCameraIdle: () {print('onCameraIdle');},
              onSelectedIndoorChanged: (indoor) {print('onSelectedIndoorChanged');},
            );
          }
      ),
    );
  }
}

**Comment by islom9797** [comment]
this is Controller page



import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_naver_map/flutter_naver_map.dart';
import 'package:get/get.dart';
import 'package:permission_handler/permission_handler.dart';

class MapPageController extends GetxController {
  late NaverMapController naverMapController;

  setMap(context) async {
    naverMapController.setLocationTrackingMode(NLocationTrackingMode.follow);
    NCameraPosition camerapostion =
        await naverMapController.getCameraPosition();

    NCameraUpdate cameraUpdate =
        NCameraUpdate.withParams(target: camerapostion.target);
    await naverMapController.updateCamera(cameraUpdate);
    print('map ready');
    final iconImage = await NOverlayImage.fromWidget(
        widget: Image.asset("assets/main/37.png"),
        size: const Size(30, 30),
        context: context);
    final marker = NMarker(
        id: "test", position: NLatLng(37.497942, 127.027621), icon: iconImage);


    naverMapController.addOverlay(marker);
    final onMarkerInfoWindow =
        NInfoWindow.onMarker(id: marker.info.id, text: "인포윈도우 텍스트");

    marker.openInfoWindow(onMarkerInfoWindow);
    marker.setOnTapListener((m) {
      symbolTapped(context);
    });



// You can request multiple permissions at once.
    Map<Permission, PermissionStatus> statuses = await [
      Permission.location,
      Permission.storage,
    ].request();
    print(statuses[Permission.location]);
  }

  symbolTapped(context) {
    showDialog(
        context: context,
        builder: (_) {
          return AlertDialog(
            title: Text("adkfndkf"),
          );
        });
  }
}

**Comment by islom9797** [comment]
I cant put IconButton  to Appbar with Naver Map its give error
I must to delete Appbar Icon if I want to use

appBar: AppBar(
        centerTitle: true,
        title: Text("지도 보기"),
        actions: [
           // IconButton(onPressed:symbolTapped(context) , icon: Icon(Icons.add))
        ],
      ),


With IconButton in appbar 
<img width="312" alt="Снимок экрана 2023-04-10 в 11 48 28 PM" src="https://user-images.githubusercontent.com/40173829/230925436-30ac584d-c370-421f-b0aa-a760239c7724.png">


**### Error**


======== Exception caught by widgets library =======================================================
The following UnimplementedError was thrown building MapPage(dirty, dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#a51f5]], state: _MapPageState#7a233):
UnimplementedError

The relevant error-causing widget was: 
  MapPage MapPage:file:///Users/islomjonrikhsiyev/StudioProjects/womo-app/lib/presentation/pages/home/widgets/find_around_me.dart:79:20
When the exception was thrown, this was the stack: 
#0      MaterialLocalizationKo.modalBarrierDismissLabel (package:womo_app/core/locals/korean-delegates/material_delegate.dart:472:42)
#1      new DialogRoute (package:flutter/src/material/dialog.dart:1380:74)
#2      showDialog (package:flutter/src/material/dialog.dart:1282:73)
#3      _MapPageState.symbolTapped (package:womo_app/presentation/pages/map/map_page.dart:130:5)
#4      _MapPageState.build (package:womo_app/presentation/pages/map/map_page.dart:145:34)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#14     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942:7)
#18     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================
Reloaded 1 of 1973 libraries in 328ms (compile: 58 ms, reload: 129 ms, reassemble: 116 ms).

======== Exception caught by image resource service ================================================
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2733:9)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2604:7)
#2      IOClient.send (package:http/src/io_client.dart:57:38)
#3      HttpFileService.get (package:flutter_cache_manager/src/web/file_service.dart:35:44)
#4      WebHelper._download (package:flutter_cache_manager/src/web/web_helper.dart:121:24)
#5      WebHelper._updateFile (package:flutter_cache_manager/src/web/web_helper.dart:103:28)
<asynchronous suspension>
#6      WebHelper._downloadOrAddToQueue (package:flutter_cache_manager/src/web/web_helper.dart:71:7)
<asynchronous suspension>
Image provider: CachedNetworkImageProvider("", scale: 1.0) 
 Image key: CachedNetworkImageProvider("", scale: 1.0): CachedNetworkImageProvider("", scale: 1.0)
====================================================================================================



without Iconbutton in appbar
<img width="268" alt="Снимок экрана 2023-04-10 в 11 42 07 PM" src="https://user-images.githubusercontent.com/40173829/230924196-23116a5d-89ec-4f62-93d6-a4dea0499d98.png">

**Comment by islom9797** [comment]
I fix problem It was because of GETX localization
Thanks

**Comment by islom9797** [comment]
I fix problem It was because of GETX localization
Thanks
