### ISSUE TITLE
[iOS] No such module 'NMapsMap'

### ISSUE THREAD

**Issue by kehyoung** [note11g/flutter_naver_map#75]
iOS 에서 빌드에러가 발생합니다.
시작가이드는 모두 따라서 설정했고요
현재는 시뮬레이터에서 작업중인데 시뮬레이터에선 사용이 불가한가요? 찾아보니 가능하다고 하시는 것 같은데...
아래 같은 에러를 참고해봐도 답이 없어 이슈를 올립니다.
혹시 MacOS와 XCode 버전 문제도 있을까요?(flutter doctor 도 아래 첨부합니다)

---
- 에러

Launching lib/main.dart on iPhone 13 Pro in debug mode...
main.dart:1
Xcode build done.                                            8.5s
Failed to build iOS app
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Uncategorized (Xcode): Command EmitSwiftModule failed with a nonzero exit code

Swift Compiler Error (Xcode): No such module 'NMapsMap'
/Users/chplatform/.pub-cache/hosted/pub.dev/flutter_naver_map-1.0.0/ios/Classes/converter/AddableOverlay.swift:0:7

Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro.
Exited

---
- flutter doctor
 flutter doctor           
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.6, on macOS 12.3.1 21E258 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by note11g** [comment]
안녕하세요. 먼저 이슈를 제보해주셔서 감사드립니다.
혹시 실기기에서는 정상적으로 동작하는지 확인 가능하실까요?

**Comment by kehyoung** [comment]
arch 커맨드는 이미 써보았네요 ㅠㅠ;;
일전에 올라왔던 iOS 빌드 이슈도 확인했었습니다.

마찬가지로 pod update NMapsMap 도 소용이 없습니다.

**Comment by Hevton** [comment]
인텔 맥인데 마찬가지로 같은 오류가 발생합니다.
며칠째 해결이 안되네요

**Comment by note11g** [comment]
@Hevton, @kehyoung  님, 혹시 해결을 위해 시도해보신 것들을 알려주실 수 있으실까요?

**Comment by note11g** [comment]
@kehyoung @Hevton 두 분 모두 해당 답변을 참고하시어 시도해 주실 수 있으실까요?
https://stackoverflow.com/questions/74120505/swift-compiler-error-xcode-no-such-module-flutter-downloader

**Comment by Hevton** [comment]
@note11g 안녕하세요. 프로젝트에 이 모듈을 적용하고 빌드에 오류가 생겨서 이 모듈에서 문제를 찾고자 했으나, 
이 모듈이랑 직접적인 연관이 있었던 것은 아닌 것 같습니다.
XCode에서 프로젝트 오픈 시 Warning으로 제시되는 버전이나 캐시문제를 해결해주면 잘 진행되었습니다.

**Comment by note11g** [comment]
@Hevton 감사합니다.

@kehyoung 님도 버전/캐시 문제인지 확인 부탁드리겠습니다.

**Comment by note11g** [comment]
라이브러리의 이슈가 아닌 것으로 보이고, 오랫동안 답변이 달리지 않아 이슈를 닫도록 하겠습니다.
여전히 이슈라고 판단하신다면, 이슈를 다시 열어주세요.
감사합니다.
