### ISSUE TITLE
Is there any option for location marker in v1.0.1

### ISSUE THREAD

**Issue by akshatjain-beam** [note11g/flutter_naver_map#78]
### Overview
When I am rendering the map, I am not able to see the location marker which shows that I am at this location. Is there any option available in the package to use

Example - 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/113326157/232745889-65073187-eff6-4279-8172-f88ce133d165.png">

**Comment by KimSungJin0** [comment]
Try 'setLocationTrackingMode' in 'controller'. Use 'NLocationTrackingMode.noFollow' to implement as shown in the picture.

**Comment by akshatjain-beam** [comment]
hey @KimSungJin0 , can pls give an example

**Comment by akshatjain-beam** [comment]
```
enum NLocationTrackingMode {
  face,
  follow,
  noFollow,
  none;
}
```

Hey @KimSungJin0 , can you please help me in understanding what's the difference between these 4 modes of `NLocationTrackingMode.noFollow`

**Comment by note11g** [comment]
@akshatjain-beam see this.
https://navermaps.github.io/android-map-sdk/guide-en/4-2.html
see "Location tracking mode" Section.

**Comment by akshatjain-beam** [comment]
Hey @note11g , thanks for reverting. It helped.
Also , in the link - https://navermaps.github.io/android-map-sdk/guide-en/4-2.html, inside `Location change event` heading
is there any way to use `onLocationChange()` for flutter-naver-maps

**Comment by akshatjain-beam** [comment]
I think, I can use - https://note11.dev/flutter_naver_map/element/event/#oncamerachange
**location: When the camera moves due to the built-in location tracking function** 🤔

**Comment by note11g** [comment]
does not support. but you can implement this function. (for example, using geolocator and NLocationOverlay.setPosition method.)

or, 

on face / follow mode, camera position will be change.
in this case, onCameraChange or onCameraIdle is Called.

**Comment by akshatjain-beam** [comment]
used this combo - 
```
_controller!.setLocationTrackingMode(NLocationTrackingMode.follow);
if (reason == NCameraUpdateReason.location && _controller != null) {
      NLocationOverlay locationOverlay = await _controller!.getLocationOverlay();
      NLatLng userLocation = await locationOverlay.getPosition();
}
```

and its working .

**Comment by note11g** [comment]
@akshatjain-beam 
issue resolved?
