### ISSUE TITLE
Marker not show when I open page

### ISSUE THREAD

**Issue by islom9797** [note11g/flutter_naver_map#79]
When I open Page marker not show until if I reopen the page after that marker start show

 NaverMap(
              options: const NaverMapViewOptions(
                locationButtonEnable: true,
                initialCameraPosition: NCameraPosition(
                  target: NLatLng(37.497942, 127.027621),
                  zoom: 13,
                ),
              ),
              // 지도 옵션을 설정할 수 있습니다.
              forceGesture: true, // 지도에 전달되는 제스처 이벤트의 우선순위를 가장 높게 설정할지 여부를 지정합니다.
              onMapReady: (navercontroller) async {
           
              final iconImage = await NOverlayImage.fromWidget(
        widget: Image.asset("assets/37.png"),
        size: const Size(30,30),
        context: context);
    final marker1 = NMarker( id: "test1", position: NLatLng(37.497942, 127.027621), icon: iconImage);// 강남
navercontroller.addOverlay(marker1);
                });
              },
              // onMapTapped: (point, latLng) {
              //   Get.to(MapPage());
              // },

              onSymbolTapped: (symbol) {
                controller.symbolTapped(context);

                print('onSymbolTapped');
              },
              onCameraChange: (position, reason) {
                print('onCameraChange');
              },
              onCameraIdle: () {
                print('onCameraIdle');
              },
              onSelectedIndoorChanged: (indoor) {
                print('onSelectedIndoorChanged');
              },
            );

**Comment by islom9797** [comment]
https://user-images.githubusercontent.com/40173829/232892277-2d1ad26f-f799-4261-b6fd-4e6ef7d88367.MOV

**Comment by islom9797** [comment]
@note11g Please give me some Idea.Thanks

**Comment by note11g** [comment]
@islom9797 
use `NOverlayImage.fromAsset` instead.

**Comment by islom9797** [comment]
thanks its worked
 정말 감사합니다
