### ISSUE TITLE
zoomTo 에러가 납니다

### ISSUE THREAD

**Issue by ItdaTeam** [note11g/flutter_naver_map#8]
controller.moveCamera(CameraUpdate.zoomTo(14.0)); 를 사용했을 때

zoomTo가 작동되지 않고 에러코드가 납니다.

E/MethodChannel#naver_map_plugin_0(26250): Failed to handle method call
E/MethodChannel#naver_map_plugin_0(26250): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Any?>
E/MethodChannel#naver_map_plugin_0(26250): 	at map.naver.plugin.net.note11.naver_map_plugin.Convert.toCameraUpdate(Convert.kt:114)
E/MethodChannel#naver_map_plugin_0(26250): 	at map.naver.plugin.net.note11.naver_map_plugin.NaverMapController.onMethodCall(NaverMapController.kt:222)
E/MethodChannel#naver_map_plugin_0(26250): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#naver_map_plugin_0(26250): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#naver_map_plugin_0(26250): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:320)
E/MethodChannel#naver_map_plugin_0(26250): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#naver_map_plugin_0(26250): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#naver_map_plugin_0(26250): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#naver_map_plugin_0(26250): 	at android.os.Looper.loop(Looper.java:237)
E/MethodChannel#naver_map_plugin_0(26250): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/MethodChannel#naver_map_plugin_0(26250): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#naver_map_plugin_0(26250): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/MethodChannel#naver_map_plugin_0(26250): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/flutter (26250): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, null cannot be cast to non-null type kotlin.collections.List<kotlin.Any?>, null, java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Any?>
E/flutter (26250): 	at map.naver.plugin.net.note11.naver_map_plugin.Convert.toCameraUpdate(Convert.kt:114)
E/flutter (26250): 	at map.naver.plugin.net.note11.naver_map_plugin.NaverMapController.onMethodCall(NaverMapController.kt:222)
E/flutter (26250): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (26250): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter (26250): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:320)
E/flutter (26250): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (26250): 	at android.os.Handler.handleCallback(Handler.java:883)
E/flutter (26250): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/flutter (26250): 	at android.os.Looper.loop(Looper.java:237)
E/flutter (26250): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/flutter (26250): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26250): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/flutter (26250): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/flutter (26250): )
E/flutter (26250): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (26250): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
E/flutter (26250): <asynchronous suspension>
E/flutter (26250): #2      NaverMapController.moveCamera (package:flutter_naver_map/src/controller.dart:184:5)
E/flutter (26250): <asynchronous suspension>

해결방법 있을까요?ㅠㅠ

**Comment by note11g** [comment]
해당 이슈는 오늘 야자 끝난 후, 밤에 수정하도록 하겠습니다. 감사합니다.

**Comment by ItdaTeam** [comment]
혹시 수정이 되었을까요?ㅠㅠ

**Comment by note11g** [comment]
업로드는 오늘 밤 예정입니다. 감사합니다.

**Comment by note11g** [comment]
0.10.4에서 수정되었고, 다른 이슈를 수정한 0.10.5 버전을 사용바랍니다.
@ItdaTeam

**Comment by ItdaTeam** [comment]
네, 감사합니다~
