### ISSUE TITLE
지도 좌표값 변경 질문 드립니다

### ISSUE THREAD

**Issue by yangsh91** [note11g/flutter_naver_map#86]
현재 1.0.1로 버전이 업데이트 된거 같아서 업그레이드를 했는데 기존 내용과 좀 많이 바껴 있더군요

여기서 질문드리고 싶은 게 기존 버전에서 카메라 이동 시 카메라 좌표값을 따라 마커 위치를 변경시켰는데

1.0.1 버전에서 onCameraChange에 좌표 파라미터가 없어졌던데 카메라 위치 이동할 때 마커 위치 변경 이제 못 하게 막은건지 아니면 다른 방법을 사용해야하는지 질문드립니다.

또 마커의 기본이미지를 다른 이미지로 대체할 수 있을까요?

**Comment by KimSungJin0** [comment]
@yangsh91 

 첫번째 질문에서 저는 `NCameraUpdateReason` 중 if 문을 통해 `NCameraUpdateReason.gesture` 가 감지되면 `setLocationTrackingMode` 를 noFollow로 바꾸는 방식을 적용시켰습니다.
 이런식으로 reason 을 감지해 controller를 작동시켜보시면 될 것 같습니다.


 두번째 질문에서 마커가 현위치 마커를 말씀하시는 것이라면
```
nLocationOverlay = await mapController.getLocationOverlay();

nLocationOverlay.setIcon(
    NOverlayImage.fromAssetImage(Assets.marker.currentActive));
```
 해당 방법으로 현위치 마커를 받아 온 다음 setIcon을 사용해 이미지를 넣어주었습니다.
[이미지 말고 많은 옵션이 있으니 참고 바랍니다.](https://pub.dev/documentation/flutter_naver_map/latest/flutter_naver_map/NLocationOverlay-class.html)

저도 테스트 중이여서 한번 확인해보시길 바랍니다.

**Comment by note11g** [comment]
좌표 파라미터가 없어진 것은 맞습니다.
이는 mapController의 [latLngToScreenLocation](https://note11.dev/flutter_naver_map/element/controller#%EC%9D%B4%EC%99%B8-%EB%A9%94%EC%84%9C%EB%93%9C%EB%93%A4) 메서드를 이용하시어, 활용하시기 바랍니다. 감사합니다.

**Comment by yangsh91** [comment]
좌표 이동은 mapController의 getCameraPosition을 통해 좌표를 가져와서 마커 이동하게 끔 수정했습니다 ! 답변 감사합니다~
