### ISSUE TITLE
Marker Index

### ISSUE THREAD

**Issue by akshatjain-beam** [note11g/flutter_naver_map#88]
I have created markers and set their Zindex, but the Zindex, are not working

zindex of marker1 = 0
zindex of marker2 = -1

**Comment by akshatjain-beam** [comment]
issue resolved

**Comment by akshatjain-beam** [comment]
I am able to update the zindex, but they aren't getting activated until I move the map, even a little

**Comment by note11g** [comment]
Could you provide me with a sample code?

**Comment by akshatjain-beam** [comment]
ahh, its fixed, need to refresh the controller and the index starts working
Thanks
