### ISSUE TITLE
Flutter 3.10.0 대응

### ISSUE THREAD

**Issue by yangster-chief** [note11g/flutter_naver_map#89]
flutter 3.10.0으로 업그레이드했을 때 아래와 같은 에러가 발생합니다.

<img width="1324" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/38216680/52e4dfe1-6736-4623-8090-347fceea7671">

SingletonFlutterWindow가 3.10.0부터 deprecated 되어 생긴 문제입니다. [https://docs.flutter.dev/release/breaking-changes/window-singleton](url)

/// Deprecated. Will be removed in a future version of Flutter.
///
/// This property has been deprecated to prepare for Flutter's upcoming
/// support for multiple views and multiple windows.
///
/// It represents the main view for applications where there is only one
/// view, such as applications designed for single-display mobile devices.
/// If the embedder supports multiple views, it points to the first view
/// created which is assumed to be the main view. It throws if no view has
/// been created yet or if the first view has been removed again.
///
/// The following options exists to migrate code that relies on accessing
/// this deprecated property:
///
/// If a [BuildContext] is available, consider looking up the current
/// [FlutterView] associated with that context via [View.of]. It gives access
/// to the same functionality as this deprecated property. However, the
/// platform-specific functionality has moved to the [PlatformDispatcher],
/// which may be accessed from the view returned by [View.of] via
/// [FlutterView.platformDispatcher]. Using [View.of] with a [BuildContext] is
/// the preferred option to migrate away from this deprecated [window]
/// property.
///
/// If no context is available to look up a [FlutterView], the
/// [platformDispatcher] exposed by this binding can be used directly for
/// platform-specific functionality. It also maintains a list of all available
/// [FlutterView]s in [PlatformDispatcher.views] to access view-specific
/// functionality without a context.
///
/// See also:
///
/// * [View.of] to access view-specific functionality on the [FlutterView]
///   associated with the provided [BuildContext].
/// * [FlutterView.platformDispatcher] to access platform-specific
///   functionality from a given [FlutterView].
/// * [platformDispatcher] on this binding to access the [PlatformDispatcher],
///   which provides platform-specific functionality.
@Deprecated(
  'Look up the current FlutterView from the context via View.of(context) or consult the PlatformDispatcher directly instead. '
  'Deprecated to prepare for the upcoming multi-window support. '
  'This feature was deprecated after v3.7.0-32.0.pre.'
)
ui.SingletonFlutterWindow get window => ui.window;

**Comment by C0routine** [comment]
수정하여 Pullrequests 요청하였습니다~ 확인 부탁드립니다.

**Comment by note11g** [comment]
#90 Merge 하였습니다.
1.0.2 버전에서 수정될 예정입니다. 감사합니다.

**Comment by note11g** [comment]
1.0.2 업로드 이전까지 다음과 같이 수정된 버전을 사용하실 수 있습니다.

``` yaml
flutter_naver_map:
    git:
      url: https://github.com/note11g/flutter_naver_map.git
      ref: aa817f4f905771782e4e31960cd7844ea98be21e
```

**Comment by MinJun-chl** [comment]
220564943ea459d26835118477ce93cbc0c21b3d

**Comment by baekjungkim** [comment]
> 1.0.2 업로드 이전까지 다음과 같이 수정된 버전을 사용하실 수 있습니다.
> 
> ```yaml
> flutter_naver_map:
>     git:
>       url: https://github.com/note11g/flutter_naver_map.git
>       ref: 1bc039f636e9cdfe5aafc8a829e6e9fa8d666bd3
> ```

해당 버전 사용시 에러가 발생합니다.

> Git error. Command: `git clone C:\Users\miclo\AppData\Local\Pub\Cache\git\cache\flutter_naver_map-824fc847413fd721fdce3d45f53d6e995581340b C:\Users\miclo\AppData\Local\Pub\Cache\git\flutter_naver_map-1bc039f636e9cdfe5aafc8a829e6e9fa8d666bd3`
> stdout:
> stderr: Cloning into 'C:\Users\miclo\AppData\Local\Pub\Cache\git\flutter_naver_map-1bc039f636e9cdfe5aafc8a829e6e9fa8d666bd3'...
done.
> error: invalid path '.pubignore '
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by note11g** [comment]
@baekjungkim 안녕하세요. 혹시 다음과 같이 시도해보시겠어요?

```yaml
flutter_naver_map:
    git:
      url: https://github.com/note11g/flutter_naver_map.git
      ref: 1.0.2-dev
```

**Comment by baekjungkim** [comment]
> @baekjungkim 안녕하세요. 혹시 다음과 같이 시도해보시겠어요?
> 
> ```yaml
> flutter_naver_map:
>     git:
>       url: https://github.com/note11g/flutter_naver_map.git
>       ref: 1.0.2-dev
> ```

`
flutter clean
flutter pub cache clean
flutter pub get
`
이렇게 재설치 해도 해당 에러가 발생합니다.

> Git error. Command: `git clone C:\Users\miclo\AppData\Local\Pub\Cache\git\cache\flutter_naver_map-824fc847413fd721fdce3d45f53d6e995581340b C:\Users\miclo\AppData\Local\Pub\Cache\git\flutter_naver_map-f06813b061d85bc3de6d44a328b3a5444a48a834`
> stdout:
> stderr: Cloning into 'C:\Users\miclo\AppData\Local\Pub\Cache\git\flutter_naver_map-f06813b061d85bc3de6d44a328b3a5444a48a834'...
done.
> error: invalid path '.pubignore '
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by hyeyoungmesh** [comment]
> @baekjungkim 안녕하세요. 혹시 다음과 같이 시도해보시겠어요?
> 
> ```yaml
> flutter_naver_map:
>     git:
>       url: https://github.com/note11g/flutter_naver_map.git
>       ref: 1.0.2-dev
> ```

사용가능합니다.

**Comment by note11g** [comment]
@baekjungkim 라이브러리 문제가 아닌, git checkout과 관련된 문제로 보입니다.

**Comment by baekjungkim** [comment]
감사합니다. 어떤 이유인지는 잘 모르겠으나..;
지금은 잘 됩니다 ㅠ

**Comment by YongWoo-8933** [comment]
안녕하세요, @baekjungkim 님과 같은 오류를 겪고 있습니다.
cache도 clean시키고 직접 경로에 가서 삭제도 해봤는데,
오류가 뜨거나 잘 되더라도 flutter_naver_map 없이 업데이트 됩니다.

(package가 없는 모습)
![image](https://github.com/note11g/flutter_naver_map/assets/77825655/3633cbec-75db-406c-a4e1-0d47fa7bbd07)

패키지가 있는 C:\Users\YongWoo\AppData\Local\Pub\Cache\hosted\pub.dev 폴더로 가도 보이지 않고,

C:\Users\YongWoo\AppData\Local\Pub\Cache\git\flutter_naver_map-f06813b061d85bc3de6d44a328b3a5444a48a834
C:\Users\YongWoo\AppData\Local\Pub\Cache\git\cache\flutter_naver_map-824fc847413fd721fdce3d45f53d6e995581340b
위 두 경로 폴더만 추가되어 있습니다.

그래서 import가 제대로 되질 않네요ㅠ

**Comment by BGM-109** [comment]
쏘귯입니다
