### ISSUE TITLE
사용자 Gesture의 최대/최소 줌 레벨 제한 기능의 제공 가능 여부

### ISSUE THREAD

**Issue by ItdaTeam** [note11g/flutter_naver_map#9]
버튼 타입으로 지도 줌 , 아웃은 IF 등으로 제한을 해서 최소 레벨, 최대 레벨 지도 줌 아웃을 제어 가능한데 

핀치 줌아웃은 최대 , 최소 레벨 조정 할수 있는 메소드가 안보여서 문의 드립니다. 

최소로 축소 하면 전세계 지도가 보이는데 가능 하면 최소로 축소 하면 한국정도만 보이게끔 하고 싶어서 문의 드려 봅니다. (핀치줌 한정)

학생이신것 같은데 ^^; 카톡 ID  하나 보내주시면 쿠폰 하나 보내드릴께요 

노고에 정말 감사드립니다.

**Comment by note11g** [comment]
해당 기능을 구현하기 위해서 카메라가 이동 후(줌도 포함됩니다.) 실행되는 onCameraChange 메서드가 도움이 될 것 같습니다.
매개변수로 주어지는 CameraChangeReason이 Gesture이라면 사용자의 터치 제스처에 의해 발생된 것이라고 생각하시고 구현하시면 됩니다.

모든 줌에 적용하시려면, NaverMap 객체에 minZoom 혹은 maxZoom을 인자로 전달해주시면 됩니다.

도움이 되셨으면 좋겠습니다. 감사합니다.

**Comment by note11g** [comment]
@ItdaTeam 이슈가 아닌 것 같아보이므로 Close 하겠습니다.
이슈라고 판단되신다면, 다시 열어주시면 감사하겠습니다.
