### ISSUE TITLE
iOS에서 `NOverlayImage`의 크기가 크게 표시되는 문제

### ISSUE THREAD

**Issue by note11g** [note11g/flutter_naver_map#91]
`NOverlayImage.fromByteArray` 혹은 `NOverlayImage.fromWidget`으로 NOverlayImage를 만들면,
Android에서는 LogicalPixel(DP)로 잘 보여짐. 

그러나, iOS에서는 Pixel 크기로 보여지기 때문에, 24\*24 logical Pixel로 보여야 할 NOverlayImage의 크기가 실제로는 72\*72 logical pixel로 보여짐. (devicePixelRatio가 3인 경우를 가정한 예시입니다.)

**Comment by note11g** [comment]
생각하고 있는 해결법은 다음과 같습니다.

NOverlayImage의 멤버로 Size를 포함하고,
NOverlayImage를 이용하여 overlay에 적용할 때(Native Side의 `NOverlayImage.applyToOverlay`메서드에서), 
devicePixelRatio(scaleFactor)를 적용하여 보여질 Size를 계산하여 overlay의 Size를 지정합니다.
단, NGroundOverlay와 같이 Size를 따로 지정하지 못하는(NGroundOverlay의 경우는 NLatLngBounds로 크기를 지정합니다.) 경우에는 따로 지정하지 않습니다.

*일정이 많이 바쁜 관계로 이렇게 해결법만 정리해두게 되었습니다. 
시간이 나는대로, 적용을 해보고 다시 코멘트 달도록 하겠습니다.
빠르게 대응하지 못해드려 죄송합니다.

**Comment by Dongsu-M** [comment]
NOverlayImage.fromAssetImage()도 동일한 문제가 있는 것 같습니다.ㅜㅜ
왼쪽이 안드로이드, 오른쪽이 아이폰인데요.

"출", "도" 마커가 NOverlayImage.fromAssetImage() 를 이용한 마커이고,
"15.1Km" 가 NOverlayImage.fromWidget() 을 이용한 마커입니다.

<img width="300" alt="스크린샷 2023-05-18 오후 5 40 50" src="https://github.com/note11g/flutter_naver_map/assets/108326895/765cd37e-7218-43a5-8d0d-f9a8c0edafe6">

<img width="220" src="https://github.com/note11g/flutter_naver_map/assets/108326895/2fa6dbe3-aa55-4363-9a6b-0096c93c8fe7"/>

**Comment by Dongsu-M** [comment]
이거 NMarker() 에 size 를 지정해주니 해결되긴 합니다!

**Comment by note11g** [comment]
@Dongsu-M 
네 맞습니다. 그래서 지금 그런 방식으로 해결하고 있는 임시 코드를 공유드리겠습니다.

**Comment by note11g** [comment]
2ec7a70 에서는 fromWidget만 임시로 작성한 코드입니다.
작동하지는 않지만 대략적인 컨셉을 확인하실 수 있습니다.

**Comment by note11g** [comment]
`NOverlayImage.fromAssetImage`를 이용하여 에셋 이미지를 적용하는 경우,
1. 사이즈가 작게 적용되거나,
2. 사이즈가 크게 적용됩니다.
두개의 차이를 분석한 후, 코멘트 드리도록 하겠습니다.

**Comment by Soogyo-In** [comment]
> NOverlayImage.fromAssetImage()도 동일한 문제가 있는 것 같습니다.ㅜㅜ 왼쪽이 안드로이드, 오른쪽이 아이폰인데요.
> 
> "출", "도" 마커가 NOverlayImage.fromAssetImage() 를 이용한 마커이고, "15.1Km" 가 NOverlayImage.fromWidget() 을 이용한 마커입니다.
> 
> <img alt="스크린샷 2023-05-18 오후 5 40 50" width="300" src="https://user-images.githubusercontent.com/108326895/239187414-765cd37e-7218-43a5-8d0d-f9a8c0edafe6.png"> <img alt="" width="220" src="https://user-images.githubusercontent.com/108326895/239187905-2fa6dbe3-aa55-4363-9a6b-0096c93c8fe7.png">

음... 일단 다음 세가지를 확인하고싶습니다. 
* 실제 아이콘 이미지 파일의 사이즈
* android 기기의 해상도(dpi)
* 렌더링 되었을 때 기대하는 logical pixel 단위의 사이즈
Swift 코드를 확인해본 바 iOS 에서는 이미지를 읽어서 scale factor 를 신경쓰지 않고 그립니다. 따라서 하나의 이미지를 읽는다면 테스트 기기의 구성이 안드로이드의 해상도가 아이폰보다 높다면 아이폰에서는 크게 그려질 것이고 반대라면 아이폰에서 작게 그려질 것입니다.

**Comment by note11g** [comment]
#126 PR은 Marker의 해당 현상만 수정하는 PR입니다.
동시에, #130 이슈가 발생하는 중입니다.
`NOverlayImage`를 사용하는 오버레이 개별로 수정하는 방안이 있겠으나,
공통적으로 해결할 수 있는 방안을 생각해보아야 할 듯합니다.
이를 위한 브랜치를 새로 생성하겠습니다.

도와주실 수 있으실까요? @Soogyo-In

**Comment by note11g** [comment]
Test Case (NMarker / NLocationOverlay / NPathOverlay / NMultipartPathOverlay)
- [ ] 사이즈 표시 문제
- [ ] #130

**Comment by note11g** [comment]
수정 후에도, Path / MultipartPath에 대한 문제는 해결되지 않는 것으로 보입니다.
다만, 해당 예시가 `pathWidth = 24dp` / `ImageSize = 12dp`(pixelRatio * 12px) 인 것으로 미루어볼때,
Android 상의 문제인 것 같습니다.

<img width="320" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/67783062/e25c771d-62ac-4c74-906b-0ec9ae996f2d">
<img width="320" alt="image" src="https://github.com/note11g/flutter_naver_map/assets/67783062/8a4ce193-9c78-4dc2-884e-dd4c34108f3a">

**Comment by note11g** [comment]
iOS의 동작이 잘못된 것이 맞음을 확인하였습니다.
위의 예시는 Icon Size가 Padding을 포함하고 있어, 잘못 작성된 예시입니다.

다음은 정상적인 예시입니다. (`zoomLevel=16`)

<img width="320" alt="android screenshot" src="https://github.com/note11g/flutter_naver_map/assets/67783062/c93a98c2-7a76-4d3c-92f3-93abefec13b2"/>
<img width="320" alt="ios screenshot" src="https://github.com/note11g/flutter_naver_map/assets/67783062/aaa03769-9286-4185-8fe2-c9f0675ec509"/>

```dart
const size = 12.0;
final patternWidget = Container(
      width: size,
      height: size,
      decoration: const BoxDecoration(color: Colors.white, shape: BoxShape.circle),
);
final patternImage = await NOverlayImage.fromWidget(
  widget: patternWidget,
  size: const NSize(size, size),
  context: context);

overlay
    ..setWidth(36)
    ..setPatternImage(patternImage);
```

**Comment by note11g** [comment]
수정을 완료하였습니다.
이전 수정사항처럼, 직접 size를 조절하는 것이 아닌 iOS의 UIImage에서 scale 프로퍼티를 이용하여, 정상적으로 표출되도록 수정하였습니다.

**Comment by note11g** [comment]
수정사항은 1.0.3에서 적용될 예정입니다. 감사합니다.

**Comment by note11g** [comment]
`fromAssetImage`에는 여전히 동일한 현상이 발생합니다.
Android와 기존 iOS에서의 fromAssetImage을 제외한 동작과 통일시키는 작업을 진행하겠습니다.

**Comment by note11g** [comment]
해당 커밋에 대한 golden test를 진행하려 하였으나, Integration test에서도 platform view의 golden test는 작동하지 않고, 흰 화면만 나오므로 직접 테스트한 결과를 첨부합니다.

테스트는 iPhone 15 Pro Simulator(devicePixelRatio=3.0)를 활용했습니다. 
비교 대상은 Android Pixel 7 Emulator(devicePixelRatio=3.125)입니다.

정상적인(예상되는) 테스트 결과는 아이폰의 경우 `Container(width: 24, height:32)`가 3배율 이미지와 크기가 같아야 합니다. 안드로이드는 pixelRatio가 3.125이므로, 동일한 크기의 Container가 3배율 이미지보다 약간 커야합니다.

사용한 마커의 1배율 픽셀은 24x32이며, 2배율은 48x64, 3배율은 72x96, 4배율은 96x128 입니다.

<details>
  <summary>테스트한 스크린샷 펼치기</summary>
  
  ### iPhone 15 Pro Simulator (ratio=3.0) - iOS, 실험군
  
  ![Simulator Screenshot - iPhone 15 Pro - 2024-02-17 at 23 16 25](https://github.com/note11g/flutter_naver_map/assets/67783062/a9a4a2b9-30a1-4edb-a7fd-c7ea3a6e3dc6)

  ### Pixel 7 Emulator (ratio=3.125) - Android, 대조군
  
  ![Screenshot_1708179665](https://github.com/note11g/flutter_naver_map/assets/67783062/21bd9f57-67cc-4787-b31e-a7bb882a761f)
</details>

사용한 코드는 다음과 같습니다.
<details>
  <summary>코드 보기</summary>

  ### widget
  ```dart
  return Stack(children: [
      Positioned.fill(child: TransparentPointer(child: mapWidget())),
      Positioned.fill(child: Center(
        child: Container(
          width: 24, height: 32, // 컨테이너의 사이즈와 비교하기 위함.
          color: Colors.blueAccent.withOpacity(0.64)),
        )),
  ]);
  ```

  ### controller
  ```dart
  final marker1 = NMarker(
        id: "1x",
        position: latLng.offsetByMeter(eastMeter: -60),
        icon: const NOverlayImage.fromAssetImage("assets/bar_1x.png"));
  final marker2 = NMarker(
        id: "2x",
        position: latLng.offsetByMeter(eastMeter: -30),
        icon: const NOverlayImage.fromAssetImage("assets/bar_2x.png"));
  final marker3 = NMarker(
        id: "3x",
        position: latLng.offsetByMeter(eastMeter: 30),
        icon: const NOverlayImage.fromAssetImage("assets/bar_3x.png"));
  final marker4 = NMarker(
        id: "4x",
        position: latLng.offsetByMeter(eastMeter: 60),
        icon: const NOverlayImage.fromAssetImage("assets/bar_4x.png"));

  await mapController.addOverlayAll({marker1, marker2, marker3, marker4});
  ```
</details>


다음은 테스트에 사용한 파일 4개입니다. (1x, 2x, 3x, 4x)
![bar_1x](https://github.com/note11g/flutter_naver_map/assets/67783062/d5580532-85cb-4430-a2c7-2d3f2ced192c)![bar_2x](https://github.com/note11g/flutter_naver_map/assets/67783062/f5c3af53-1851-4790-9898-c3e6f035bcc0)![bar_3x](https://github.com/note11g/flutter_naver_map/assets/67783062/59a52aba-74a9-4ff7-927d-b19fa14a449c)![bar_4x](https://github.com/note11g/flutter_naver_map/assets/67783062/a14339d6-9d9a-4f31-93d7-204a01da79bd)

**Comment by note11g** [comment]
1.2.1에서 수정됩니다.

**Comment by yoojin282** [comment]
NOverlayImage.fromAssetImage 사용시 이미지 해상도가 이상하여 질문남겨요.
기본 asset 파일경로(ex: assets/file.png) 로 지정하면 2.0x 3.0x 4.0x 폴더 asset 파일이 적용되지 않는걸로 보이는데
이부분은 사용자가 device pixel ratio에 따라 이미지 사이즈별 파일 경로를 지정해줘야 하는지요?

일단 fromWidget 메소드로 이미지 변환하여 적용하면 문제 없긴합니다.

**Comment by note11g** [comment]
> NOverlayImage.fromAssetImage 사용시 이미지 해상도가 이상하여 질문남겨요. 기본 asset 파일경로(ex: assets/file.png) 로 지정하면 2.0x 3.0x 4.0x 폴더 asset 파일이 적용되지 않는걸로 보이는데 이부분은 사용자가 device pixel ratio에 따라 이미지 사이즈별 파일 경로를 지정해줘야 하는지요?
> 
> 일단 fromWidget 메소드로 이미지 변환하여 적용하면 문제 없긴합니다.

완전히 동일한 사이즈를 표시하기 위해서는 그래야하겠지만,
기본적으로 하나의 이미지로 여러 사이즈에 대응하기 위해, devicePixelRatio를 통해 이미지를 알맞게 표시하고 있습니다.
이는 (Android/iOS), (File/Assets/ByteArray)에 모두 동일한 동작을 하기 위함이기도 합니다.
기본적으로 널리 사용되는 2x/3x/4x 역시, 완전히 동일한 크기가 아닌 유사한 크기로 표시되므로 큰 차이가 없으므로 말씀드린 것처럼 동작합니다.
표시에 사용되는 로직을 간략하게 표현하면 다음과 같습니다.

// imageSize => imageWidth || imageHeight
(imageSize / devicePixelRatio) = usedLogicalPixelOnUi (dp)
