### ISSUE TITLE
안드로이드 debug/release 빌드 에러 : unresolved referebece : style

### ISSUE THREAD

**Issue by yangsh91** [note11g/flutter_naver_map#92]
flutter ver : 3.7.1
android sdk ver : 33.0.1

iOS 시뮬레이터만 주로 이용하다 보니 안드로이드는 지도맵 업데이트 이후 확인을 안 해 봤었는데 확인차 빌드를 해보았는데 
/.pub-cache/hosted/pub.dev/flutter_naver_map-1.0.1/android/src/main/kotlin/dev/note11/flutter_naver_map/view/NaverMap.View.kt (119, 29) : Unresolved reference: style 
라고 나오고 있고 디버그 / 릴리즈 모드 둘다 빌드가 안 됩니다

flutter clean도 해보고 패키지도 다시 받아보고 깃허브 소스에 있는 gradle 버전이랑 맞춰봤는데도 마찬가지인데 저만 안드로이드 빌드할 때 이런건지 이슈가 있었는지 (있었는지 못 찾았지만) 모르겠네요 ㅠ 

<img width="1453" alt="스크린샷 2023-05-12 오전 10 12 55" src="https://github.com/note11g/flutter_naver_map/assets/44184266/3a25abb1-b0bd-4ea6-aa70-d4d7b3ad5991">

**Comment by note11g** [comment]
정확하진 않지만, android gradle dependency에 다음처럼 appcomat을 추가하면 될 수도 있습니다.
```groovy
implementation "androidx.appcompat:appcompat:1.6.1"
```

**Comment by yangsh91** [comment]
@note11g gradle 확인해 보니까 예전에 추가 했었는지 있더라구요 ㅠ  네이티브 쪽은 잘 몰라서 혹시해서 추가로 질문드리고 싶은데 안드로이드쪽에서 네이티브 라이브러리를 사용해야 해서 안드로이드 언어를 코틀린 말고 자바로 변경했는데 플러그인은 코틀린인거 같아서 그러는데 0점대 버전일 때는 문제가 없었는데 버전업 한뒤 언어차이 때문에 충돌날 경우도 있을까요..?

**Comment by note11g** [comment]
@yangsh91 혹시 아직 해당 증상이 발생하고 있을까요?

**Comment by note11g** [comment]
해당 이슈는 오랜 기간동안 답변이 없으셨기에, 일단 Close하도록 하겠습니다.
동일한 이슈가 다시 발생한다면, 이슈를 열어주시면 감사 드리겠습니다.
