### ISSUE TITLE
[건의] NOverlayImage.fromWidget()에 String? tag 파라미터 추가

### ISSUE THREAD

**Issue by Dongsu-M** [note11g/flutter_naver_map#94]
NOverlayImage.fromWidget()의 구현을 보면 캐싱을 하고 있지만, 위젯을 이미지화 한 다음 Uint8List 로 변환하는 작업은 생략이 되지 않습니다.
그래서 이 부분에 대한 캐싱 최적화를 하기 위해 NOverlayImage.fromWidget()에 `String? tag` 파라미터를 추가하는 것을 건의 드립니다.

이게 동작하기 위해서는 우선 ImageUtil에 _hashPathMap 뿐만 아니라 `_tagPathMap`도 추가해서 태그에 대응되는 파일 경로를 담고 있는 맵으로 활용할 수 있을 것 같습니다.

tag가 null이 아닐 경우, ImageUtil을 통해 tag로 파일 경로를 우선 검색할 수 있을 것 같네요.
tag가 null인 경우는 기존과 동일하게 동작합니다.

이렇게 되면 `위젯 -> 이미지화 -> Uint8List` 과정이 생략돼서 좀 더 캐싱이 멋지게 동작할 수 있지 않을까 생각합니다~
혹시 작업 시간이 여의치 않다면 제가 작업해서 PR 올려드릴 수도 있으니, 편하게 말씀해주세요.

**Comment by note11g** [comment]
안녕하세요, @Dongsu-M 님.
먼저, 제안주셔서 감사드립니다.

제가 이해한 바로는, 매번 같은 위젯을 생성할때 이미지로 바꾸어, 해싱을 하는데에 비용이 낭비되는 것 때문에 태그를 통해, 같은 태그면 이미 만들어진 위젯 이미지를 불러오도록 하는 것을 제안주신 것 같은데,

이게 맞을지 여쭙고 싶습니다.

**Comment by Dongsu-M** [comment]
> 안녕하세요, @Dongsu-M 님. 먼저, 제안주셔서 감사드립니다.
> 
> 제가 이해한 바로는, 매번 같은 위젯을 생성할때 이미지로 바꾸어, 해싱을 하는데에 비용이 낭비되는 것 때문에 태그를 통해, 같은 태그면 이미 만들어진 위젯 이미지를 불러오도록 하는 것을 제안주신 것 같은데, 제가 이해한 바가 맞을지 여쭙고 싶습니다.

답변 감사합니다.
말씀하신게 정확히 맞습니다. 태그가 동일하면 동일한 위젯이라 판단하는거죠~

**Comment by note11g** [comment]
> 답변 감사합니다. 말씀하신게 정확히 맞습니다. 태그가 동일하면 동일한 위젯이라 판단하는거죠~

혹시 그러면, 다음과 같이 위젯을 이용하여 생성된 NOverlayImage 인스턴스를 재사용하는 것과는 얻는 이점이 다를까요?
```dart
NOverlayImage? flutterIcon;

void makeFlutterIconAndAddMarker() async {
  if (flutterIcon == null) {
    flutterIcon = await NOverlayImage.fromWidget(
          widget: const FlutterLogo(),
          size: const Size(24, 24),
          context: context);
  }

  final marker = NMarker(id: "icon_test_1", position: latLng1, icon: flutterIcon!);
  final marker2 = NMarker(id: "icon_test_2", position: latLng2, icon: flutterIcon!);
}
```

**Comment by Dongsu-M** [comment]
> > 답변 감사합니다. 말씀하신게 정확히 맞습니다. 태그가 동일하면 동일한 위젯이라 판단하는거죠~
> 
> 혹시 그러면, 다음과 같이 위젯을 이용하여 생성된 NOverlayImage 인스턴스를 재사용하는 것과는 얻는 이점이 다를까요?
> 
> ```dart
> NOverlayImage? flutterIcon;
> 
> void makeFlutterIconAndAddMarker() async {
>   if (flutterIcon == null) {
>     flutterIcon = await NOverlayImage.fromWidget(
>           widget: const FlutterLogo(),
>           size: const Size(24, 24),
>           context: context);
>   }
> 
>   final marker = NMarker(id: "icon_test_1", position: latLng1, icon: flutterIcon!);
>   final marker2 = NMarker(id: "icon_test_2", position: latLng2, icon: flutterIcon!);
> 
>   mapController.addOverlayAll({marker, marker2});
> }
> ```

말씀해주신 방법은 위젯의 종류가 적을 때는 충분히 취할 수 있는 전략인거 같습니다~ 
하지만 위젯의 종류가 많아지는 경우에는 취하기 힘든 전략인거 같아서요.ㅠ

예를들어 내 위치와 특정 위치 사이의 거리를 텍스트 위젯으로 표현하고 싶은 경우를 생각해볼 수 있는데요,
내 위치가 변함에 따라 텍스트의 값이 변하기 때문에 앱 레벨에서 위젯 목록을 모두 가지고 있기에는 부담이 있을 것 같습니다.
(인포 윈도우와 기능적으로는 비슷하지만, dart 코드로 커스터마이징 가능한 인포 윈도우의 느낌으로 활용할 가능성을 생각하고 있습니다.)

**Comment by note11g** [comment]
**라이브러리 외부에서 Map을 만들어서 사용하는 것**과 **라이브러리에 내장하는 것**은 비슷하게 작동하지만, 각각 Trade Off가 있을 것 같습니다.
이 부분은 어떻게 생각하시는지 고견을 여쭙고 싶습니다

**Comment by Dongsu-M** [comment]
> 

라이브러리 외부(앱 레벨)에서 Map을 사용하게 되면 Map<String, NOverlayImage> 타입이 될 것 같네요~
NOverlayImage 를 많이 가지고 있으면 메모리 부담이 있지 않을까했는데, 단순히 _path, _mode 정도만 가지고 있는 객체라 그렇게 사용 가능할 것 같습니다!

이전 답변의 코드 예시에서 충분히 캐치할 수 있는 부분이었는데, 제가 코드 부분을 자세히 살펴보지 않아 추가 리소스를 뺏은 것 같아 죄송하네요.ㅠ
이슈 클로즈해도 좋을 것 같습니다~

**Comment by note11g** [comment]
제안 주신 것 다시 한번 감사드리며, 
추가로 비슷한 질문이나 제안주실 것이 있으시다면 이슈를 다시 열어주시면 감사드리겠습니다.
좋은 하루 되세요:)
