### ISSUE TITLE
marker drag 기능 추가 요청

### ISSUE THREAD

**Issue by kimdindoo** [note11g/flutter_naver_map#97]
다음 업데이트때 marker drag 기능 추가해주시면 감사하겠습니다!

**Comment by note11g** [comment]
안녕하세요. 기능 제안을 주셔서 감사드립니다.
혹시, 이 기능에 대해 자세히 설명해 주실 수 있으실까요?

**Comment by kimdindoo** [comment]
구글 지도를 예를 들면,
`
  /// Signature reporting the new [LatLng] at the start of a drag event.
  final ValueChanged<LatLng>? onDragStart;

  /// Signature reporting the new [LatLng] at the end of a drag event.
  final ValueChanged<LatLng>? onDragEnd;
`

**Comment by note11g** [comment]
마커를 잡고, 끌면 지도상에서 움직이는 기능을 원하시는걸까요?

**Comment by kimdindoo** [comment]
네 맞습니다. 드래그 끝났을때 해당 마커 좌표값을 받을 수 있게끔 원합니다!

**Comment by note11g** [comment]
먼저, 기능 요청에 감사드립니다.

해당 부분은 직접 구현하실 수 있는 기능으로 판단됩니다.
flutter_naver_map은 사용성에 영향을 미치지 않으면서, 직접 구현할 수 있는 기능은 라이브러리에 최대한 포함시키지 않으려 하고 있습니다.
아쉽게도, 해당 부분은 필요성에 대한 검토가 조금 더 필요할 것으로 보입니다.

추가로 주실 의견이 있으시다면, 코멘트를 남겨주세요.
감사합니다. 좋은 하루 되세요:)

**Comment by kimdindoo** [comment]
답변 감사드립니다.  

제가 요구드렸던 기능은 아래 동영상같이 마커를 잡고 드래그하는 기능인데 혹시 이런 기능을 직접 구현할 수 있다는 말씀이 맞으신가요?
https://github.com/note11g/flutter_naver_map/assets/87438680/38c4b2be-9fe5-4885-8170-d67726fbd0de

맞다면 어떤식으로 구현가능할지 도움을 주시면 감사하겠습니다.
