### ISSUE TITLE
스트리트뷰, 파나라마뷰 이런건 안되나요? 

### ISSUE THREAD

**Issue by kotran88** [note11g/flutter_naver_map#99]
https://navermaps.github.io/maps.js.en/docs/tutorial-1-panorama-simple.example.html

문서를 봐도 제가 못찾는건지 보이지않아서요..

**Comment by note11g** [comment]
안녕하세요. 이슈를 남겨주셔서 감사드립니다.
해당 부분은, Javascript를 이용한 **Web Dynamic Map**에서만 가능한 기능으로 보입니다.

[네이버 클라우드 플랫폼 Maps 소개 페이지](https://www.ncloud.com/product/applicationService/maps)의 **제공 서비스** 섹션에서 확인하실 수 있듯, Web Dynamic Map과 Mobile Dynamic Map은 서로 지원하는 기능이 다릅니다.
해당 부분 참고하시어, 이용에 도움이 되셨으면 좋겠습니다.
더 도움이 필요하시다면, 이슈를 다시 오픈해주세요. 감사합니다. 좋은 하루되세요:)
